# automatically generated by the FlatBuffers compiler, do not modify

# namespace: datatypes

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Bytes(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Bytes()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBytes(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Bytes
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Bytes
    def B(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Bytes
    def BAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Bytes
    def BLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Bytes
    def BIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def BytesStart(builder):
    builder.StartObject(1)

def Start(builder):
    BytesStart(builder)

def BytesAddB(builder, b):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(b), 0)

def AddB(builder, b):
    BytesAddB(builder, b)

def BytesStartBVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartBVector(builder, numElems):
    return BytesStartBVector(builder, numElems)

def BytesEnd(builder):
    return builder.EndObject()

def End(builder):
    return BytesEnd(builder)

try:
    from typing import List
except:
    pass

class BytesT(object):

    # BytesT
    def __init__(
        self,
        b = None,
    ):
        self.b = b  # type: Optional[List[int]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        bytes = Bytes()
        bytes.Init(buf, pos)
        return cls.InitFromObj(bytes)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, bytes):
        x = BytesT()
        x._UnPack(bytes)
        return x

    # BytesT
    def _UnPack(self, bytes):
        if bytes is None:
            return
        if not bytes.BIsNone():
            if np is None:
                self.b = []
                for i in range(bytes.BLength()):
                    self.b.append(bytes.B(i))
            else:
                self.b = bytes.BAsNumpy()

    # BytesT
    def Pack(self, builder):
        if self.b is not None:
            if np is not None and type(self.b) is np.ndarray:
                b = builder.CreateNumpyVector(self.b)
            else:
                BytesStartBVector(builder, len(self.b))
                for i in reversed(range(len(self.b))):
                    builder.PrependUint8(self.b[i])
                b = builder.EndVector()
        BytesStart(builder)
        if self.b is not None:
            BytesAddB(builder, b)
        bytes = BytesEnd(builder)
        return bytes
