# automatically generated by the FlatBuffers compiler, do not modify

# namespace: datatypes

# Used for filtering tracker rotations in software
class FilteringType(object):
    NONE = 0
    SMOOTHING = 1
    PREDICTION = 2
