# automatically generated by the FlatBuffers compiler, do not modify

# namespace: datatypes

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# The 4 bytes of an ip address are stored in 32 bits in big endian order.
# We will switch over to fixed size arrays when they are supported better.
class Ipv4Address(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 4

    # Ipv4Address
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Ipv4Address
    def Addr(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

def CreateIpv4Address(builder, addr):
    builder.Prep(4, 4)
    builder.PrependUint32(addr)
    return builder.Offset()


class Ipv4AddressT(object):

    # Ipv4AddressT
    def __init__(
        self,
        addr = 0,
    ):
        self.addr = addr  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        ipv4Address = Ipv4Address()
        ipv4Address.Init(buf, pos)
        return cls.InitFromObj(ipv4Address)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, ipv4Address):
        x = Ipv4AddressT()
        x._UnPack(ipv4Address)
        return x

    # Ipv4AddressT
    def _UnPack(self, ipv4Address):
        if ipv4Address is None:
            return
        self.addr = ipv4Address.Addr()

    # Ipv4AddressT
    def Pack(self, builder):
        return CreateIpv4Address(builder, self.addr)
