# automatically generated by the FlatBuffers compiler, do not modify

# namespace: datatypes

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# General purpose logging datatype
class LogData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LogData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLogData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LogData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LogData
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LogData
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # LogData
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # LogData
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # LogData
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def LogDataStart(builder):
    builder.StartObject(2)

def Start(builder):
    LogDataStart(builder)

def LogDataAddMessage(builder, message):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder, message):
    LogDataAddMessage(builder, message)

def LogDataAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder, data):
    LogDataAddData(builder, data)

def LogDataStartDataVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartDataVector(builder, numElems):
    return LogDataStartDataVector(builder, numElems)

def LogDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return LogDataEnd(builder)

try:
    from typing import List
except:
    pass

class LogDataT(object):

    # LogDataT
    def __init__(
        self,
        message = None,
        data = None,
    ):
        self.message = message  # type: Optional[str]
        self.data = data  # type: Optional[List[int]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        logData = LogData()
        logData.Init(buf, pos)
        return cls.InitFromObj(logData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, logData):
        x = LogDataT()
        x._UnPack(logData)
        return x

    # LogDataT
    def _UnPack(self, logData):
        if logData is None:
            return
        self.message = logData.Message()
        if not logData.DataIsNone():
            if np is None:
                self.data = []
                for i in range(logData.DataLength()):
                    self.data.append(logData.Data(i))
            else:
                self.data = logData.DataAsNumpy()

    # LogDataT
    def Pack(self, builder):
        if self.message is not None:
            message = builder.CreateString(self.message)
        if self.data is not None:
            if np is not None and type(self.data) is np.ndarray:
                data = builder.CreateNumpyVector(self.data)
            else:
                LogDataStartDataVector(builder, len(self.data))
                for i in reversed(range(len(self.data))):
                    builder.PrependUint8(self.data[i])
                data = builder.EndVector()
        LogDataStart(builder)
        if self.message is not None:
            LogDataAddMessage(builder, message)
        if self.data is not None:
            LogDataAddData(builder, data)
        logData = LogDataEnd(builder)
        return logData
