# automatically generated by the FlatBuffers compiler, do not modify

# namespace: datatypes

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.datatypes.DeviceId import DeviceIdT
from solarxr_protocol.datatypes.DeviceId import DeviceId

class TrackerId(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrackerId()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTrackerId(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TrackerId
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The device the tracker is associated with. If there is no hardware device it is
    # associated with, this should be `null`.
    # TrackerId
    def DeviceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = DeviceId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # There are possibly multiple trackers per device. This identifies which one.
    # TrackerId
    def TrackerNum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def TrackerIdStart(builder):
    builder.StartObject(2)

def Start(builder):
    TrackerIdStart(builder)

def TrackerIdAddDeviceId(builder, deviceId):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(deviceId), 0)

def AddDeviceId(builder, deviceId):
    TrackerIdAddDeviceId(builder, deviceId)

def TrackerIdAddTrackerNum(builder, trackerNum):
    builder.PrependUint8Slot(1, trackerNum, 0)

def AddTrackerNum(builder, trackerNum):
    TrackerIdAddTrackerNum(builder, trackerNum)

def TrackerIdEnd(builder):
    return builder.EndObject()

def End(builder):
    return TrackerIdEnd(builder)

try:
    from typing import Optional
except:
    pass

class TrackerIdT(object):

    # TrackerIdT
    def __init__(
        self,
        deviceId = None,
        trackerNum = 0,
    ):
        self.deviceId = deviceId  # type: Optional[DeviceIdT]
        self.trackerNum = trackerNum  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        trackerId = TrackerId()
        trackerId.Init(buf, pos)
        return cls.InitFromObj(trackerId)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, trackerId):
        x = TrackerIdT()
        x._UnPack(trackerId)
        return x

    # TrackerIdT
    def _UnPack(self, trackerId):
        if trackerId is None:
            return
        if trackerId.DeviceId() is not None:
            self.deviceId = DeviceIdT.InitFromObj(trackerId.DeviceId())
        self.trackerNum = trackerId.TrackerNum()

    # TrackerIdT
    def Pack(self, builder):
        TrackerIdStart(builder)
        if self.deviceId is not None:
            deviceId = self.deviceId.Pack(builder)
            TrackerIdAddDeviceId(builder, deviceId)
        TrackerIdAddTrackerNum(builder, self.trackerNum)
        trackerId = TrackerIdEnd(builder)
        return trackerId
