# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tracker

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A mask of the different components in `TrackerComponent`
class TrackerDataMask(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrackerDataMask()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTrackerDataMask(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TrackerDataMask
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TrackerDataMask
    def Info(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TrackerDataMask
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TrackerDataMask
    def Rotation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TrackerDataMask
    def Position(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TrackerDataMask
    def RawAngularVelocity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TrackerDataMask
    def RawAcceleration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TrackerDataMask
    def Temp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TrackerDataMask
    def LinearAcceleration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TrackerDataMask
    def RotationReferenceAdjusted(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TrackerDataMask
    def RotationIdentityAdjusted(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TrackerDataMask
    def Tps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TrackerDataMask
    def RawMagneticVector(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TrackerDataMask
    def StayAligned(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def TrackerDataMaskStart(builder):
    builder.StartObject(13)

def Start(builder):
    TrackerDataMaskStart(builder)

def TrackerDataMaskAddInfo(builder, info):
    builder.PrependBoolSlot(0, info, 0)

def AddInfo(builder, info):
    TrackerDataMaskAddInfo(builder, info)

def TrackerDataMaskAddStatus(builder, status):
    builder.PrependBoolSlot(1, status, 0)

def AddStatus(builder, status):
    TrackerDataMaskAddStatus(builder, status)

def TrackerDataMaskAddRotation(builder, rotation):
    builder.PrependBoolSlot(2, rotation, 0)

def AddRotation(builder, rotation):
    TrackerDataMaskAddRotation(builder, rotation)

def TrackerDataMaskAddPosition(builder, position):
    builder.PrependBoolSlot(3, position, 0)

def AddPosition(builder, position):
    TrackerDataMaskAddPosition(builder, position)

def TrackerDataMaskAddRawAngularVelocity(builder, rawAngularVelocity):
    builder.PrependBoolSlot(4, rawAngularVelocity, 0)

def AddRawAngularVelocity(builder, rawAngularVelocity):
    TrackerDataMaskAddRawAngularVelocity(builder, rawAngularVelocity)

def TrackerDataMaskAddRawAcceleration(builder, rawAcceleration):
    builder.PrependBoolSlot(5, rawAcceleration, 0)

def AddRawAcceleration(builder, rawAcceleration):
    TrackerDataMaskAddRawAcceleration(builder, rawAcceleration)

def TrackerDataMaskAddTemp(builder, temp):
    builder.PrependBoolSlot(6, temp, 0)

def AddTemp(builder, temp):
    TrackerDataMaskAddTemp(builder, temp)

def TrackerDataMaskAddLinearAcceleration(builder, linearAcceleration):
    builder.PrependBoolSlot(7, linearAcceleration, 0)

def AddLinearAcceleration(builder, linearAcceleration):
    TrackerDataMaskAddLinearAcceleration(builder, linearAcceleration)

def TrackerDataMaskAddRotationReferenceAdjusted(builder, rotationReferenceAdjusted):
    builder.PrependBoolSlot(8, rotationReferenceAdjusted, 0)

def AddRotationReferenceAdjusted(builder, rotationReferenceAdjusted):
    TrackerDataMaskAddRotationReferenceAdjusted(builder, rotationReferenceAdjusted)

def TrackerDataMaskAddRotationIdentityAdjusted(builder, rotationIdentityAdjusted):
    builder.PrependBoolSlot(9, rotationIdentityAdjusted, 0)

def AddRotationIdentityAdjusted(builder, rotationIdentityAdjusted):
    TrackerDataMaskAddRotationIdentityAdjusted(builder, rotationIdentityAdjusted)

def TrackerDataMaskAddTps(builder, tps):
    builder.PrependBoolSlot(10, tps, 0)

def AddTps(builder, tps):
    TrackerDataMaskAddTps(builder, tps)

def TrackerDataMaskAddRawMagneticVector(builder, rawMagneticVector):
    builder.PrependBoolSlot(11, rawMagneticVector, 0)

def AddRawMagneticVector(builder, rawMagneticVector):
    TrackerDataMaskAddRawMagneticVector(builder, rawMagneticVector)

def TrackerDataMaskAddStayAligned(builder, stayAligned):
    builder.PrependBoolSlot(12, stayAligned, 0)

def AddStayAligned(builder, stayAligned):
    TrackerDataMaskAddStayAligned(builder, stayAligned)

def TrackerDataMaskEnd(builder):
    return builder.EndObject()

def End(builder):
    return TrackerDataMaskEnd(builder)


class TrackerDataMaskT(object):

    # TrackerDataMaskT
    def __init__(
        self,
        info = False,
        status = False,
        rotation = False,
        position = False,
        rawAngularVelocity = False,
        rawAcceleration = False,
        temp = False,
        linearAcceleration = False,
        rotationReferenceAdjusted = False,
        rotationIdentityAdjusted = False,
        tps = False,
        rawMagneticVector = False,
        stayAligned = False,
    ):
        self.info = info  # type: bool
        self.status = status  # type: bool
        self.rotation = rotation  # type: bool
        self.position = position  # type: bool
        self.rawAngularVelocity = rawAngularVelocity  # type: bool
        self.rawAcceleration = rawAcceleration  # type: bool
        self.temp = temp  # type: bool
        self.linearAcceleration = linearAcceleration  # type: bool
        self.rotationReferenceAdjusted = rotationReferenceAdjusted  # type: bool
        self.rotationIdentityAdjusted = rotationIdentityAdjusted  # type: bool
        self.tps = tps  # type: bool
        self.rawMagneticVector = rawMagneticVector  # type: bool
        self.stayAligned = stayAligned  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        trackerDataMask = TrackerDataMask()
        trackerDataMask.Init(buf, pos)
        return cls.InitFromObj(trackerDataMask)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, trackerDataMask):
        x = TrackerDataMaskT()
        x._UnPack(trackerDataMask)
        return x

    # TrackerDataMaskT
    def _UnPack(self, trackerDataMask):
        if trackerDataMask is None:
            return
        self.info = trackerDataMask.Info()
        self.status = trackerDataMask.Status()
        self.rotation = trackerDataMask.Rotation()
        self.position = trackerDataMask.Position()
        self.rawAngularVelocity = trackerDataMask.RawAngularVelocity()
        self.rawAcceleration = trackerDataMask.RawAcceleration()
        self.temp = trackerDataMask.Temp()
        self.linearAcceleration = trackerDataMask.LinearAcceleration()
        self.rotationReferenceAdjusted = trackerDataMask.RotationReferenceAdjusted()
        self.rotationIdentityAdjusted = trackerDataMask.RotationIdentityAdjusted()
        self.tps = trackerDataMask.Tps()
        self.rawMagneticVector = trackerDataMask.RawMagneticVector()
        self.stayAligned = trackerDataMask.StayAligned()

    # TrackerDataMaskT
    def Pack(self, builder):
        TrackerDataMaskStart(builder)
        TrackerDataMaskAddInfo(builder, self.info)
        TrackerDataMaskAddStatus(builder, self.status)
        TrackerDataMaskAddRotation(builder, self.rotation)
        TrackerDataMaskAddPosition(builder, self.position)
        TrackerDataMaskAddRawAngularVelocity(builder, self.rawAngularVelocity)
        TrackerDataMaskAddRawAcceleration(builder, self.rawAcceleration)
        TrackerDataMaskAddTemp(builder, self.temp)
        TrackerDataMaskAddLinearAcceleration(builder, self.linearAcceleration)
        TrackerDataMaskAddRotationReferenceAdjusted(builder, self.rotationReferenceAdjusted)
        TrackerDataMaskAddRotationIdentityAdjusted(builder, self.rotationIdentityAdjusted)
        TrackerDataMaskAddTps(builder, self.tps)
        TrackerDataMaskAddRawMagneticVector(builder, self.rawMagneticVector)
        TrackerDataMaskAddStayAligned(builder, self.stayAligned)
        trackerDataMask = TrackerDataMaskEnd(builder)
        return trackerDataMask
