# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tracker

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.datatypes.HzF32 import HzF32T
from solarxr_protocol.datatypes.math.Quat import QuatT
from solarxr_protocol.datatypes.HzF32 import HzF32
from solarxr_protocol.datatypes.math.Quat import Quat

# Static description of a tracker
class TrackerInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrackerInfo()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTrackerInfo(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TrackerInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TrackerInfo
    def ImuType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # The user-assigned role of the tracker.
    # TrackerInfo
    def BodyPart(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # average samples per second
    # TrackerInfo
    def PollRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            obj = HzF32()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # The orientation of the tracker when mounted on the body
    # TrackerInfo
    def MountingOrientation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = Quat()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Should the tracker's settings be editable by the user
    # TrackerInfo
    def Editable(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Indicates if the tracker is computed (solved position and rotation)
    # TrackerInfo
    def IsComputed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Indicates if the tracker is using an IMU for its tracking data
    # TrackerInfo
    def IsImu(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # A human-friendly name to display as the name of the tracker.
    # TrackerInfo
    def DisplayName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # name to display as the name of the tracker set by the user
    # TrackerInfo
    def CustomName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Whether to allow yaw drift compensation for this tracker or not.
    # TrackerInfo
    def AllowDriftCompensation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Mounting Reset orientation overrides the current `mounting_orientation` of
    # the tracker, this orientation is not saved and needs to be calculated
    # each time the server is ran
    # TrackerInfo
    def MountingResetOrientation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = o + self._tab.Pos
            obj = Quat()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Indicates if the tracker is actually an HMD
    # TrackerInfo
    def IsHmd(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TrackerInfo
    def Magnetometer(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Indicates what type of data the tracker sends (note: it always ends up being rotation in the end)
    # TrackerInfo
    def DataSupport(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def TrackerInfoStart(builder):
    builder.StartObject(14)

def Start(builder):
    TrackerInfoStart(builder)

def TrackerInfoAddImuType(builder, imuType):
    builder.PrependUint16Slot(0, imuType, 0)

def AddImuType(builder, imuType):
    TrackerInfoAddImuType(builder, imuType)

def TrackerInfoAddBodyPart(builder, bodyPart):
    builder.PrependUint8Slot(1, bodyPart, 0)

def AddBodyPart(builder, bodyPart):
    TrackerInfoAddBodyPart(builder, bodyPart)

def TrackerInfoAddPollRate(builder, pollRate):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(pollRate), 0)

def AddPollRate(builder, pollRate):
    TrackerInfoAddPollRate(builder, pollRate)

def TrackerInfoAddMountingOrientation(builder, mountingOrientation):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(mountingOrientation), 0)

def AddMountingOrientation(builder, mountingOrientation):
    TrackerInfoAddMountingOrientation(builder, mountingOrientation)

def TrackerInfoAddEditable(builder, editable):
    builder.PrependBoolSlot(4, editable, 0)

def AddEditable(builder, editable):
    TrackerInfoAddEditable(builder, editable)

def TrackerInfoAddIsComputed(builder, isComputed):
    builder.PrependBoolSlot(5, isComputed, 0)

def AddIsComputed(builder, isComputed):
    TrackerInfoAddIsComputed(builder, isComputed)

def TrackerInfoAddIsImu(builder, isImu):
    builder.PrependBoolSlot(6, isImu, 0)

def AddIsImu(builder, isImu):
    TrackerInfoAddIsImu(builder, isImu)

def TrackerInfoAddDisplayName(builder, displayName):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(displayName), 0)

def AddDisplayName(builder, displayName):
    TrackerInfoAddDisplayName(builder, displayName)

def TrackerInfoAddCustomName(builder, customName):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(customName), 0)

def AddCustomName(builder, customName):
    TrackerInfoAddCustomName(builder, customName)

def TrackerInfoAddAllowDriftCompensation(builder, allowDriftCompensation):
    builder.PrependBoolSlot(9, allowDriftCompensation, 0)

def AddAllowDriftCompensation(builder, allowDriftCompensation):
    TrackerInfoAddAllowDriftCompensation(builder, allowDriftCompensation)

def TrackerInfoAddMountingResetOrientation(builder, mountingResetOrientation):
    builder.PrependStructSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(mountingResetOrientation), 0)

def AddMountingResetOrientation(builder, mountingResetOrientation):
    TrackerInfoAddMountingResetOrientation(builder, mountingResetOrientation)

def TrackerInfoAddIsHmd(builder, isHmd):
    builder.PrependBoolSlot(11, isHmd, 0)

def AddIsHmd(builder, isHmd):
    TrackerInfoAddIsHmd(builder, isHmd)

def TrackerInfoAddMagnetometer(builder, magnetometer):
    builder.PrependUint8Slot(12, magnetometer, 0)

def AddMagnetometer(builder, magnetometer):
    TrackerInfoAddMagnetometer(builder, magnetometer)

def TrackerInfoAddDataSupport(builder, dataSupport):
    builder.PrependUint8Slot(13, dataSupport, 0)

def AddDataSupport(builder, dataSupport):
    TrackerInfoAddDataSupport(builder, dataSupport)

def TrackerInfoEnd(builder):
    return builder.EndObject()

def End(builder):
    return TrackerInfoEnd(builder)

try:
    from typing import Optional
except:
    pass

class TrackerInfoT(object):

    # TrackerInfoT
    def __init__(
        self,
        imuType = 0,
        bodyPart = 0,
        pollRate = None,
        mountingOrientation = None,
        editable = False,
        isComputed = False,
        isImu = False,
        displayName = None,
        customName = None,
        allowDriftCompensation = False,
        mountingResetOrientation = None,
        isHmd = False,
        magnetometer = 0,
        dataSupport = 0,
    ):
        self.imuType = imuType  # type: int
        self.bodyPart = bodyPart  # type: int
        self.pollRate = pollRate  # type: Optional[HzF32T]
        self.mountingOrientation = mountingOrientation  # type: Optional[QuatT]
        self.editable = editable  # type: bool
        self.isComputed = isComputed  # type: bool
        self.isImu = isImu  # type: bool
        self.displayName = displayName  # type: Optional[str]
        self.customName = customName  # type: Optional[str]
        self.allowDriftCompensation = allowDriftCompensation  # type: bool
        self.mountingResetOrientation = mountingResetOrientation  # type: Optional[QuatT]
        self.isHmd = isHmd  # type: bool
        self.magnetometer = magnetometer  # type: int
        self.dataSupport = dataSupport  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        trackerInfo = TrackerInfo()
        trackerInfo.Init(buf, pos)
        return cls.InitFromObj(trackerInfo)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, trackerInfo):
        x = TrackerInfoT()
        x._UnPack(trackerInfo)
        return x

    # TrackerInfoT
    def _UnPack(self, trackerInfo):
        if trackerInfo is None:
            return
        self.imuType = trackerInfo.ImuType()
        self.bodyPart = trackerInfo.BodyPart()
        if trackerInfo.PollRate() is not None:
            self.pollRate = HzF32T.InitFromObj(trackerInfo.PollRate())
        if trackerInfo.MountingOrientation() is not None:
            self.mountingOrientation = QuatT.InitFromObj(trackerInfo.MountingOrientation())
        self.editable = trackerInfo.Editable()
        self.isComputed = trackerInfo.IsComputed()
        self.isImu = trackerInfo.IsImu()
        self.displayName = trackerInfo.DisplayName()
        self.customName = trackerInfo.CustomName()
        self.allowDriftCompensation = trackerInfo.AllowDriftCompensation()
        if trackerInfo.MountingResetOrientation() is not None:
            self.mountingResetOrientation = QuatT.InitFromObj(trackerInfo.MountingResetOrientation())
        self.isHmd = trackerInfo.IsHmd()
        self.magnetometer = trackerInfo.Magnetometer()
        self.dataSupport = trackerInfo.DataSupport()

    # TrackerInfoT
    def Pack(self, builder):
        if self.displayName is not None:
            displayName = builder.CreateString(self.displayName)
        if self.customName is not None:
            customName = builder.CreateString(self.customName)
        TrackerInfoStart(builder)
        TrackerInfoAddImuType(builder, self.imuType)
        TrackerInfoAddBodyPart(builder, self.bodyPart)
        if self.pollRate is not None:
            pollRate = self.pollRate.Pack(builder)
            TrackerInfoAddPollRate(builder, pollRate)
        if self.mountingOrientation is not None:
            mountingOrientation = self.mountingOrientation.Pack(builder)
            TrackerInfoAddMountingOrientation(builder, mountingOrientation)
        TrackerInfoAddEditable(builder, self.editable)
        TrackerInfoAddIsComputed(builder, self.isComputed)
        TrackerInfoAddIsImu(builder, self.isImu)
        if self.displayName is not None:
            TrackerInfoAddDisplayName(builder, displayName)
        if self.customName is not None:
            TrackerInfoAddCustomName(builder, customName)
        TrackerInfoAddAllowDriftCompensation(builder, self.allowDriftCompensation)
        if self.mountingResetOrientation is not None:
            mountingResetOrientation = self.mountingResetOrientation.Pack(builder)
            TrackerInfoAddMountingResetOrientation(builder, mountingResetOrientation)
        TrackerInfoAddIsHmd(builder, self.isHmd)
        TrackerInfoAddMagnetometer(builder, self.magnetometer)
        TrackerInfoAddDataSupport(builder, self.dataSupport)
        trackerInfo = TrackerInfoEnd(builder)
        return trackerInfo
