# automatically generated by the FlatBuffers compiler, do not modify

# namespace: stay_aligned

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StayAlignedTracker(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StayAlignedTracker()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStayAlignedTracker(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StayAlignedTracker
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StayAlignedTracker
    def YawCorrectionInDeg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # StayAlignedTracker
    def LockedErrorInDeg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # StayAlignedTracker
    def CenterErrorInDeg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # StayAlignedTracker
    def NeighborErrorInDeg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # StayAlignedTracker
    def Locked(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def StayAlignedTrackerStart(builder):
    builder.StartObject(5)

def Start(builder):
    StayAlignedTrackerStart(builder)

def StayAlignedTrackerAddYawCorrectionInDeg(builder, yawCorrectionInDeg):
    builder.PrependFloat32Slot(0, yawCorrectionInDeg, 0.0)

def AddYawCorrectionInDeg(builder, yawCorrectionInDeg):
    StayAlignedTrackerAddYawCorrectionInDeg(builder, yawCorrectionInDeg)

def StayAlignedTrackerAddLockedErrorInDeg(builder, lockedErrorInDeg):
    builder.PrependFloat32Slot(1, lockedErrorInDeg, 0.0)

def AddLockedErrorInDeg(builder, lockedErrorInDeg):
    StayAlignedTrackerAddLockedErrorInDeg(builder, lockedErrorInDeg)

def StayAlignedTrackerAddCenterErrorInDeg(builder, centerErrorInDeg):
    builder.PrependFloat32Slot(2, centerErrorInDeg, 0.0)

def AddCenterErrorInDeg(builder, centerErrorInDeg):
    StayAlignedTrackerAddCenterErrorInDeg(builder, centerErrorInDeg)

def StayAlignedTrackerAddNeighborErrorInDeg(builder, neighborErrorInDeg):
    builder.PrependFloat32Slot(3, neighborErrorInDeg, 0.0)

def AddNeighborErrorInDeg(builder, neighborErrorInDeg):
    StayAlignedTrackerAddNeighborErrorInDeg(builder, neighborErrorInDeg)

def StayAlignedTrackerAddLocked(builder, locked):
    builder.PrependBoolSlot(4, locked, 0)

def AddLocked(builder, locked):
    StayAlignedTrackerAddLocked(builder, locked)

def StayAlignedTrackerEnd(builder):
    return builder.EndObject()

def End(builder):
    return StayAlignedTrackerEnd(builder)


class StayAlignedTrackerT(object):

    # StayAlignedTrackerT
    def __init__(
        self,
        yawCorrectionInDeg = 0.0,
        lockedErrorInDeg = 0.0,
        centerErrorInDeg = 0.0,
        neighborErrorInDeg = 0.0,
        locked = False,
    ):
        self.yawCorrectionInDeg = yawCorrectionInDeg  # type: float
        self.lockedErrorInDeg = lockedErrorInDeg  # type: float
        self.centerErrorInDeg = centerErrorInDeg  # type: float
        self.neighborErrorInDeg = neighborErrorInDeg  # type: float
        self.locked = locked  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        stayAlignedTracker = StayAlignedTracker()
        stayAlignedTracker.Init(buf, pos)
        return cls.InitFromObj(stayAlignedTracker)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, stayAlignedTracker):
        x = StayAlignedTrackerT()
        x._UnPack(stayAlignedTracker)
        return x

    # StayAlignedTrackerT
    def _UnPack(self, stayAlignedTracker):
        if stayAlignedTracker is None:
            return
        self.yawCorrectionInDeg = stayAlignedTracker.YawCorrectionInDeg()
        self.lockedErrorInDeg = stayAlignedTracker.LockedErrorInDeg()
        self.centerErrorInDeg = stayAlignedTracker.CenterErrorInDeg()
        self.neighborErrorInDeg = stayAlignedTracker.NeighborErrorInDeg()
        self.locked = stayAlignedTracker.Locked()

    # StayAlignedTrackerT
    def Pack(self, builder):
        StayAlignedTrackerStart(builder)
        StayAlignedTrackerAddYawCorrectionInDeg(builder, self.yawCorrectionInDeg)
        StayAlignedTrackerAddLockedErrorInDeg(builder, self.lockedErrorInDeg)
        StayAlignedTrackerAddCenterErrorInDeg(builder, self.centerErrorInDeg)
        StayAlignedTrackerAddNeighborErrorInDeg(builder, self.neighborErrorInDeg)
        StayAlignedTrackerAddLocked(builder, self.locked)
        stayAlignedTracker = StayAlignedTrackerEnd(builder)
        return stayAlignedTracker
