# automatically generated by the FlatBuffers compiler, do not modify

# namespace: data_feed

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.data_feed.DataFeedMessage import DataFeedMessageCreator

class DataFeedMessageHeader(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DataFeedMessageHeader()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDataFeedMessageHeader(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DataFeedMessageHeader
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DataFeedMessageHeader
    def MessageType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # DataFeedMessageHeader
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def DataFeedMessageHeaderStart(builder):
    builder.StartObject(2)

def Start(builder):
    DataFeedMessageHeaderStart(builder)

def DataFeedMessageHeaderAddMessageType(builder, messageType):
    builder.PrependUint8Slot(0, messageType, 0)

def AddMessageType(builder, messageType):
    DataFeedMessageHeaderAddMessageType(builder, messageType)

def DataFeedMessageHeaderAddMessage(builder, message):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder, message):
    DataFeedMessageHeaderAddMessage(builder, message)

def DataFeedMessageHeaderEnd(builder):
    return builder.EndObject()

def End(builder):
    return DataFeedMessageHeaderEnd(builder)

try:
    from typing import Union
except:
    pass

class DataFeedMessageHeaderT(object):

    # DataFeedMessageHeaderT
    def __init__(
        self,
        messageType = 0,
        message = None,
    ):
        self.messageType = messageType  # type: int
        self.message = message  # type: Union[None, 'PollDataFeedT', 'StartDataFeedT', 'DataFeedUpdateT', 'DataFeedConfigT']

    @classmethod
    def InitFromBuf(cls, buf, pos):
        dataFeedMessageHeader = DataFeedMessageHeader()
        dataFeedMessageHeader.Init(buf, pos)
        return cls.InitFromObj(dataFeedMessageHeader)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, dataFeedMessageHeader):
        x = DataFeedMessageHeaderT()
        x._UnPack(dataFeedMessageHeader)
        return x

    # DataFeedMessageHeaderT
    def _UnPack(self, dataFeedMessageHeader):
        if dataFeedMessageHeader is None:
            return
        self.messageType = dataFeedMessageHeader.MessageType()
        self.message = DataFeedMessageCreator(self.messageType, dataFeedMessageHeader.Message())

    # DataFeedMessageHeaderT
    def Pack(self, builder):
        if self.message is not None:
            message = self.message.Pack(builder)
        DataFeedMessageHeaderStart(builder)
        DataFeedMessageHeaderAddMessageType(builder, self.messageType)
        if self.message is not None:
            DataFeedMessageHeaderAddMessage(builder, message)
        dataFeedMessageHeader = DataFeedMessageHeaderEnd(builder)
        return dataFeedMessageHeader
