# automatically generated by the FlatBuffers compiler, do not modify

# namespace: data_feed

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.data_feed.Bone import BoneT
from solarxr_protocol.data_feed.device_data.DeviceData import DeviceDataT
from solarxr_protocol.data_feed.server.ServerGuards import ServerGuardsT
from solarxr_protocol.data_feed.stay_aligned.StayAlignedPose import StayAlignedPoseT
from solarxr_protocol.data_feed.tracker.TrackerData import TrackerDataT
from solarxr_protocol.data_feed.Bone import Bone
from solarxr_protocol.data_feed.device_data.DeviceData import DeviceData
from solarxr_protocol.data_feed.server.ServerGuards import ServerGuards
from solarxr_protocol.data_feed.stay_aligned.StayAlignedPose import StayAlignedPose
from solarxr_protocol.data_feed.tracker.TrackerData import TrackerData

# All of the data components related to a single data feed. A data feed is comprised
# of device data, and tracker data.
#
# A data feed might send data only when it changes/updates, and we should make no
# assumptions that the data is actually delivered. If you want to guarantee
# delivery and avoid dropped observations of data (such as a user-initiated
# button press), it is better to use the RPC system.
class DataFeedUpdate(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DataFeedUpdate()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDataFeedUpdate(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DataFeedUpdate
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DataFeedUpdate
    def Devices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = DeviceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DataFeedUpdate
    def DevicesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DataFeedUpdate
    def DevicesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # DataFeedUpdate
    def SyntheticTrackers(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = TrackerData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DataFeedUpdate
    def SyntheticTrackersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DataFeedUpdate
    def SyntheticTrackersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # This must represent a set, where there is no more than one bone for a `BodyPart`.
    # DataFeedUpdate
    def Bones(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Bone()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DataFeedUpdate
    def BonesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DataFeedUpdate
    def BonesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # DataFeedUpdate
    def StayAlignedPose(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = StayAlignedPose()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DataFeedUpdate
    def Index(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # DataFeedUpdate
    def ServerGuards(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = ServerGuards()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def DataFeedUpdateStart(builder):
    builder.StartObject(6)

def Start(builder):
    DataFeedUpdateStart(builder)

def DataFeedUpdateAddDevices(builder, devices):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(devices), 0)

def AddDevices(builder, devices):
    DataFeedUpdateAddDevices(builder, devices)

def DataFeedUpdateStartDevicesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDevicesVector(builder, numElems):
    return DataFeedUpdateStartDevicesVector(builder, numElems)

def DataFeedUpdateAddSyntheticTrackers(builder, syntheticTrackers):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(syntheticTrackers), 0)

def AddSyntheticTrackers(builder, syntheticTrackers):
    DataFeedUpdateAddSyntheticTrackers(builder, syntheticTrackers)

def DataFeedUpdateStartSyntheticTrackersVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSyntheticTrackersVector(builder, numElems):
    return DataFeedUpdateStartSyntheticTrackersVector(builder, numElems)

def DataFeedUpdateAddBones(builder, bones):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(bones), 0)

def AddBones(builder, bones):
    DataFeedUpdateAddBones(builder, bones)

def DataFeedUpdateStartBonesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartBonesVector(builder, numElems):
    return DataFeedUpdateStartBonesVector(builder, numElems)

def DataFeedUpdateAddStayAlignedPose(builder, stayAlignedPose):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(stayAlignedPose), 0)

def AddStayAlignedPose(builder, stayAlignedPose):
    DataFeedUpdateAddStayAlignedPose(builder, stayAlignedPose)

def DataFeedUpdateAddIndex(builder, index):
    builder.PrependUint8Slot(4, index, 0)

def AddIndex(builder, index):
    DataFeedUpdateAddIndex(builder, index)

def DataFeedUpdateAddServerGuards(builder, serverGuards):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(serverGuards), 0)

def AddServerGuards(builder, serverGuards):
    DataFeedUpdateAddServerGuards(builder, serverGuards)

def DataFeedUpdateEnd(builder):
    return builder.EndObject()

def End(builder):
    return DataFeedUpdateEnd(builder)

try:
    from typing import List, Optional
except:
    pass

class DataFeedUpdateT(object):

    # DataFeedUpdateT
    def __init__(
        self,
        devices = None,
        syntheticTrackers = None,
        bones = None,
        stayAlignedPose = None,
        index = 0,
        serverGuards = None,
    ):
        self.devices = devices  # type: Optional[List[DeviceDataT]]
        self.syntheticTrackers = syntheticTrackers  # type: Optional[List[TrackerDataT]]
        self.bones = bones  # type: Optional[List[BoneT]]
        self.stayAlignedPose = stayAlignedPose  # type: Optional[StayAlignedPoseT]
        self.index = index  # type: int
        self.serverGuards = serverGuards  # type: Optional[ServerGuardsT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        dataFeedUpdate = DataFeedUpdate()
        dataFeedUpdate.Init(buf, pos)
        return cls.InitFromObj(dataFeedUpdate)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, dataFeedUpdate):
        x = DataFeedUpdateT()
        x._UnPack(dataFeedUpdate)
        return x

    # DataFeedUpdateT
    def _UnPack(self, dataFeedUpdate):
        if dataFeedUpdate is None:
            return
        if not dataFeedUpdate.DevicesIsNone():
            self.devices = []
            for i in range(dataFeedUpdate.DevicesLength()):
                if dataFeedUpdate.Devices(i) is None:
                    self.devices.append(None)
                else:
                    deviceData_ = DeviceDataT.InitFromObj(dataFeedUpdate.Devices(i))
                    self.devices.append(deviceData_)
        if not dataFeedUpdate.SyntheticTrackersIsNone():
            self.syntheticTrackers = []
            for i in range(dataFeedUpdate.SyntheticTrackersLength()):
                if dataFeedUpdate.SyntheticTrackers(i) is None:
                    self.syntheticTrackers.append(None)
                else:
                    trackerData_ = TrackerDataT.InitFromObj(dataFeedUpdate.SyntheticTrackers(i))
                    self.syntheticTrackers.append(trackerData_)
        if not dataFeedUpdate.BonesIsNone():
            self.bones = []
            for i in range(dataFeedUpdate.BonesLength()):
                if dataFeedUpdate.Bones(i) is None:
                    self.bones.append(None)
                else:
                    bone_ = BoneT.InitFromObj(dataFeedUpdate.Bones(i))
                    self.bones.append(bone_)
        if dataFeedUpdate.StayAlignedPose() is not None:
            self.stayAlignedPose = StayAlignedPoseT.InitFromObj(dataFeedUpdate.StayAlignedPose())
        self.index = dataFeedUpdate.Index()
        if dataFeedUpdate.ServerGuards() is not None:
            self.serverGuards = ServerGuardsT.InitFromObj(dataFeedUpdate.ServerGuards())

    # DataFeedUpdateT
    def Pack(self, builder):
        if self.devices is not None:
            deviceslist = []
            for i in range(len(self.devices)):
                deviceslist.append(self.devices[i].Pack(builder))
            DataFeedUpdateStartDevicesVector(builder, len(self.devices))
            for i in reversed(range(len(self.devices))):
                builder.PrependUOffsetTRelative(deviceslist[i])
            devices = builder.EndVector()
        if self.syntheticTrackers is not None:
            syntheticTrackerslist = []
            for i in range(len(self.syntheticTrackers)):
                syntheticTrackerslist.append(self.syntheticTrackers[i].Pack(builder))
            DataFeedUpdateStartSyntheticTrackersVector(builder, len(self.syntheticTrackers))
            for i in reversed(range(len(self.syntheticTrackers))):
                builder.PrependUOffsetTRelative(syntheticTrackerslist[i])
            syntheticTrackers = builder.EndVector()
        if self.bones is not None:
            boneslist = []
            for i in range(len(self.bones)):
                boneslist.append(self.bones[i].Pack(builder))
            DataFeedUpdateStartBonesVector(builder, len(self.bones))
            for i in reversed(range(len(self.bones))):
                builder.PrependUOffsetTRelative(boneslist[i])
            bones = builder.EndVector()
        if self.stayAlignedPose is not None:
            stayAlignedPose = self.stayAlignedPose.Pack(builder)
        if self.serverGuards is not None:
            serverGuards = self.serverGuards.Pack(builder)
        DataFeedUpdateStart(builder)
        if self.devices is not None:
            DataFeedUpdateAddDevices(builder, devices)
        if self.syntheticTrackers is not None:
            DataFeedUpdateAddSyntheticTrackers(builder, syntheticTrackers)
        if self.bones is not None:
            DataFeedUpdateAddBones(builder, bones)
        if self.stayAlignedPose is not None:
            DataFeedUpdateAddStayAlignedPose(builder, stayAlignedPose)
        DataFeedUpdateAddIndex(builder, self.index)
        if self.serverGuards is not None:
            DataFeedUpdateAddServerGuards(builder, serverGuards)
        dataFeedUpdate = DataFeedUpdateEnd(builder)
        return dataFeedUpdate
