# automatically generated by the FlatBuffers compiler, do not modify

# namespace: data_feed

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.data_feed.DataFeedConfig import DataFeedConfigT
from solarxr_protocol.data_feed.DataFeedConfig import DataFeedConfig

# Requests for the other party to send `data_feeds`.
# For example, GUI requests for position data to be sent from server.
#
# When sending a new `StartFeed`, the old data feeds should stop being sent.
# We still support multiple data feeds at the same time, because `data_feeds`
# is a list.
#
# Multiple data feeds are useful to get data at different frequencies.
class StartDataFeed(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StartDataFeed()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStartDataFeed(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StartDataFeed
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StartDataFeed
    def DataFeeds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = DataFeedConfig()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StartDataFeed
    def DataFeedsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StartDataFeed
    def DataFeedsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def StartDataFeedStart(builder):
    builder.StartObject(1)

def Start(builder):
    StartDataFeedStart(builder)

def StartDataFeedAddDataFeeds(builder, dataFeeds):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(dataFeeds), 0)

def AddDataFeeds(builder, dataFeeds):
    StartDataFeedAddDataFeeds(builder, dataFeeds)

def StartDataFeedStartDataFeedsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDataFeedsVector(builder, numElems):
    return StartDataFeedStartDataFeedsVector(builder, numElems)

def StartDataFeedEnd(builder):
    return builder.EndObject()

def End(builder):
    return StartDataFeedEnd(builder)

try:
    from typing import List
except:
    pass

class StartDataFeedT(object):

    # StartDataFeedT
    def __init__(
        self,
        dataFeeds = None,
    ):
        self.dataFeeds = dataFeeds  # type: Optional[List[DataFeedConfigT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        startDataFeed = StartDataFeed()
        startDataFeed.Init(buf, pos)
        return cls.InitFromObj(startDataFeed)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, startDataFeed):
        x = StartDataFeedT()
        x._UnPack(startDataFeed)
        return x

    # StartDataFeedT
    def _UnPack(self, startDataFeed):
        if startDataFeed is None:
            return
        if not startDataFeed.DataFeedsIsNone():
            self.dataFeeds = []
            for i in range(startDataFeed.DataFeedsLength()):
                if startDataFeed.DataFeeds(i) is None:
                    self.dataFeeds.append(None)
                else:
                    dataFeedConfig_ = DataFeedConfigT.InitFromObj(startDataFeed.DataFeeds(i))
                    self.dataFeeds.append(dataFeedConfig_)

    # StartDataFeedT
    def Pack(self, builder):
        if self.dataFeeds is not None:
            dataFeedslist = []
            for i in range(len(self.dataFeeds)):
                dataFeedslist.append(self.dataFeeds[i].Pack(builder))
            StartDataFeedStartDataFeedsVector(builder, len(self.dataFeeds))
            for i in reversed(range(len(self.dataFeeds))):
                builder.PrependUOffsetTRelative(dataFeedslist[i])
            dataFeeds = builder.EndVector()
        StartDataFeedStart(builder)
        if self.dataFeeds is not None:
            StartDataFeedAddDataFeeds(builder, dataFeeds)
        startDataFeed = StartDataFeedEnd(builder)
        return startDataFeed
