# automatically generated by the FlatBuffers compiler, do not modify

# namespace: solarxr_protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.data_feed.DataFeedMessageHeader import DataFeedMessageHeaderT
from solarxr_protocol.pub_sub.PubSubHeader import PubSubHeaderT
from solarxr_protocol.rpc.RpcMessageHeader import RpcMessageHeaderT
from solarxr_protocol.data_feed.DataFeedMessageHeader import DataFeedMessageHeader
from solarxr_protocol.pub_sub.PubSubHeader import PubSubHeader
from solarxr_protocol.rpc.RpcMessageHeader import RpcMessageHeader

# MessageBundle contains all of the messages for the data feed system and the
# rpc system that will be sent in one buffer.
class MessageBundle(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MessageBundle()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMessageBundle(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MessageBundle
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MessageBundle
    def DataFeedMsgs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = DataFeedMessageHeader()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MessageBundle
    def DataFeedMsgsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MessageBundle
    def DataFeedMsgsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # MessageBundle
    def RpcMsgs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = RpcMessageHeader()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MessageBundle
    def RpcMsgsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MessageBundle
    def RpcMsgsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # MessageBundle
    def PubSubMsgs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = PubSubHeader()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MessageBundle
    def PubSubMsgsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MessageBundle
    def PubSubMsgsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def MessageBundleStart(builder):
    builder.StartObject(3)

def Start(builder):
    MessageBundleStart(builder)

def MessageBundleAddDataFeedMsgs(builder, dataFeedMsgs):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(dataFeedMsgs), 0)

def AddDataFeedMsgs(builder, dataFeedMsgs):
    MessageBundleAddDataFeedMsgs(builder, dataFeedMsgs)

def MessageBundleStartDataFeedMsgsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDataFeedMsgsVector(builder, numElems):
    return MessageBundleStartDataFeedMsgsVector(builder, numElems)

def MessageBundleAddRpcMsgs(builder, rpcMsgs):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(rpcMsgs), 0)

def AddRpcMsgs(builder, rpcMsgs):
    MessageBundleAddRpcMsgs(builder, rpcMsgs)

def MessageBundleStartRpcMsgsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRpcMsgsVector(builder, numElems):
    return MessageBundleStartRpcMsgsVector(builder, numElems)

def MessageBundleAddPubSubMsgs(builder, pubSubMsgs):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(pubSubMsgs), 0)

def AddPubSubMsgs(builder, pubSubMsgs):
    MessageBundleAddPubSubMsgs(builder, pubSubMsgs)

def MessageBundleStartPubSubMsgsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartPubSubMsgsVector(builder, numElems):
    return MessageBundleStartPubSubMsgsVector(builder, numElems)

def MessageBundleEnd(builder):
    return builder.EndObject()

def End(builder):
    return MessageBundleEnd(builder)

try:
    from typing import List
except:
    pass

class MessageBundleT(object):

    # MessageBundleT
    def __init__(
        self,
        dataFeedMsgs = None,
        rpcMsgs = None,
        pubSubMsgs = None,
    ):
        self.dataFeedMsgs = dataFeedMsgs  # type: Optional[List[DataFeedMessageHeaderT]]
        self.rpcMsgs = rpcMsgs  # type: Optional[List[RpcMessageHeaderT]]
        self.pubSubMsgs = pubSubMsgs  # type: Optional[List[PubSubHeaderT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        messageBundle = MessageBundle()
        messageBundle.Init(buf, pos)
        return cls.InitFromObj(messageBundle)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, messageBundle):
        x = MessageBundleT()
        x._UnPack(messageBundle)
        return x

    # MessageBundleT
    def _UnPack(self, messageBundle):
        if messageBundle is None:
            return
        if not messageBundle.DataFeedMsgsIsNone():
            self.dataFeedMsgs = []
            for i in range(messageBundle.DataFeedMsgsLength()):
                if messageBundle.DataFeedMsgs(i) is None:
                    self.dataFeedMsgs.append(None)
                else:
                    dataFeedMessageHeader_ = DataFeedMessageHeaderT.InitFromObj(messageBundle.DataFeedMsgs(i))
                    self.dataFeedMsgs.append(dataFeedMessageHeader_)
        if not messageBundle.RpcMsgsIsNone():
            self.rpcMsgs = []
            for i in range(messageBundle.RpcMsgsLength()):
                if messageBundle.RpcMsgs(i) is None:
                    self.rpcMsgs.append(None)
                else:
                    rpcMessageHeader_ = RpcMessageHeaderT.InitFromObj(messageBundle.RpcMsgs(i))
                    self.rpcMsgs.append(rpcMessageHeader_)
        if not messageBundle.PubSubMsgsIsNone():
            self.pubSubMsgs = []
            for i in range(messageBundle.PubSubMsgsLength()):
                if messageBundle.PubSubMsgs(i) is None:
                    self.pubSubMsgs.append(None)
                else:
                    pubSubHeader_ = PubSubHeaderT.InitFromObj(messageBundle.PubSubMsgs(i))
                    self.pubSubMsgs.append(pubSubHeader_)

    # MessageBundleT
    def Pack(self, builder):
        if self.dataFeedMsgs is not None:
            dataFeedMsgslist = []
            for i in range(len(self.dataFeedMsgs)):
                dataFeedMsgslist.append(self.dataFeedMsgs[i].Pack(builder))
            MessageBundleStartDataFeedMsgsVector(builder, len(self.dataFeedMsgs))
            for i in reversed(range(len(self.dataFeedMsgs))):
                builder.PrependUOffsetTRelative(dataFeedMsgslist[i])
            dataFeedMsgs = builder.EndVector()
        if self.rpcMsgs is not None:
            rpcMsgslist = []
            for i in range(len(self.rpcMsgs)):
                rpcMsgslist.append(self.rpcMsgs[i].Pack(builder))
            MessageBundleStartRpcMsgsVector(builder, len(self.rpcMsgs))
            for i in reversed(range(len(self.rpcMsgs))):
                builder.PrependUOffsetTRelative(rpcMsgslist[i])
            rpcMsgs = builder.EndVector()
        if self.pubSubMsgs is not None:
            pubSubMsgslist = []
            for i in range(len(self.pubSubMsgs)):
                pubSubMsgslist.append(self.pubSubMsgs[i].Pack(builder))
            MessageBundleStartPubSubMsgsVector(builder, len(self.pubSubMsgs))
            for i in reversed(range(len(self.pubSubMsgs))):
                builder.PrependUOffsetTRelative(pubSubMsgslist[i])
            pubSubMsgs = builder.EndVector()
        MessageBundleStart(builder)
        if self.dataFeedMsgs is not None:
            MessageBundleAddDataFeedMsgs(builder, dataFeedMsgs)
        if self.rpcMsgs is not None:
            MessageBundleAddRpcMsgs(builder, rpcMsgs)
        if self.pubSubMsgs is not None:
            MessageBundleAddPubSubMsgs(builder, pubSubMsgs)
        messageBundle = MessageBundleEnd(builder)
        return messageBundle
