# automatically generated by the FlatBuffers compiler, do not modify

# namespace: server

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ServerGuards(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ServerGuards()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsServerGuards(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ServerGuards
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ServerGuards
    def CanDoMounting(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ServerGuards
    def CanDoYawReset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ServerGuards
    def CanDoUserHeightCalibration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def ServerGuardsStart(builder):
    builder.StartObject(3)

def Start(builder):
    ServerGuardsStart(builder)

def ServerGuardsAddCanDoMounting(builder, canDoMounting):
    builder.PrependBoolSlot(0, canDoMounting, 0)

def AddCanDoMounting(builder, canDoMounting):
    ServerGuardsAddCanDoMounting(builder, canDoMounting)

def ServerGuardsAddCanDoYawReset(builder, canDoYawReset):
    builder.PrependBoolSlot(1, canDoYawReset, 0)

def AddCanDoYawReset(builder, canDoYawReset):
    ServerGuardsAddCanDoYawReset(builder, canDoYawReset)

def ServerGuardsAddCanDoUserHeightCalibration(builder, canDoUserHeightCalibration):
    builder.PrependBoolSlot(2, canDoUserHeightCalibration, 0)

def AddCanDoUserHeightCalibration(builder, canDoUserHeightCalibration):
    ServerGuardsAddCanDoUserHeightCalibration(builder, canDoUserHeightCalibration)

def ServerGuardsEnd(builder):
    return builder.EndObject()

def End(builder):
    return ServerGuardsEnd(builder)


class ServerGuardsT(object):

    # ServerGuardsT
    def __init__(
        self,
        canDoMounting = False,
        canDoYawReset = False,
        canDoUserHeightCalibration = False,
    ):
        self.canDoMounting = canDoMounting  # type: bool
        self.canDoYawReset = canDoYawReset  # type: bool
        self.canDoUserHeightCalibration = canDoUserHeightCalibration  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        serverGuards = ServerGuards()
        serverGuards.Init(buf, pos)
        return cls.InitFromObj(serverGuards)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, serverGuards):
        x = ServerGuardsT()
        x._UnPack(serverGuards)
        return x

    # ServerGuardsT
    def _UnPack(self, serverGuards):
        if serverGuards is None:
            return
        self.canDoMounting = serverGuards.CanDoMounting()
        self.canDoYawReset = serverGuards.CanDoYawReset()
        self.canDoUserHeightCalibration = serverGuards.CanDoUserHeightCalibration()

    # ServerGuardsT
    def Pack(self, builder):
        ServerGuardsStart(builder)
        ServerGuardsAddCanDoMounting(builder, self.canDoMounting)
        ServerGuardsAddCanDoYawReset(builder, self.canDoYawReset)
        ServerGuardsAddCanDoUserHeightCalibration(builder, self.canDoUserHeightCalibration)
        serverGuards = ServerGuardsEnd(builder)
        return serverGuards
