# automatically generated by the FlatBuffers compiler, do not modify

# namespace: settings

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LegTweaksSettings(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LegTweaksSettings()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLegTweaksSettings(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LegTweaksSettings
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LegTweaksSettings
    def CorrectionStrength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return None

def LegTweaksSettingsStart(builder):
    builder.StartObject(1)

def Start(builder):
    LegTweaksSettingsStart(builder)

def LegTweaksSettingsAddCorrectionStrength(builder, correctionStrength):
    builder.PrependFloat32Slot(0, correctionStrength, None)

def AddCorrectionStrength(builder, correctionStrength):
    LegTweaksSettingsAddCorrectionStrength(builder, correctionStrength)

def LegTweaksSettingsEnd(builder):
    return builder.EndObject()

def End(builder):
    return LegTweaksSettingsEnd(builder)

try:
    from typing import Optional
except:
    pass

class LegTweaksSettingsT(object):

    # LegTweaksSettingsT
    def __init__(
        self,
        correctionStrength = None,
    ):
        self.correctionStrength = correctionStrength  # type: Optional[float]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        legTweaksSettings = LegTweaksSettings()
        legTweaksSettings.Init(buf, pos)
        return cls.InitFromObj(legTweaksSettings)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, legTweaksSettings):
        x = LegTweaksSettingsT()
        x._UnPack(legTweaksSettings)
        return x

    # LegTweaksSettingsT
    def _UnPack(self, legTweaksSettings):
        if legTweaksSettings is None:
            return
        self.correctionStrength = legTweaksSettings.CorrectionStrength()

    # LegTweaksSettingsT
    def Pack(self, builder):
        LegTweaksSettingsStart(builder)
        LegTweaksSettingsAddCorrectionStrength(builder, self.correctionStrength)
        legTweaksSettings = LegTweaksSettingsEnd(builder)
        return legTweaksSettings
