# automatically generated by the FlatBuffers compiler, do not modify

# namespace: settings

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Settings for the skeletal model that are ratios.
# These values range from 0 to 1.
class ModelRatios(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ModelRatios()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsModelRatios(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ModelRatios
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ModelRatios
    def ImputeWaistFromChestHip(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return None

    # ModelRatios
    def ImputeWaistFromChestLegs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return None

    # ModelRatios
    def ImputeHipFromChestLegs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return None

    # ModelRatios
    def ImputeHipFromWaistLegs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return None

    # Hip's yaw and roll is set to the average of legs when 1.0
    # ModelRatios
    def InterpHipLegs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return None

    # Knee trackers' yaw and roll is set to the lower leg's when 1.0
    # ModelRatios
    def InterpKneeTrackerAnkle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return None

    # Upper leg's yaw and roll is set to the lower leg's when 1.0
    # ModelRatios
    def InterpKneeAnkle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return None

def ModelRatiosStart(builder):
    builder.StartObject(7)

def Start(builder):
    ModelRatiosStart(builder)

def ModelRatiosAddImputeWaistFromChestHip(builder, imputeWaistFromChestHip):
    builder.PrependFloat32Slot(0, imputeWaistFromChestHip, None)

def AddImputeWaistFromChestHip(builder, imputeWaistFromChestHip):
    ModelRatiosAddImputeWaistFromChestHip(builder, imputeWaistFromChestHip)

def ModelRatiosAddImputeWaistFromChestLegs(builder, imputeWaistFromChestLegs):
    builder.PrependFloat32Slot(1, imputeWaistFromChestLegs, None)

def AddImputeWaistFromChestLegs(builder, imputeWaistFromChestLegs):
    ModelRatiosAddImputeWaistFromChestLegs(builder, imputeWaistFromChestLegs)

def ModelRatiosAddImputeHipFromChestLegs(builder, imputeHipFromChestLegs):
    builder.PrependFloat32Slot(2, imputeHipFromChestLegs, None)

def AddImputeHipFromChestLegs(builder, imputeHipFromChestLegs):
    ModelRatiosAddImputeHipFromChestLegs(builder, imputeHipFromChestLegs)

def ModelRatiosAddImputeHipFromWaistLegs(builder, imputeHipFromWaistLegs):
    builder.PrependFloat32Slot(3, imputeHipFromWaistLegs, None)

def AddImputeHipFromWaistLegs(builder, imputeHipFromWaistLegs):
    ModelRatiosAddImputeHipFromWaistLegs(builder, imputeHipFromWaistLegs)

def ModelRatiosAddInterpHipLegs(builder, interpHipLegs):
    builder.PrependFloat32Slot(4, interpHipLegs, None)

def AddInterpHipLegs(builder, interpHipLegs):
    ModelRatiosAddInterpHipLegs(builder, interpHipLegs)

def ModelRatiosAddInterpKneeTrackerAnkle(builder, interpKneeTrackerAnkle):
    builder.PrependFloat32Slot(5, interpKneeTrackerAnkle, None)

def AddInterpKneeTrackerAnkle(builder, interpKneeTrackerAnkle):
    ModelRatiosAddInterpKneeTrackerAnkle(builder, interpKneeTrackerAnkle)

def ModelRatiosAddInterpKneeAnkle(builder, interpKneeAnkle):
    builder.PrependFloat32Slot(6, interpKneeAnkle, None)

def AddInterpKneeAnkle(builder, interpKneeAnkle):
    ModelRatiosAddInterpKneeAnkle(builder, interpKneeAnkle)

def ModelRatiosEnd(builder):
    return builder.EndObject()

def End(builder):
    return ModelRatiosEnd(builder)

try:
    from typing import Optional
except:
    pass

class ModelRatiosT(object):

    # ModelRatiosT
    def __init__(
        self,
        imputeWaistFromChestHip = None,
        imputeWaistFromChestLegs = None,
        imputeHipFromChestLegs = None,
        imputeHipFromWaistLegs = None,
        interpHipLegs = None,
        interpKneeTrackerAnkle = None,
        interpKneeAnkle = None,
    ):
        self.imputeWaistFromChestHip = imputeWaistFromChestHip  # type: Optional[float]
        self.imputeWaistFromChestLegs = imputeWaistFromChestLegs  # type: Optional[float]
        self.imputeHipFromChestLegs = imputeHipFromChestLegs  # type: Optional[float]
        self.imputeHipFromWaistLegs = imputeHipFromWaistLegs  # type: Optional[float]
        self.interpHipLegs = interpHipLegs  # type: Optional[float]
        self.interpKneeTrackerAnkle = interpKneeTrackerAnkle  # type: Optional[float]
        self.interpKneeAnkle = interpKneeAnkle  # type: Optional[float]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        modelRatios = ModelRatios()
        modelRatios.Init(buf, pos)
        return cls.InitFromObj(modelRatios)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, modelRatios):
        x = ModelRatiosT()
        x._UnPack(modelRatios)
        return x

    # ModelRatiosT
    def _UnPack(self, modelRatios):
        if modelRatios is None:
            return
        self.imputeWaistFromChestHip = modelRatios.ImputeWaistFromChestHip()
        self.imputeWaistFromChestLegs = modelRatios.ImputeWaistFromChestLegs()
        self.imputeHipFromChestLegs = modelRatios.ImputeHipFromChestLegs()
        self.imputeHipFromWaistLegs = modelRatios.ImputeHipFromWaistLegs()
        self.interpHipLegs = modelRatios.InterpHipLegs()
        self.interpKneeTrackerAnkle = modelRatios.InterpKneeTrackerAnkle()
        self.interpKneeAnkle = modelRatios.InterpKneeAnkle()

    # ModelRatiosT
    def Pack(self, builder):
        ModelRatiosStart(builder)
        ModelRatiosAddImputeWaistFromChestHip(builder, self.imputeWaistFromChestHip)
        ModelRatiosAddImputeWaistFromChestLegs(builder, self.imputeWaistFromChestLegs)
        ModelRatiosAddImputeHipFromChestLegs(builder, self.imputeHipFromChestLegs)
        ModelRatiosAddImputeHipFromWaistLegs(builder, self.imputeHipFromWaistLegs)
        ModelRatiosAddInterpHipLegs(builder, self.interpHipLegs)
        ModelRatiosAddInterpKneeTrackerAnkle(builder, self.interpKneeTrackerAnkle)
        ModelRatiosAddInterpKneeAnkle(builder, self.interpKneeAnkle)
        modelRatios = ModelRatiosEnd(builder)
        return modelRatios
