# automatically generated by the FlatBuffers compiler, do not modify

# namespace: settings

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.rpc.settings.LegTweaksSettings import LegTweaksSettingsT
from solarxr_protocol.rpc.settings.ModelRatios import ModelRatiosT
from solarxr_protocol.rpc.settings.ModelToggles import ModelTogglesT
from solarxr_protocol.rpc.settings.SkeletonHeight import SkeletonHeightT
from solarxr_protocol.rpc.settings.LegTweaksSettings import LegTweaksSettings
from solarxr_protocol.rpc.settings.ModelRatios import ModelRatios
from solarxr_protocol.rpc.settings.ModelToggles import ModelToggles
from solarxr_protocol.rpc.settings.SkeletonHeight import SkeletonHeight

# Settings for the skeletal model.
class ModelSettings(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ModelSettings()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsModelSettings(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ModelSettings
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ModelSettings
    def Toggles(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = ModelToggles()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelSettings
    def Ratios(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = ModelRatios()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelSettings
    def LegTweaks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = LegTweaksSettings()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ModelSettings
    def SkeletonHeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = SkeletonHeight()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ModelSettingsStart(builder):
    builder.StartObject(4)

def Start(builder):
    ModelSettingsStart(builder)

def ModelSettingsAddToggles(builder, toggles):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(toggles), 0)

def AddToggles(builder, toggles):
    ModelSettingsAddToggles(builder, toggles)

def ModelSettingsAddRatios(builder, ratios):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(ratios), 0)

def AddRatios(builder, ratios):
    ModelSettingsAddRatios(builder, ratios)

def ModelSettingsAddLegTweaks(builder, legTweaks):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(legTweaks), 0)

def AddLegTweaks(builder, legTweaks):
    ModelSettingsAddLegTweaks(builder, legTweaks)

def ModelSettingsAddSkeletonHeight(builder, skeletonHeight):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(skeletonHeight), 0)

def AddSkeletonHeight(builder, skeletonHeight):
    ModelSettingsAddSkeletonHeight(builder, skeletonHeight)

def ModelSettingsEnd(builder):
    return builder.EndObject()

def End(builder):
    return ModelSettingsEnd(builder)

try:
    from typing import Optional
except:
    pass

class ModelSettingsT(object):

    # ModelSettingsT
    def __init__(
        self,
        toggles = None,
        ratios = None,
        legTweaks = None,
        skeletonHeight = None,
    ):
        self.toggles = toggles  # type: Optional[ModelTogglesT]
        self.ratios = ratios  # type: Optional[ModelRatiosT]
        self.legTweaks = legTweaks  # type: Optional[LegTweaksSettingsT]
        self.skeletonHeight = skeletonHeight  # type: Optional[SkeletonHeightT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        modelSettings = ModelSettings()
        modelSettings.Init(buf, pos)
        return cls.InitFromObj(modelSettings)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, modelSettings):
        x = ModelSettingsT()
        x._UnPack(modelSettings)
        return x

    # ModelSettingsT
    def _UnPack(self, modelSettings):
        if modelSettings is None:
            return
        if modelSettings.Toggles() is not None:
            self.toggles = ModelTogglesT.InitFromObj(modelSettings.Toggles())
        if modelSettings.Ratios() is not None:
            self.ratios = ModelRatiosT.InitFromObj(modelSettings.Ratios())
        if modelSettings.LegTweaks() is not None:
            self.legTweaks = LegTweaksSettingsT.InitFromObj(modelSettings.LegTweaks())
        if modelSettings.SkeletonHeight() is not None:
            self.skeletonHeight = SkeletonHeightT.InitFromObj(modelSettings.SkeletonHeight())

    # ModelSettingsT
    def Pack(self, builder):
        if self.toggles is not None:
            toggles = self.toggles.Pack(builder)
        if self.ratios is not None:
            ratios = self.ratios.Pack(builder)
        if self.legTweaks is not None:
            legTweaks = self.legTweaks.Pack(builder)
        if self.skeletonHeight is not None:
            skeletonHeight = self.skeletonHeight.Pack(builder)
        ModelSettingsStart(builder)
        if self.toggles is not None:
            ModelSettingsAddToggles(builder, toggles)
        if self.ratios is not None:
            ModelSettingsAddRatios(builder, ratios)
        if self.legTweaks is not None:
            ModelSettingsAddLegTweaks(builder, legTweaks)
        if self.skeletonHeight is not None:
            ModelSettingsAddSkeletonHeight(builder, skeletonHeight)
        modelSettings = ModelSettingsEnd(builder)
        return modelSettings
