# automatically generated by the FlatBuffers compiler, do not modify

# namespace: settings

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Settings for the skeletal model that are toggles.
class ModelToggles(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ModelToggles()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsModelToggles(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ModelToggles
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ModelToggles
    def ExtendedSpine(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return None

    # ModelToggles
    def ExtendedPelvis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return None

    # ModelToggles
    def ExtendedKnee(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return None

    # ModelToggles
    def ForceArmsFromHmd(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return None

    # ModelToggles
    def FloorClip(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return None

    # ModelToggles
    def SkatingCorrection(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return None

    # ModelToggles
    def ToeSnap(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return None

    # ModelToggles
    def FootPlant(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return None

    # ModelToggles
    def SelfLocalization(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return None

    # ModelToggles
    def UsePosition(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return None

    # ModelToggles
    def EnforceConstraints(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return None

    # ModelToggles
    def CorrectConstraints(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return None

def ModelTogglesStart(builder):
    builder.StartObject(13)

def Start(builder):
    ModelTogglesStart(builder)

def ModelTogglesAddExtendedSpine(builder, extendedSpine):
    builder.PrependBoolSlot(0, extendedSpine, None)

def AddExtendedSpine(builder, extendedSpine):
    ModelTogglesAddExtendedSpine(builder, extendedSpine)

def ModelTogglesAddExtendedPelvis(builder, extendedPelvis):
    builder.PrependBoolSlot(1, extendedPelvis, None)

def AddExtendedPelvis(builder, extendedPelvis):
    ModelTogglesAddExtendedPelvis(builder, extendedPelvis)

def ModelTogglesAddExtendedKnee(builder, extendedKnee):
    builder.PrependBoolSlot(2, extendedKnee, None)

def AddExtendedKnee(builder, extendedKnee):
    ModelTogglesAddExtendedKnee(builder, extendedKnee)

def ModelTogglesAddForceArmsFromHmd(builder, forceArmsFromHmd):
    builder.PrependBoolSlot(3, forceArmsFromHmd, None)

def AddForceArmsFromHmd(builder, forceArmsFromHmd):
    ModelTogglesAddForceArmsFromHmd(builder, forceArmsFromHmd)

def ModelTogglesAddFloorClip(builder, floorClip):
    builder.PrependBoolSlot(4, floorClip, None)

def AddFloorClip(builder, floorClip):
    ModelTogglesAddFloorClip(builder, floorClip)

def ModelTogglesAddSkatingCorrection(builder, skatingCorrection):
    builder.PrependBoolSlot(5, skatingCorrection, None)

def AddSkatingCorrection(builder, skatingCorrection):
    ModelTogglesAddSkatingCorrection(builder, skatingCorrection)

def ModelTogglesAddToeSnap(builder, toeSnap):
    builder.PrependBoolSlot(7, toeSnap, None)

def AddToeSnap(builder, toeSnap):
    ModelTogglesAddToeSnap(builder, toeSnap)

def ModelTogglesAddFootPlant(builder, footPlant):
    builder.PrependBoolSlot(8, footPlant, None)

def AddFootPlant(builder, footPlant):
    ModelTogglesAddFootPlant(builder, footPlant)

def ModelTogglesAddSelfLocalization(builder, selfLocalization):
    builder.PrependBoolSlot(9, selfLocalization, None)

def AddSelfLocalization(builder, selfLocalization):
    ModelTogglesAddSelfLocalization(builder, selfLocalization)

def ModelTogglesAddUsePosition(builder, usePosition):
    builder.PrependBoolSlot(10, usePosition, None)

def AddUsePosition(builder, usePosition):
    ModelTogglesAddUsePosition(builder, usePosition)

def ModelTogglesAddEnforceConstraints(builder, enforceConstraints):
    builder.PrependBoolSlot(11, enforceConstraints, None)

def AddEnforceConstraints(builder, enforceConstraints):
    ModelTogglesAddEnforceConstraints(builder, enforceConstraints)

def ModelTogglesAddCorrectConstraints(builder, correctConstraints):
    builder.PrependBoolSlot(12, correctConstraints, None)

def AddCorrectConstraints(builder, correctConstraints):
    ModelTogglesAddCorrectConstraints(builder, correctConstraints)

def ModelTogglesEnd(builder):
    return builder.EndObject()

def End(builder):
    return ModelTogglesEnd(builder)

try:
    from typing import Optional
except:
    pass

class ModelTogglesT(object):

    # ModelTogglesT
    def __init__(
        self,
        extendedSpine = None,
        extendedPelvis = None,
        extendedKnee = None,
        forceArmsFromHmd = None,
        floorClip = None,
        skatingCorrection = None,
        toeSnap = None,
        footPlant = None,
        selfLocalization = None,
        usePosition = None,
        enforceConstraints = None,
        correctConstraints = None,
    ):
        self.extendedSpine = extendedSpine  # type: Optional[bool]
        self.extendedPelvis = extendedPelvis  # type: Optional[bool]
        self.extendedKnee = extendedKnee  # type: Optional[bool]
        self.forceArmsFromHmd = forceArmsFromHmd  # type: Optional[bool]
        self.floorClip = floorClip  # type: Optional[bool]
        self.skatingCorrection = skatingCorrection  # type: Optional[bool]
        self.toeSnap = toeSnap  # type: Optional[bool]
        self.footPlant = footPlant  # type: Optional[bool]
        self.selfLocalization = selfLocalization  # type: Optional[bool]
        self.usePosition = usePosition  # type: Optional[bool]
        self.enforceConstraints = enforceConstraints  # type: Optional[bool]
        self.correctConstraints = correctConstraints  # type: Optional[bool]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        modelToggles = ModelToggles()
        modelToggles.Init(buf, pos)
        return cls.InitFromObj(modelToggles)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, modelToggles):
        x = ModelTogglesT()
        x._UnPack(modelToggles)
        return x

    # ModelTogglesT
    def _UnPack(self, modelToggles):
        if modelToggles is None:
            return
        self.extendedSpine = modelToggles.ExtendedSpine()
        self.extendedPelvis = modelToggles.ExtendedPelvis()
        self.extendedKnee = modelToggles.ExtendedKnee()
        self.forceArmsFromHmd = modelToggles.ForceArmsFromHmd()
        self.floorClip = modelToggles.FloorClip()
        self.skatingCorrection = modelToggles.SkatingCorrection()
        self.toeSnap = modelToggles.ToeSnap()
        self.footPlant = modelToggles.FootPlant()
        self.selfLocalization = modelToggles.SelfLocalization()
        self.usePosition = modelToggles.UsePosition()
        self.enforceConstraints = modelToggles.EnforceConstraints()
        self.correctConstraints = modelToggles.CorrectConstraints()

    # ModelTogglesT
    def Pack(self, builder):
        ModelTogglesStart(builder)
        ModelTogglesAddExtendedSpine(builder, self.extendedSpine)
        ModelTogglesAddExtendedPelvis(builder, self.extendedPelvis)
        ModelTogglesAddExtendedKnee(builder, self.extendedKnee)
        ModelTogglesAddForceArmsFromHmd(builder, self.forceArmsFromHmd)
        ModelTogglesAddFloorClip(builder, self.floorClip)
        ModelTogglesAddSkatingCorrection(builder, self.skatingCorrection)
        ModelTogglesAddToeSnap(builder, self.toeSnap)
        ModelTogglesAddFootPlant(builder, self.footPlant)
        ModelTogglesAddSelfLocalization(builder, self.selfLocalization)
        ModelTogglesAddUsePosition(builder, self.usePosition)
        ModelTogglesAddEnforceConstraints(builder, self.enforceConstraints)
        ModelTogglesAddCorrectConstraints(builder, self.correctConstraints)
        modelToggles = ModelTogglesEnd(builder)
        return modelToggles
