# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hardware_info

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.datatypes.hardware_info.HardwareAddress import HardwareAddressT
from solarxr_protocol.datatypes.Ipv4Address import Ipv4AddressT
from solarxr_protocol.datatypes.hardware_info.HardwareAddress import HardwareAddress
from solarxr_protocol.datatypes.Ipv4Address import Ipv4Address

# Mostly static info about the device's hardware/firmware.
class HardwareInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HardwareInfo()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHardwareInfo(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HardwareInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HardwareInfo
    def McuId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # A human-friendly name to display as the name of the device.
    # HardwareInfo
    def DisplayName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # A human-friendly string for the device model.
    # HardwareInfo
    def Model(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # A human-friendly string for the manufacturer of the device.
    # HardwareInfo
    def Manufacturer(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # The hardware version of the device. For example, pcb version.
    # HardwareInfo
    def HardwareRevision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # The version of the slimevr firmware that the device is running.
    # HardwareInfo
    def FirmwareVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HardwareInfo
    def HardwareAddress(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            obj = HardwareAddress()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # HardwareInfo
    def IpAddress(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = o + self._tab.Pos
            obj = Ipv4Address()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # A board type string that can be used to name a board. if possible you should use official board type
    # HardwareInfo
    def BoardType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # An enum listing all the board types supported by the firmware
    # HardwareInfo
    def OfficialBoardType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # A unique identifier for the device. Depending on the type of device it can be the MAC address,
    # the IP address, or some other unique identifier like what USB device it is.
    # HardwareInfo
    def HardwareIdentifier(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # The version of the protocol it's using to communicate with server
    # HardwareInfo
    def NetworkProtocolVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return None

    # The build date of the slimevr firmware that the device is running. YYYY-MM-DD
    # HardwareInfo
    def FirmwareDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def HardwareInfoStart(builder):
    builder.StartObject(13)

def Start(builder):
    HardwareInfoStart(builder)

def HardwareInfoAddMcuId(builder, mcuId):
    builder.PrependUint16Slot(0, mcuId, 0)

def AddMcuId(builder, mcuId):
    HardwareInfoAddMcuId(builder, mcuId)

def HardwareInfoAddDisplayName(builder, displayName):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(displayName), 0)

def AddDisplayName(builder, displayName):
    HardwareInfoAddDisplayName(builder, displayName)

def HardwareInfoAddModel(builder, model):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(model), 0)

def AddModel(builder, model):
    HardwareInfoAddModel(builder, model)

def HardwareInfoAddManufacturer(builder, manufacturer):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(manufacturer), 0)

def AddManufacturer(builder, manufacturer):
    HardwareInfoAddManufacturer(builder, manufacturer)

def HardwareInfoAddHardwareRevision(builder, hardwareRevision):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(hardwareRevision), 0)

def AddHardwareRevision(builder, hardwareRevision):
    HardwareInfoAddHardwareRevision(builder, hardwareRevision)

def HardwareInfoAddFirmwareVersion(builder, firmwareVersion):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(firmwareVersion), 0)

def AddFirmwareVersion(builder, firmwareVersion):
    HardwareInfoAddFirmwareVersion(builder, firmwareVersion)

def HardwareInfoAddHardwareAddress(builder, hardwareAddress):
    builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(hardwareAddress), 0)

def AddHardwareAddress(builder, hardwareAddress):
    HardwareInfoAddHardwareAddress(builder, hardwareAddress)

def HardwareInfoAddIpAddress(builder, ipAddress):
    builder.PrependStructSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(ipAddress), 0)

def AddIpAddress(builder, ipAddress):
    HardwareInfoAddIpAddress(builder, ipAddress)

def HardwareInfoAddBoardType(builder, boardType):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(boardType), 0)

def AddBoardType(builder, boardType):
    HardwareInfoAddBoardType(builder, boardType)

def HardwareInfoAddOfficialBoardType(builder, officialBoardType):
    builder.PrependUint16Slot(9, officialBoardType, 0)

def AddOfficialBoardType(builder, officialBoardType):
    HardwareInfoAddOfficialBoardType(builder, officialBoardType)

def HardwareInfoAddHardwareIdentifier(builder, hardwareIdentifier):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(hardwareIdentifier), 0)

def AddHardwareIdentifier(builder, hardwareIdentifier):
    HardwareInfoAddHardwareIdentifier(builder, hardwareIdentifier)

def HardwareInfoAddNetworkProtocolVersion(builder, networkProtocolVersion):
    builder.PrependUint16Slot(11, networkProtocolVersion, None)

def AddNetworkProtocolVersion(builder, networkProtocolVersion):
    HardwareInfoAddNetworkProtocolVersion(builder, networkProtocolVersion)

def HardwareInfoAddFirmwareDate(builder, firmwareDate):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(firmwareDate), 0)

def AddFirmwareDate(builder, firmwareDate):
    HardwareInfoAddFirmwareDate(builder, firmwareDate)

def HardwareInfoEnd(builder):
    return builder.EndObject()

def End(builder):
    return HardwareInfoEnd(builder)

try:
    from typing import Optional
except:
    pass

class HardwareInfoT(object):

    # HardwareInfoT
    def __init__(
        self,
        mcuId = 0,
        displayName = None,
        model = None,
        manufacturer = None,
        hardwareRevision = None,
        firmwareVersion = None,
        hardwareAddress = None,
        ipAddress = None,
        boardType = None,
        officialBoardType = 0,
        hardwareIdentifier = None,
        networkProtocolVersion = None,
        firmwareDate = None,
    ):
        self.mcuId = mcuId  # type: int
        self.displayName = displayName  # type: Optional[str]
        self.model = model  # type: Optional[str]
        self.manufacturer = manufacturer  # type: Optional[str]
        self.hardwareRevision = hardwareRevision  # type: Optional[str]
        self.firmwareVersion = firmwareVersion  # type: Optional[str]
        self.hardwareAddress = hardwareAddress  # type: Optional[HardwareAddressT]
        self.ipAddress = ipAddress  # type: Optional[Ipv4AddressT]
        self.boardType = boardType  # type: Optional[str]
        self.officialBoardType = officialBoardType  # type: int
        self.hardwareIdentifier = hardwareIdentifier  # type: Optional[str]
        self.networkProtocolVersion = networkProtocolVersion  # type: Optional[int]
        self.firmwareDate = firmwareDate  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        hardwareInfo = HardwareInfo()
        hardwareInfo.Init(buf, pos)
        return cls.InitFromObj(hardwareInfo)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, hardwareInfo):
        x = HardwareInfoT()
        x._UnPack(hardwareInfo)
        return x

    # HardwareInfoT
    def _UnPack(self, hardwareInfo):
        if hardwareInfo is None:
            return
        self.mcuId = hardwareInfo.McuId()
        self.displayName = hardwareInfo.DisplayName()
        self.model = hardwareInfo.Model()
        self.manufacturer = hardwareInfo.Manufacturer()
        self.hardwareRevision = hardwareInfo.HardwareRevision()
        self.firmwareVersion = hardwareInfo.FirmwareVersion()
        if hardwareInfo.HardwareAddress() is not None:
            self.hardwareAddress = HardwareAddressT.InitFromObj(hardwareInfo.HardwareAddress())
        if hardwareInfo.IpAddress() is not None:
            self.ipAddress = Ipv4AddressT.InitFromObj(hardwareInfo.IpAddress())
        self.boardType = hardwareInfo.BoardType()
        self.officialBoardType = hardwareInfo.OfficialBoardType()
        self.hardwareIdentifier = hardwareInfo.HardwareIdentifier()
        self.networkProtocolVersion = hardwareInfo.NetworkProtocolVersion()
        self.firmwareDate = hardwareInfo.FirmwareDate()

    # HardwareInfoT
    def Pack(self, builder):
        if self.displayName is not None:
            displayName = builder.CreateString(self.displayName)
        if self.model is not None:
            model = builder.CreateString(self.model)
        if self.manufacturer is not None:
            manufacturer = builder.CreateString(self.manufacturer)
        if self.hardwareRevision is not None:
            hardwareRevision = builder.CreateString(self.hardwareRevision)
        if self.firmwareVersion is not None:
            firmwareVersion = builder.CreateString(self.firmwareVersion)
        if self.boardType is not None:
            boardType = builder.CreateString(self.boardType)
        if self.hardwareIdentifier is not None:
            hardwareIdentifier = builder.CreateString(self.hardwareIdentifier)
        if self.firmwareDate is not None:
            firmwareDate = builder.CreateString(self.firmwareDate)
        HardwareInfoStart(builder)
        HardwareInfoAddMcuId(builder, self.mcuId)
        if self.displayName is not None:
            HardwareInfoAddDisplayName(builder, displayName)
        if self.model is not None:
            HardwareInfoAddModel(builder, model)
        if self.manufacturer is not None:
            HardwareInfoAddManufacturer(builder, manufacturer)
        if self.hardwareRevision is not None:
            HardwareInfoAddHardwareRevision(builder, hardwareRevision)
        if self.firmwareVersion is not None:
            HardwareInfoAddFirmwareVersion(builder, firmwareVersion)
        if self.hardwareAddress is not None:
            hardwareAddress = self.hardwareAddress.Pack(builder)
            HardwareInfoAddHardwareAddress(builder, hardwareAddress)
        if self.ipAddress is not None:
            ipAddress = self.ipAddress.Pack(builder)
            HardwareInfoAddIpAddress(builder, ipAddress)
        if self.boardType is not None:
            HardwareInfoAddBoardType(builder, boardType)
        HardwareInfoAddOfficialBoardType(builder, self.officialBoardType)
        if self.hardwareIdentifier is not None:
            HardwareInfoAddHardwareIdentifier(builder, hardwareIdentifier)
        HardwareInfoAddNetworkProtocolVersion(builder, self.networkProtocolVersion)
        if self.firmwareDate is not None:
            HardwareInfoAddFirmwareDate(builder, firmwareDate)
        hardwareInfo = HardwareInfoEnd(builder)
        return hardwareInfo
