# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pub_sub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.pub_sub.PubSubUnion import PubSubUnionCreator

class PubSubHeader(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PubSubHeader()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPubSubHeader(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PubSubHeader
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PubSubHeader
    def UType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PubSubHeader
    def U(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def PubSubHeaderStart(builder):
    builder.StartObject(2)

def Start(builder):
    PubSubHeaderStart(builder)

def PubSubHeaderAddUType(builder, uType):
    builder.PrependUint8Slot(0, uType, 0)

def AddUType(builder, uType):
    PubSubHeaderAddUType(builder, uType)

def PubSubHeaderAddU(builder, u):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(u), 0)

def AddU(builder, u):
    PubSubHeaderAddU(builder, u)

def PubSubHeaderEnd(builder):
    return builder.EndObject()

def End(builder):
    return PubSubHeaderEnd(builder)

try:
    from typing import Union
except:
    pass

class PubSubHeaderT(object):

    # PubSubHeaderT
    def __init__(
        self,
        uType = 0,
        u = None,
    ):
        self.uType = uType  # type: int
        self.u = u  # type: Union[None, 'MessageT', 'SubscriptionRequestT', 'TopicHandleRequestT', 'TopicMappingT']

    @classmethod
    def InitFromBuf(cls, buf, pos):
        pubSubHeader = PubSubHeader()
        pubSubHeader.Init(buf, pos)
        return cls.InitFromObj(pubSubHeader)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, pubSubHeader):
        x = PubSubHeaderT()
        x._UnPack(pubSubHeader)
        return x

    # PubSubHeaderT
    def _UnPack(self, pubSubHeader):
        if pubSubHeader is None:
            return
        self.uType = pubSubHeader.UType()
        self.u = PubSubUnionCreator(self.uType, pubSubHeader.U())

    # PubSubHeaderT
    def Pack(self, builder):
        if self.u is not None:
            u = self.u.Pack(builder)
        PubSubHeaderStart(builder)
        PubSubHeaderAddUType(builder, self.uType)
        if self.u is not None:
            PubSubHeaderAddU(builder, u)
        pubSubHeader = PubSubHeaderEnd(builder)
        return pubSubHeader
