# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pub_sub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.pub_sub.TopicId import TopicIdT
from solarxr_protocol.pub_sub.TopicId import TopicId

# Request to get the `FeatureHandle` from a `FeatureId`. This is useful for reducing
# bandwidth, since `FeatureId` can be large.
class TopicHandleRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TopicHandleRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTopicHandleRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TopicHandleRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TopicHandleRequest
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = TopicId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def TopicHandleRequestStart(builder):
    builder.StartObject(1)

def Start(builder):
    TopicHandleRequestStart(builder)

def TopicHandleRequestAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    TopicHandleRequestAddId(builder, id)

def TopicHandleRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return TopicHandleRequestEnd(builder)

try:
    from typing import Optional
except:
    pass

class TopicHandleRequestT(object):

    # TopicHandleRequestT
    def __init__(
        self,
        id = None,
    ):
        self.id = id  # type: Optional[TopicIdT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        topicHandleRequest = TopicHandleRequest()
        topicHandleRequest.Init(buf, pos)
        return cls.InitFromObj(topicHandleRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, topicHandleRequest):
        x = TopicHandleRequestT()
        x._UnPack(topicHandleRequest)
        return x

    # TopicHandleRequestT
    def _UnPack(self, topicHandleRequest):
        if topicHandleRequest is None:
            return
        if topicHandleRequest.Id() is not None:
            self.id = TopicIdT.InitFromObj(topicHandleRequest.Id())

    # TopicHandleRequestT
    def Pack(self, builder):
        if self.id is not None:
            id = self.id.Pack(builder)
        TopicHandleRequestStart(builder)
        if self.id is not None:
            TopicHandleRequestAddId(builder, id)
        topicHandleRequest = TopicHandleRequestEnd(builder)
        return topicHandleRequest
