# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pub_sub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.pub_sub.TopicHandle import TopicHandleT
from solarxr_protocol.pub_sub.TopicId import TopicIdT
from solarxr_protocol.pub_sub.TopicHandle import TopicHandle
from solarxr_protocol.pub_sub.TopicId import TopicId

# Response for `TopicHandleRequest` or `SubscriptionRequest`.
class TopicMapping(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TopicMapping()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTopicMapping(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TopicMapping
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TopicMapping
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = TopicId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TopicMapping
    def Handle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = TopicHandle()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def TopicMappingStart(builder):
    builder.StartObject(2)

def Start(builder):
    TopicMappingStart(builder)

def TopicMappingAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    TopicMappingAddId(builder, id)

def TopicMappingAddHandle(builder, handle):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(handle), 0)

def AddHandle(builder, handle):
    TopicMappingAddHandle(builder, handle)

def TopicMappingEnd(builder):
    return builder.EndObject()

def End(builder):
    return TopicMappingEnd(builder)

try:
    from typing import Optional
except:
    pass

class TopicMappingT(object):

    # TopicMappingT
    def __init__(
        self,
        id = None,
        handle = None,
    ):
        self.id = id  # type: Optional[TopicIdT]
        self.handle = handle  # type: Optional[TopicHandleT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        topicMapping = TopicMapping()
        topicMapping.Init(buf, pos)
        return cls.InitFromObj(topicMapping)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, topicMapping):
        x = TopicMappingT()
        x._UnPack(topicMapping)
        return x

    # TopicMappingT
    def _UnPack(self, topicMapping):
        if topicMapping is None:
            return
        if topicMapping.Id() is not None:
            self.id = TopicIdT.InitFromObj(topicMapping.Id())
        if topicMapping.Handle() is not None:
            self.handle = TopicHandleT.InitFromObj(topicMapping.Handle())

    # TopicMappingT
    def Pack(self, builder):
        if self.id is not None:
            id = self.id.Pack(builder)
        if self.handle is not None:
            handle = self.handle.Pack(builder)
        TopicMappingStart(builder)
        if self.id is not None:
            TopicMappingAddId(builder, id)
        if self.handle is not None:
            TopicMappingAddHandle(builder, handle)
        topicMapping = TopicMappingEnd(builder)
        return topicMapping
