from solarxr_protocol.pub_sub.TopicHandle import TopicHandleT
from solarxr_protocol.pub_sub.TopicId import TopicIdT
# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pub_sub

class Topic(object):
    NONE = 0
    TopicHandle = 1
    TopicId = 2

def TopicCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == Topic.TopicHandle:
        return TopicHandleT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Topic.TopicId:
        return TopicIdT.InitFromBuf(table.Bytes, table.Pos)
    return None
