# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pub_sub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A `TopicId` identifies an application-specific category of data. Because it
# is application-specific, it is up to the application within the specified
# organization to define its semantics/meaning.
#
# For example, "bob" may have an "overlay" app with a "settings" topic for controlling
# the overlay visibility and other settings, as well as a "video feed" topic for
# allowing other applications to display video data in a wrist mounted window in VR.
class TopicId(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TopicId()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTopicId(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TopicId
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The organization/developer that defines the meaning of this feature. Avoids name
    # clashes. Should be something unique - same idea as java package identifier.
    # TopicId
    def Organization(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # The name of the application/device. Should be unique within the organization.
    # TopicId
    def AppName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # The name of the topic. Should be unique within the application.
    # TopicId
    def Topic(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def TopicIdStart(builder):
    builder.StartObject(3)

def Start(builder):
    TopicIdStart(builder)

def TopicIdAddOrganization(builder, organization):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(organization), 0)

def AddOrganization(builder, organization):
    TopicIdAddOrganization(builder, organization)

def TopicIdAddAppName(builder, appName):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(appName), 0)

def AddAppName(builder, appName):
    TopicIdAddAppName(builder, appName)

def TopicIdAddTopic(builder, topic):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(topic), 0)

def AddTopic(builder, topic):
    TopicIdAddTopic(builder, topic)

def TopicIdEnd(builder):
    return builder.EndObject()

def End(builder):
    return TopicIdEnd(builder)


class TopicIdT(object):

    # TopicIdT
    def __init__(
        self,
        organization = None,
        appName = None,
        topic = None,
    ):
        self.organization = organization  # type: Optional[str]
        self.appName = appName  # type: Optional[str]
        self.topic = topic  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        topicId = TopicId()
        topicId.Init(buf, pos)
        return cls.InitFromObj(topicId)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, topicId):
        x = TopicIdT()
        x._UnPack(topicId)
        return x

    # TopicIdT
    def _UnPack(self, topicId):
        if topicId is None:
            return
        self.organization = topicId.Organization()
        self.appName = topicId.AppName()
        self.topic = topicId.Topic()

    # TopicIdT
    def Pack(self, builder):
        if self.organization is not None:
            organization = builder.CreateString(self.organization)
        if self.appName is not None:
            appName = builder.CreateString(self.appName)
        if self.topic is not None:
            topic = builder.CreateString(self.topic)
        TopicIdStart(builder)
        if self.organization is not None:
            TopicIdAddOrganization(builder, organization)
        if self.appName is not None:
            TopicIdAddAppName(builder, appName)
        if self.topic is not None:
            TopicIdAddTopic(builder, topic)
        topicId = TopicIdEnd(builder)
        return topicId
