# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pub_sub

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A handle for the topic, allows referencing a topic without sending a huge
# `TopicId`.
class TopicHandle(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TopicHandle()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTopicHandle(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TopicHandle
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TopicHandle
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def TopicHandleStart(builder):
    builder.StartObject(1)

def Start(builder):
    TopicHandleStart(builder)

def TopicHandleAddId(builder, id):
    builder.PrependUint16Slot(0, id, 0)

def AddId(builder, id):
    TopicHandleAddId(builder, id)

def TopicHandleEnd(builder):
    return builder.EndObject()

def End(builder):
    return TopicHandleEnd(builder)


class TopicHandleT(object):

    # TopicHandleT
    def __init__(
        self,
        id = 0,
    ):
        self.id = id  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        topicHandle = TopicHandle()
        topicHandle.Init(buf, pos)
        return cls.InitFromObj(topicHandle)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, topicHandle):
        x = TopicHandleT()
        x._UnPack(topicHandle)
        return x

    # TopicHandleT
    def _UnPack(self, topicHandle):
        if topicHandle is None:
            return
        self.id = topicHandle.Id()

    # TopicHandleT
    def Pack(self, builder):
        TopicHandleStart(builder)
        TopicHandleAddId(builder, self.id)
        topicHandle = TopicHandleEnd(builder)
        return topicHandle
