# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# https://github.com/SlimeVR/SlimeVR-Server/blob/v0.8.3/server/src/main/java/dev/slimevr/config/AutoBoneConfig.kt
class AutoBoneSettings(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AutoBoneSettings()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAutoBoneSettings(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AutoBoneSettings
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AutoBoneSettings
    def CursorIncrement(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return None

    # AutoBoneSettings
    def MinDataDistance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return None

    # AutoBoneSettings
    def MaxDataDistance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return None

    # AutoBoneSettings
    def NumEpochs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return None

    # AutoBoneSettings
    def PrintEveryNumEpochs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return None

    # AutoBoneSettings
    def InitialAdjustRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return None

    # AutoBoneSettings
    def AdjustRateDecay(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return None

    # AutoBoneSettings
    def SlideErrorFactor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return None

    # AutoBoneSettings
    def OffsetSlideErrorFactor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return None

    # AutoBoneSettings
    def FootHeightOffsetErrorFactor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return None

    # AutoBoneSettings
    def BodyProportionErrorFactor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return None

    # AutoBoneSettings
    def HeightErrorFactor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return None

    # AutoBoneSettings
    def PositionErrorFactor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return None

    # AutoBoneSettings
    def PositionOffsetErrorFactor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return None

    # AutoBoneSettings
    def CalcInitError(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return None

    # AutoBoneSettings
    def RandomizeFrameOrder(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return None

    # AutoBoneSettings
    def ScaleEachStep(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return None

    # AutoBoneSettings
    def SampleCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return None

    # AutoBoneSettings
    def SampleRateMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return None

    # AutoBoneSettings
    def SaveRecordings(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return None

    # AutoBoneSettings
    def UseSkeletonHeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return None

    # AutoBoneSettings
    def RandSeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return None

def AutoBoneSettingsStart(builder):
    builder.StartObject(22)

def Start(builder):
    AutoBoneSettingsStart(builder)

def AutoBoneSettingsAddCursorIncrement(builder, cursorIncrement):
    builder.PrependInt32Slot(0, cursorIncrement, None)

def AddCursorIncrement(builder, cursorIncrement):
    AutoBoneSettingsAddCursorIncrement(builder, cursorIncrement)

def AutoBoneSettingsAddMinDataDistance(builder, minDataDistance):
    builder.PrependInt32Slot(1, minDataDistance, None)

def AddMinDataDistance(builder, minDataDistance):
    AutoBoneSettingsAddMinDataDistance(builder, minDataDistance)

def AutoBoneSettingsAddMaxDataDistance(builder, maxDataDistance):
    builder.PrependInt32Slot(2, maxDataDistance, None)

def AddMaxDataDistance(builder, maxDataDistance):
    AutoBoneSettingsAddMaxDataDistance(builder, maxDataDistance)

def AutoBoneSettingsAddNumEpochs(builder, numEpochs):
    builder.PrependInt32Slot(3, numEpochs, None)

def AddNumEpochs(builder, numEpochs):
    AutoBoneSettingsAddNumEpochs(builder, numEpochs)

def AutoBoneSettingsAddPrintEveryNumEpochs(builder, printEveryNumEpochs):
    builder.PrependInt32Slot(4, printEveryNumEpochs, None)

def AddPrintEveryNumEpochs(builder, printEveryNumEpochs):
    AutoBoneSettingsAddPrintEveryNumEpochs(builder, printEveryNumEpochs)

def AutoBoneSettingsAddInitialAdjustRate(builder, initialAdjustRate):
    builder.PrependFloat32Slot(5, initialAdjustRate, None)

def AddInitialAdjustRate(builder, initialAdjustRate):
    AutoBoneSettingsAddInitialAdjustRate(builder, initialAdjustRate)

def AutoBoneSettingsAddAdjustRateDecay(builder, adjustRateDecay):
    builder.PrependFloat32Slot(6, adjustRateDecay, None)

def AddAdjustRateDecay(builder, adjustRateDecay):
    AutoBoneSettingsAddAdjustRateDecay(builder, adjustRateDecay)

def AutoBoneSettingsAddSlideErrorFactor(builder, slideErrorFactor):
    builder.PrependFloat32Slot(7, slideErrorFactor, None)

def AddSlideErrorFactor(builder, slideErrorFactor):
    AutoBoneSettingsAddSlideErrorFactor(builder, slideErrorFactor)

def AutoBoneSettingsAddOffsetSlideErrorFactor(builder, offsetSlideErrorFactor):
    builder.PrependFloat32Slot(8, offsetSlideErrorFactor, None)

def AddOffsetSlideErrorFactor(builder, offsetSlideErrorFactor):
    AutoBoneSettingsAddOffsetSlideErrorFactor(builder, offsetSlideErrorFactor)

def AutoBoneSettingsAddFootHeightOffsetErrorFactor(builder, footHeightOffsetErrorFactor):
    builder.PrependFloat32Slot(9, footHeightOffsetErrorFactor, None)

def AddFootHeightOffsetErrorFactor(builder, footHeightOffsetErrorFactor):
    AutoBoneSettingsAddFootHeightOffsetErrorFactor(builder, footHeightOffsetErrorFactor)

def AutoBoneSettingsAddBodyProportionErrorFactor(builder, bodyProportionErrorFactor):
    builder.PrependFloat32Slot(10, bodyProportionErrorFactor, None)

def AddBodyProportionErrorFactor(builder, bodyProportionErrorFactor):
    AutoBoneSettingsAddBodyProportionErrorFactor(builder, bodyProportionErrorFactor)

def AutoBoneSettingsAddHeightErrorFactor(builder, heightErrorFactor):
    builder.PrependFloat32Slot(11, heightErrorFactor, None)

def AddHeightErrorFactor(builder, heightErrorFactor):
    AutoBoneSettingsAddHeightErrorFactor(builder, heightErrorFactor)

def AutoBoneSettingsAddPositionErrorFactor(builder, positionErrorFactor):
    builder.PrependFloat32Slot(12, positionErrorFactor, None)

def AddPositionErrorFactor(builder, positionErrorFactor):
    AutoBoneSettingsAddPositionErrorFactor(builder, positionErrorFactor)

def AutoBoneSettingsAddPositionOffsetErrorFactor(builder, positionOffsetErrorFactor):
    builder.PrependFloat32Slot(13, positionOffsetErrorFactor, None)

def AddPositionOffsetErrorFactor(builder, positionOffsetErrorFactor):
    AutoBoneSettingsAddPositionOffsetErrorFactor(builder, positionOffsetErrorFactor)

def AutoBoneSettingsAddCalcInitError(builder, calcInitError):
    builder.PrependBoolSlot(14, calcInitError, None)

def AddCalcInitError(builder, calcInitError):
    AutoBoneSettingsAddCalcInitError(builder, calcInitError)

def AutoBoneSettingsAddRandomizeFrameOrder(builder, randomizeFrameOrder):
    builder.PrependBoolSlot(15, randomizeFrameOrder, None)

def AddRandomizeFrameOrder(builder, randomizeFrameOrder):
    AutoBoneSettingsAddRandomizeFrameOrder(builder, randomizeFrameOrder)

def AutoBoneSettingsAddScaleEachStep(builder, scaleEachStep):
    builder.PrependBoolSlot(16, scaleEachStep, None)

def AddScaleEachStep(builder, scaleEachStep):
    AutoBoneSettingsAddScaleEachStep(builder, scaleEachStep)

def AutoBoneSettingsAddSampleCount(builder, sampleCount):
    builder.PrependInt32Slot(17, sampleCount, None)

def AddSampleCount(builder, sampleCount):
    AutoBoneSettingsAddSampleCount(builder, sampleCount)

def AutoBoneSettingsAddSampleRateMs(builder, sampleRateMs):
    builder.PrependInt64Slot(18, sampleRateMs, None)

def AddSampleRateMs(builder, sampleRateMs):
    AutoBoneSettingsAddSampleRateMs(builder, sampleRateMs)

def AutoBoneSettingsAddSaveRecordings(builder, saveRecordings):
    builder.PrependBoolSlot(19, saveRecordings, None)

def AddSaveRecordings(builder, saveRecordings):
    AutoBoneSettingsAddSaveRecordings(builder, saveRecordings)

def AutoBoneSettingsAddUseSkeletonHeight(builder, useSkeletonHeight):
    builder.PrependBoolSlot(20, useSkeletonHeight, None)

def AddUseSkeletonHeight(builder, useSkeletonHeight):
    AutoBoneSettingsAddUseSkeletonHeight(builder, useSkeletonHeight)

def AutoBoneSettingsAddRandSeed(builder, randSeed):
    builder.PrependInt64Slot(21, randSeed, None)

def AddRandSeed(builder, randSeed):
    AutoBoneSettingsAddRandSeed(builder, randSeed)

def AutoBoneSettingsEnd(builder):
    return builder.EndObject()

def End(builder):
    return AutoBoneSettingsEnd(builder)

try:
    from typing import Optional
except:
    pass

class AutoBoneSettingsT(object):

    # AutoBoneSettingsT
    def __init__(
        self,
        cursorIncrement = None,
        minDataDistance = None,
        maxDataDistance = None,
        numEpochs = None,
        printEveryNumEpochs = None,
        initialAdjustRate = None,
        adjustRateDecay = None,
        slideErrorFactor = None,
        offsetSlideErrorFactor = None,
        footHeightOffsetErrorFactor = None,
        bodyProportionErrorFactor = None,
        heightErrorFactor = None,
        positionErrorFactor = None,
        positionOffsetErrorFactor = None,
        calcInitError = None,
        randomizeFrameOrder = None,
        scaleEachStep = None,
        sampleCount = None,
        sampleRateMs = None,
        saveRecordings = None,
        useSkeletonHeight = None,
        randSeed = None,
    ):
        self.cursorIncrement = cursorIncrement  # type: Optional[int]
        self.minDataDistance = minDataDistance  # type: Optional[int]
        self.maxDataDistance = maxDataDistance  # type: Optional[int]
        self.numEpochs = numEpochs  # type: Optional[int]
        self.printEveryNumEpochs = printEveryNumEpochs  # type: Optional[int]
        self.initialAdjustRate = initialAdjustRate  # type: Optional[float]
        self.adjustRateDecay = adjustRateDecay  # type: Optional[float]
        self.slideErrorFactor = slideErrorFactor  # type: Optional[float]
        self.offsetSlideErrorFactor = offsetSlideErrorFactor  # type: Optional[float]
        self.footHeightOffsetErrorFactor = footHeightOffsetErrorFactor  # type: Optional[float]
        self.bodyProportionErrorFactor = bodyProportionErrorFactor  # type: Optional[float]
        self.heightErrorFactor = heightErrorFactor  # type: Optional[float]
        self.positionErrorFactor = positionErrorFactor  # type: Optional[float]
        self.positionOffsetErrorFactor = positionOffsetErrorFactor  # type: Optional[float]
        self.calcInitError = calcInitError  # type: Optional[bool]
        self.randomizeFrameOrder = randomizeFrameOrder  # type: Optional[bool]
        self.scaleEachStep = scaleEachStep  # type: Optional[bool]
        self.sampleCount = sampleCount  # type: Optional[int]
        self.sampleRateMs = sampleRateMs  # type: Optional[int]
        self.saveRecordings = saveRecordings  # type: Optional[bool]
        self.useSkeletonHeight = useSkeletonHeight  # type: Optional[bool]
        self.randSeed = randSeed  # type: Optional[int]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        autoBoneSettings = AutoBoneSettings()
        autoBoneSettings.Init(buf, pos)
        return cls.InitFromObj(autoBoneSettings)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, autoBoneSettings):
        x = AutoBoneSettingsT()
        x._UnPack(autoBoneSettings)
        return x

    # AutoBoneSettingsT
    def _UnPack(self, autoBoneSettings):
        if autoBoneSettings is None:
            return
        self.cursorIncrement = autoBoneSettings.CursorIncrement()
        self.minDataDistance = autoBoneSettings.MinDataDistance()
        self.maxDataDistance = autoBoneSettings.MaxDataDistance()
        self.numEpochs = autoBoneSettings.NumEpochs()
        self.printEveryNumEpochs = autoBoneSettings.PrintEveryNumEpochs()
        self.initialAdjustRate = autoBoneSettings.InitialAdjustRate()
        self.adjustRateDecay = autoBoneSettings.AdjustRateDecay()
        self.slideErrorFactor = autoBoneSettings.SlideErrorFactor()
        self.offsetSlideErrorFactor = autoBoneSettings.OffsetSlideErrorFactor()
        self.footHeightOffsetErrorFactor = autoBoneSettings.FootHeightOffsetErrorFactor()
        self.bodyProportionErrorFactor = autoBoneSettings.BodyProportionErrorFactor()
        self.heightErrorFactor = autoBoneSettings.HeightErrorFactor()
        self.positionErrorFactor = autoBoneSettings.PositionErrorFactor()
        self.positionOffsetErrorFactor = autoBoneSettings.PositionOffsetErrorFactor()
        self.calcInitError = autoBoneSettings.CalcInitError()
        self.randomizeFrameOrder = autoBoneSettings.RandomizeFrameOrder()
        self.scaleEachStep = autoBoneSettings.ScaleEachStep()
        self.sampleCount = autoBoneSettings.SampleCount()
        self.sampleRateMs = autoBoneSettings.SampleRateMs()
        self.saveRecordings = autoBoneSettings.SaveRecordings()
        self.useSkeletonHeight = autoBoneSettings.UseSkeletonHeight()
        self.randSeed = autoBoneSettings.RandSeed()

    # AutoBoneSettingsT
    def Pack(self, builder):
        AutoBoneSettingsStart(builder)
        AutoBoneSettingsAddCursorIncrement(builder, self.cursorIncrement)
        AutoBoneSettingsAddMinDataDistance(builder, self.minDataDistance)
        AutoBoneSettingsAddMaxDataDistance(builder, self.maxDataDistance)
        AutoBoneSettingsAddNumEpochs(builder, self.numEpochs)
        AutoBoneSettingsAddPrintEveryNumEpochs(builder, self.printEveryNumEpochs)
        AutoBoneSettingsAddInitialAdjustRate(builder, self.initialAdjustRate)
        AutoBoneSettingsAddAdjustRateDecay(builder, self.adjustRateDecay)
        AutoBoneSettingsAddSlideErrorFactor(builder, self.slideErrorFactor)
        AutoBoneSettingsAddOffsetSlideErrorFactor(builder, self.offsetSlideErrorFactor)
        AutoBoneSettingsAddFootHeightOffsetErrorFactor(builder, self.footHeightOffsetErrorFactor)
        AutoBoneSettingsAddBodyProportionErrorFactor(builder, self.bodyProportionErrorFactor)
        AutoBoneSettingsAddHeightErrorFactor(builder, self.heightErrorFactor)
        AutoBoneSettingsAddPositionErrorFactor(builder, self.positionErrorFactor)
        AutoBoneSettingsAddPositionOffsetErrorFactor(builder, self.positionOffsetErrorFactor)
        AutoBoneSettingsAddCalcInitError(builder, self.calcInitError)
        AutoBoneSettingsAddRandomizeFrameOrder(builder, self.randomizeFrameOrder)
        AutoBoneSettingsAddScaleEachStep(builder, self.scaleEachStep)
        AutoBoneSettingsAddSampleCount(builder, self.sampleCount)
        AutoBoneSettingsAddSampleRateMs(builder, self.sampleRateMs)
        AutoBoneSettingsAddSaveRecordings(builder, self.saveRecordings)
        AutoBoneSettingsAddUseSkeletonHeight(builder, self.useSkeletonHeight)
        AutoBoneSettingsAddRandSeed(builder, self.randSeed)
        autoBoneSettings = AutoBoneSettingsEnd(builder)
        return autoBoneSettings
