# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.rpc.SkeletonPart import SkeletonPartT
from solarxr_protocol.rpc.SkeletonPart import SkeletonPart

class AutoBoneEpochResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AutoBoneEpochResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAutoBoneEpochResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AutoBoneEpochResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AutoBoneEpochResponse
    def CurrentEpoch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AutoBoneEpochResponse
    def TotalEpochs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # The current error value. This can be any positive number, where lower is better.
    # AutoBoneEpochResponse
    def EpochError(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # A list of the current estimated body proportions.
    # AutoBoneEpochResponse
    def AdjustedSkeletonParts(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = SkeletonPart()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AutoBoneEpochResponse
    def AdjustedSkeletonPartsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AutoBoneEpochResponse
    def AdjustedSkeletonPartsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def AutoBoneEpochResponseStart(builder):
    builder.StartObject(4)

def Start(builder):
    AutoBoneEpochResponseStart(builder)

def AutoBoneEpochResponseAddCurrentEpoch(builder, currentEpoch):
    builder.PrependUint32Slot(0, currentEpoch, 0)

def AddCurrentEpoch(builder, currentEpoch):
    AutoBoneEpochResponseAddCurrentEpoch(builder, currentEpoch)

def AutoBoneEpochResponseAddTotalEpochs(builder, totalEpochs):
    builder.PrependUint32Slot(1, totalEpochs, 0)

def AddTotalEpochs(builder, totalEpochs):
    AutoBoneEpochResponseAddTotalEpochs(builder, totalEpochs)

def AutoBoneEpochResponseAddEpochError(builder, epochError):
    builder.PrependFloat32Slot(2, epochError, 0.0)

def AddEpochError(builder, epochError):
    AutoBoneEpochResponseAddEpochError(builder, epochError)

def AutoBoneEpochResponseAddAdjustedSkeletonParts(builder, adjustedSkeletonParts):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(adjustedSkeletonParts), 0)

def AddAdjustedSkeletonParts(builder, adjustedSkeletonParts):
    AutoBoneEpochResponseAddAdjustedSkeletonParts(builder, adjustedSkeletonParts)

def AutoBoneEpochResponseStartAdjustedSkeletonPartsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAdjustedSkeletonPartsVector(builder, numElems):
    return AutoBoneEpochResponseStartAdjustedSkeletonPartsVector(builder, numElems)

def AutoBoneEpochResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return AutoBoneEpochResponseEnd(builder)

try:
    from typing import List
except:
    pass

class AutoBoneEpochResponseT(object):

    # AutoBoneEpochResponseT
    def __init__(
        self,
        currentEpoch = 0,
        totalEpochs = 0,
        epochError = 0.0,
        adjustedSkeletonParts = None,
    ):
        self.currentEpoch = currentEpoch  # type: int
        self.totalEpochs = totalEpochs  # type: int
        self.epochError = epochError  # type: float
        self.adjustedSkeletonParts = adjustedSkeletonParts  # type: Optional[List[SkeletonPartT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        autoBoneEpochResponse = AutoBoneEpochResponse()
        autoBoneEpochResponse.Init(buf, pos)
        return cls.InitFromObj(autoBoneEpochResponse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, autoBoneEpochResponse):
        x = AutoBoneEpochResponseT()
        x._UnPack(autoBoneEpochResponse)
        return x

    # AutoBoneEpochResponseT
    def _UnPack(self, autoBoneEpochResponse):
        if autoBoneEpochResponse is None:
            return
        self.currentEpoch = autoBoneEpochResponse.CurrentEpoch()
        self.totalEpochs = autoBoneEpochResponse.TotalEpochs()
        self.epochError = autoBoneEpochResponse.EpochError()
        if not autoBoneEpochResponse.AdjustedSkeletonPartsIsNone():
            self.adjustedSkeletonParts = []
            for i in range(autoBoneEpochResponse.AdjustedSkeletonPartsLength()):
                if autoBoneEpochResponse.AdjustedSkeletonParts(i) is None:
                    self.adjustedSkeletonParts.append(None)
                else:
                    skeletonPart_ = SkeletonPartT.InitFromObj(autoBoneEpochResponse.AdjustedSkeletonParts(i))
                    self.adjustedSkeletonParts.append(skeletonPart_)

    # AutoBoneEpochResponseT
    def Pack(self, builder):
        if self.adjustedSkeletonParts is not None:
            adjustedSkeletonPartslist = []
            for i in range(len(self.adjustedSkeletonParts)):
                adjustedSkeletonPartslist.append(self.adjustedSkeletonParts[i].Pack(builder))
            AutoBoneEpochResponseStartAdjustedSkeletonPartsVector(builder, len(self.adjustedSkeletonParts))
            for i in reversed(range(len(self.adjustedSkeletonParts))):
                builder.PrependUOffsetTRelative(adjustedSkeletonPartslist[i])
            adjustedSkeletonParts = builder.EndVector()
        AutoBoneEpochResponseStart(builder)
        AutoBoneEpochResponseAddCurrentEpoch(builder, self.currentEpoch)
        AutoBoneEpochResponseAddTotalEpochs(builder, self.totalEpochs)
        AutoBoneEpochResponseAddEpochError(builder, self.epochError)
        if self.adjustedSkeletonParts is not None:
            AutoBoneEpochResponseAddAdjustedSkeletonParts(builder, adjustedSkeletonParts)
        autoBoneEpochResponse = AutoBoneEpochResponseEnd(builder)
        return autoBoneEpochResponse
