# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Applies the estimated proportions
class AutoBoneApplyRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AutoBoneApplyRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAutoBoneApplyRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AutoBoneApplyRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def AutoBoneApplyRequestStart(builder):
    builder.StartObject(0)

def Start(builder):
    AutoBoneApplyRequestStart(builder)

def AutoBoneApplyRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return AutoBoneApplyRequestEnd(builder)


class AutoBoneApplyRequestT(object):

    # AutoBoneApplyRequestT
    def __init__(
        self,
    ):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        autoBoneApplyRequest = AutoBoneApplyRequest()
        autoBoneApplyRequest.Init(buf, pos)
        return cls.InitFromObj(autoBoneApplyRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, autoBoneApplyRequest):
        x = AutoBoneApplyRequestT()
        x._UnPack(autoBoneApplyRequest)
        return x

    # AutoBoneApplyRequestT
    def _UnPack(self, autoBoneApplyRequest):
        if autoBoneApplyRequest is None:
            return

    # AutoBoneApplyRequestT
    def Pack(self, builder):
        AutoBoneApplyRequestStart(builder)
        autoBoneApplyRequest = AutoBoneApplyRequestEnd(builder)
        return autoBoneApplyRequest
