# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AutoBoneProcessRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AutoBoneProcessRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAutoBoneProcessRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AutoBoneProcessRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AutoBoneProcessRequest
    def ProcessType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def AutoBoneProcessRequestStart(builder):
    builder.StartObject(1)

def Start(builder):
    AutoBoneProcessRequestStart(builder)

def AutoBoneProcessRequestAddProcessType(builder, processType):
    builder.PrependUint8Slot(0, processType, 0)

def AddProcessType(builder, processType):
    AutoBoneProcessRequestAddProcessType(builder, processType)

def AutoBoneProcessRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return AutoBoneProcessRequestEnd(builder)


class AutoBoneProcessRequestT(object):

    # AutoBoneProcessRequestT
    def __init__(
        self,
        processType = 0,
    ):
        self.processType = processType  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        autoBoneProcessRequest = AutoBoneProcessRequest()
        autoBoneProcessRequest.Init(buf, pos)
        return cls.InitFromObj(autoBoneProcessRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, autoBoneProcessRequest):
        x = AutoBoneProcessRequestT()
        x._UnPack(autoBoneProcessRequest)
        return x

    # AutoBoneProcessRequestT
    def _UnPack(self, autoBoneProcessRequest):
        if autoBoneProcessRequest is None:
            return
        self.processType = autoBoneProcessRequest.ProcessType()

    # AutoBoneProcessRequestT
    def Pack(self, builder):
        AutoBoneProcessRequestStart(builder)
        AutoBoneProcessRequestAddProcessType(builder, self.processType)
        autoBoneProcessRequest = AutoBoneProcessRequestEnd(builder)
        return autoBoneProcessRequest
