# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Cancels the current recording, aborting the process and discarding the data
class AutoBoneCancelRecordingRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AutoBoneCancelRecordingRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAutoBoneCancelRecordingRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AutoBoneCancelRecordingRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def AutoBoneCancelRecordingRequestStart(builder):
    builder.StartObject(0)

def Start(builder):
    AutoBoneCancelRecordingRequestStart(builder)

def AutoBoneCancelRecordingRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return AutoBoneCancelRecordingRequestEnd(builder)


class AutoBoneCancelRecordingRequestT(object):

    # AutoBoneCancelRecordingRequestT
    def __init__(
        self,
    ):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        autoBoneCancelRecordingRequest = AutoBoneCancelRecordingRequest()
        autoBoneCancelRecordingRequest.Init(buf, pos)
        return cls.InitFromObj(autoBoneCancelRecordingRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, autoBoneCancelRecordingRequest):
        x = AutoBoneCancelRecordingRequestT()
        x._UnPack(autoBoneCancelRecordingRequest)
        return x

    # AutoBoneCancelRecordingRequestT
    def _UnPack(self, autoBoneCancelRecordingRequest):
        if autoBoneCancelRecordingRequest is None:
            return

    # AutoBoneCancelRecordingRequestT
    def Pack(self, builder):
        AutoBoneCancelRecordingRequestStart(builder)
        autoBoneCancelRecordingRequest = AutoBoneCancelRecordingRequestEnd(builder)
        return autoBoneCancelRecordingRequest
