# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CancelUserHeightCalibration(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CancelUserHeightCalibration()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCancelUserHeightCalibration(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CancelUserHeightCalibration
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def CancelUserHeightCalibrationStart(builder):
    builder.StartObject(0)

def Start(builder):
    CancelUserHeightCalibrationStart(builder)

def CancelUserHeightCalibrationEnd(builder):
    return builder.EndObject()

def End(builder):
    return CancelUserHeightCalibrationEnd(builder)


class CancelUserHeightCalibrationT(object):

    # CancelUserHeightCalibrationT
    def __init__(
        self,
    ):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cancelUserHeightCalibration = CancelUserHeightCalibration()
        cancelUserHeightCalibration.Init(buf, pos)
        return cls.InitFromObj(cancelUserHeightCalibration)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cancelUserHeightCalibration):
        x = CancelUserHeightCalibrationT()
        x._UnPack(cancelUserHeightCalibration)
        return x

    # CancelUserHeightCalibrationT
    def _UnPack(self, cancelUserHeightCalibration):
        if cancelUserHeightCalibration is None:
            return

    # CancelUserHeightCalibrationT
    def Pack(self, builder):
        CancelUserHeightCalibrationStart(builder)
        cancelUserHeightCalibration = CancelUserHeightCalibrationEnd(builder)
        return cancelUserHeightCalibration
