# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ChangeSkeletonConfigRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ChangeSkeletonConfigRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsChangeSkeletonConfigRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ChangeSkeletonConfigRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ChangeSkeletonConfigRequest
    def Bone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ChangeSkeletonConfigRequest
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def ChangeSkeletonConfigRequestStart(builder):
    builder.StartObject(2)

def Start(builder):
    ChangeSkeletonConfigRequestStart(builder)

def ChangeSkeletonConfigRequestAddBone(builder, bone):
    builder.PrependUint8Slot(0, bone, 0)

def AddBone(builder, bone):
    ChangeSkeletonConfigRequestAddBone(builder, bone)

def ChangeSkeletonConfigRequestAddValue(builder, value):
    builder.PrependFloat32Slot(1, value, 0.0)

def AddValue(builder, value):
    ChangeSkeletonConfigRequestAddValue(builder, value)

def ChangeSkeletonConfigRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return ChangeSkeletonConfigRequestEnd(builder)


class ChangeSkeletonConfigRequestT(object):

    # ChangeSkeletonConfigRequestT
    def __init__(
        self,
        bone = 0,
        value = 0.0,
    ):
        self.bone = bone  # type: int
        self.value = value  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        changeSkeletonConfigRequest = ChangeSkeletonConfigRequest()
        changeSkeletonConfigRequest.Init(buf, pos)
        return cls.InitFromObj(changeSkeletonConfigRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, changeSkeletonConfigRequest):
        x = ChangeSkeletonConfigRequestT()
        x._UnPack(changeSkeletonConfigRequest)
        return x

    # ChangeSkeletonConfigRequestT
    def _UnPack(self, changeSkeletonConfigRequest):
        if changeSkeletonConfigRequest is None:
            return
        self.bone = changeSkeletonConfigRequest.Bone()
        self.value = changeSkeletonConfigRequest.Value()

    # ChangeSkeletonConfigRequestT
    def Pack(self, builder):
        ChangeSkeletonConfigRequestStart(builder)
        ChangeSkeletonConfigRequestAddBone(builder, self.bone)
        ChangeSkeletonConfigRequestAddValue(builder, self.value)
        changeSkeletonConfigRequest = ChangeSkeletonConfigRequestEnd(builder)
        return changeSkeletonConfigRequest
