# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.datatypes.TrackerId import TrackerIdT
from solarxr_protocol.datatypes.TrackerId import TrackerId

# If no tracker ID is given, it's the setting for every tracker/device
class ChangeMagToggleRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ChangeMagToggleRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsChangeMagToggleRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ChangeMagToggleRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ChangeMagToggleRequest
    def TrackerId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = TrackerId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ChangeMagToggleRequest
    def Enable(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def ChangeMagToggleRequestStart(builder):
    builder.StartObject(2)

def Start(builder):
    ChangeMagToggleRequestStart(builder)

def ChangeMagToggleRequestAddTrackerId(builder, trackerId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(trackerId), 0)

def AddTrackerId(builder, trackerId):
    ChangeMagToggleRequestAddTrackerId(builder, trackerId)

def ChangeMagToggleRequestAddEnable(builder, enable):
    builder.PrependBoolSlot(1, enable, 0)

def AddEnable(builder, enable):
    ChangeMagToggleRequestAddEnable(builder, enable)

def ChangeMagToggleRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return ChangeMagToggleRequestEnd(builder)

try:
    from typing import Optional
except:
    pass

class ChangeMagToggleRequestT(object):

    # ChangeMagToggleRequestT
    def __init__(
        self,
        trackerId = None,
        enable = False,
    ):
        self.trackerId = trackerId  # type: Optional[TrackerIdT]
        self.enable = enable  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        changeMagToggleRequest = ChangeMagToggleRequest()
        changeMagToggleRequest.Init(buf, pos)
        return cls.InitFromObj(changeMagToggleRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, changeMagToggleRequest):
        x = ChangeMagToggleRequestT()
        x._UnPack(changeMagToggleRequest)
        return x

    # ChangeMagToggleRequestT
    def _UnPack(self, changeMagToggleRequest):
        if changeMagToggleRequest is None:
            return
        if changeMagToggleRequest.TrackerId() is not None:
            self.trackerId = TrackerIdT.InitFromObj(changeMagToggleRequest.TrackerId())
        self.enable = changeMagToggleRequest.Enable()

    # ChangeMagToggleRequestT
    def Pack(self, builder):
        if self.trackerId is not None:
            trackerId = self.trackerId.Pack(builder)
        ChangeMagToggleRequestStart(builder)
        if self.trackerId is not None:
            ChangeMagToggleRequestAddTrackerId(builder, trackerId)
        ChangeMagToggleRequestAddEnable(builder, self.enable)
        changeMagToggleRequest = ChangeMagToggleRequestEnd(builder)
        return changeMagToggleRequest
