# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.rpc.AutoBoneSettings import AutoBoneSettingsT
from solarxr_protocol.rpc.DriftCompensationSettings import DriftCompensationSettingsT
from solarxr_protocol.rpc.FilteringSettings import FilteringSettingsT
from solarxr_protocol.rpc.HIDSettings import HIDSettingsT
from solarxr_protocol.rpc.settings.ModelSettings import ModelSettingsT
from solarxr_protocol.rpc.OSCRouterSettings import OSCRouterSettingsT
from solarxr_protocol.rpc.ResetsSettings import ResetsSettingsT
from solarxr_protocol.rpc.StayAlignedSettings import StayAlignedSettingsT
from solarxr_protocol.rpc.SteamVRTrackersSetting import SteamVRTrackersSettingT
from solarxr_protocol.rpc.TapDetectionSettings import TapDetectionSettingsT
from solarxr_protocol.rpc.TimeoutSettings import TimeoutSettingsT
from solarxr_protocol.rpc.VMCOSCSettings import VMCOSCSettingsT
from solarxr_protocol.rpc.VRCOSCSettings import VRCOSCSettingsT
from solarxr_protocol.rpc.VRMSettings import VRMSettingsT
from solarxr_protocol.rpc.VelocitySettings import VelocitySettingsT
from solarxr_protocol.rpc.AutoBoneSettings import AutoBoneSettings
from solarxr_protocol.rpc.DriftCompensationSettings import DriftCompensationSettings
from solarxr_protocol.rpc.FilteringSettings import FilteringSettings
from solarxr_protocol.rpc.HIDSettings import HIDSettings
from solarxr_protocol.rpc.settings.ModelSettings import ModelSettings
from solarxr_protocol.rpc.OSCRouterSettings import OSCRouterSettings
from solarxr_protocol.rpc.ResetsSettings import ResetsSettings
from solarxr_protocol.rpc.StayAlignedSettings import StayAlignedSettings
from solarxr_protocol.rpc.SteamVRTrackersSetting import SteamVRTrackersSetting
from solarxr_protocol.rpc.TapDetectionSettings import TapDetectionSettings
from solarxr_protocol.rpc.TimeoutSettings import TimeoutSettings
from solarxr_protocol.rpc.VMCOSCSettings import VMCOSCSettings
from solarxr_protocol.rpc.VRCOSCSettings import VRCOSCSettings
from solarxr_protocol.rpc.VRMSettings import VRMSettings
from solarxr_protocol.rpc.VelocitySettings import VelocitySettings

class ChangeSettingsRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ChangeSettingsRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsChangeSettingsRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ChangeSettingsRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ChangeSettingsRequest
    def SteamVrTrackers(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = SteamVRTrackersSetting()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ChangeSettingsRequest
    def Filtering(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = FilteringSettings()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ChangeSettingsRequest
    def DriftCompensation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = DriftCompensationSettings()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ChangeSettingsRequest
    def OscRouter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = OSCRouterSettings()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ChangeSettingsRequest
    def VrcOsc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = VRCOSCSettings()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ChangeSettingsRequest
    def VmcOsc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = VMCOSCSettings()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ChangeSettingsRequest
    def ModelSettings(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = ModelSettings()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ChangeSettingsRequest
    def TapDetectionSettings(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = TapDetectionSettings()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ChangeSettingsRequest
    def AutoBoneSettings(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = AutoBoneSettings()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ChangeSettingsRequest
    def ResetsSettings(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = ResetsSettings()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ChangeSettingsRequest
    def StayAligned(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = StayAlignedSettings()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ChangeSettingsRequest
    def HidSettings(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = HIDSettings()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ChangeSettingsRequest
    def Timeout(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = TimeoutSettings()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ChangeSettingsRequest
    def VelocitySettings(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = VelocitySettings()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ChangeSettingsRequest
    def Vrm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = VRMSettings()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ChangeSettingsRequestStart(builder):
    builder.StartObject(15)

def Start(builder):
    ChangeSettingsRequestStart(builder)

def ChangeSettingsRequestAddSteamVrTrackers(builder, steamVrTrackers):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(steamVrTrackers), 0)

def AddSteamVrTrackers(builder, steamVrTrackers):
    ChangeSettingsRequestAddSteamVrTrackers(builder, steamVrTrackers)

def ChangeSettingsRequestAddFiltering(builder, filtering):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(filtering), 0)

def AddFiltering(builder, filtering):
    ChangeSettingsRequestAddFiltering(builder, filtering)

def ChangeSettingsRequestAddDriftCompensation(builder, driftCompensation):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(driftCompensation), 0)

def AddDriftCompensation(builder, driftCompensation):
    ChangeSettingsRequestAddDriftCompensation(builder, driftCompensation)

def ChangeSettingsRequestAddOscRouter(builder, oscRouter):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(oscRouter), 0)

def AddOscRouter(builder, oscRouter):
    ChangeSettingsRequestAddOscRouter(builder, oscRouter)

def ChangeSettingsRequestAddVrcOsc(builder, vrcOsc):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(vrcOsc), 0)

def AddVrcOsc(builder, vrcOsc):
    ChangeSettingsRequestAddVrcOsc(builder, vrcOsc)

def ChangeSettingsRequestAddVmcOsc(builder, vmcOsc):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(vmcOsc), 0)

def AddVmcOsc(builder, vmcOsc):
    ChangeSettingsRequestAddVmcOsc(builder, vmcOsc)

def ChangeSettingsRequestAddModelSettings(builder, modelSettings):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(modelSettings), 0)

def AddModelSettings(builder, modelSettings):
    ChangeSettingsRequestAddModelSettings(builder, modelSettings)

def ChangeSettingsRequestAddTapDetectionSettings(builder, tapDetectionSettings):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(tapDetectionSettings), 0)

def AddTapDetectionSettings(builder, tapDetectionSettings):
    ChangeSettingsRequestAddTapDetectionSettings(builder, tapDetectionSettings)

def ChangeSettingsRequestAddAutoBoneSettings(builder, autoBoneSettings):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(autoBoneSettings), 0)

def AddAutoBoneSettings(builder, autoBoneSettings):
    ChangeSettingsRequestAddAutoBoneSettings(builder, autoBoneSettings)

def ChangeSettingsRequestAddResetsSettings(builder, resetsSettings):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(resetsSettings), 0)

def AddResetsSettings(builder, resetsSettings):
    ChangeSettingsRequestAddResetsSettings(builder, resetsSettings)

def ChangeSettingsRequestAddStayAligned(builder, stayAligned):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(stayAligned), 0)

def AddStayAligned(builder, stayAligned):
    ChangeSettingsRequestAddStayAligned(builder, stayAligned)

def ChangeSettingsRequestAddHidSettings(builder, hidSettings):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(hidSettings), 0)

def AddHidSettings(builder, hidSettings):
    ChangeSettingsRequestAddHidSettings(builder, hidSettings)

def ChangeSettingsRequestAddTimeout(builder, timeout):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(timeout), 0)

def AddTimeout(builder, timeout):
    ChangeSettingsRequestAddTimeout(builder, timeout)

def ChangeSettingsRequestAddVelocitySettings(builder, velocitySettings):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(velocitySettings), 0)

def AddVelocitySettings(builder, velocitySettings):
    ChangeSettingsRequestAddVelocitySettings(builder, velocitySettings)

def ChangeSettingsRequestAddVrm(builder, vrm):
    builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(vrm), 0)

def AddVrm(builder, vrm):
    ChangeSettingsRequestAddVrm(builder, vrm)

def ChangeSettingsRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return ChangeSettingsRequestEnd(builder)

try:
    from typing import Optional
except:
    pass

class ChangeSettingsRequestT(object):

    # ChangeSettingsRequestT
    def __init__(
        self,
        steamVrTrackers = None,
        filtering = None,
        driftCompensation = None,
        oscRouter = None,
        vrcOsc = None,
        vmcOsc = None,
        modelSettings = None,
        tapDetectionSettings = None,
        autoBoneSettings = None,
        resetsSettings = None,
        stayAligned = None,
        hidSettings = None,
        timeout = None,
        velocitySettings = None,
        vrm = None,
    ):
        self.steamVrTrackers = steamVrTrackers  # type: Optional[SteamVRTrackersSettingT]
        self.filtering = filtering  # type: Optional[FilteringSettingsT]
        self.driftCompensation = driftCompensation  # type: Optional[DriftCompensationSettingsT]
        self.oscRouter = oscRouter  # type: Optional[OSCRouterSettingsT]
        self.vrcOsc = vrcOsc  # type: Optional[VRCOSCSettingsT]
        self.vmcOsc = vmcOsc  # type: Optional[VMCOSCSettingsT]
        self.modelSettings = modelSettings  # type: Optional[ModelSettingsT]
        self.tapDetectionSettings = tapDetectionSettings  # type: Optional[TapDetectionSettingsT]
        self.autoBoneSettings = autoBoneSettings  # type: Optional[AutoBoneSettingsT]
        self.resetsSettings = resetsSettings  # type: Optional[ResetsSettingsT]
        self.stayAligned = stayAligned  # type: Optional[StayAlignedSettingsT]
        self.hidSettings = hidSettings  # type: Optional[HIDSettingsT]
        self.timeout = timeout  # type: Optional[TimeoutSettingsT]
        self.velocitySettings = velocitySettings  # type: Optional[VelocitySettingsT]
        self.vrm = vrm  # type: Optional[VRMSettingsT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        changeSettingsRequest = ChangeSettingsRequest()
        changeSettingsRequest.Init(buf, pos)
        return cls.InitFromObj(changeSettingsRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, changeSettingsRequest):
        x = ChangeSettingsRequestT()
        x._UnPack(changeSettingsRequest)
        return x

    # ChangeSettingsRequestT
    def _UnPack(self, changeSettingsRequest):
        if changeSettingsRequest is None:
            return
        if changeSettingsRequest.SteamVrTrackers() is not None:
            self.steamVrTrackers = SteamVRTrackersSettingT.InitFromObj(changeSettingsRequest.SteamVrTrackers())
        if changeSettingsRequest.Filtering() is not None:
            self.filtering = FilteringSettingsT.InitFromObj(changeSettingsRequest.Filtering())
        if changeSettingsRequest.DriftCompensation() is not None:
            self.driftCompensation = DriftCompensationSettingsT.InitFromObj(changeSettingsRequest.DriftCompensation())
        if changeSettingsRequest.OscRouter() is not None:
            self.oscRouter = OSCRouterSettingsT.InitFromObj(changeSettingsRequest.OscRouter())
        if changeSettingsRequest.VrcOsc() is not None:
            self.vrcOsc = VRCOSCSettingsT.InitFromObj(changeSettingsRequest.VrcOsc())
        if changeSettingsRequest.VmcOsc() is not None:
            self.vmcOsc = VMCOSCSettingsT.InitFromObj(changeSettingsRequest.VmcOsc())
        if changeSettingsRequest.ModelSettings() is not None:
            self.modelSettings = ModelSettingsT.InitFromObj(changeSettingsRequest.ModelSettings())
        if changeSettingsRequest.TapDetectionSettings() is not None:
            self.tapDetectionSettings = TapDetectionSettingsT.InitFromObj(changeSettingsRequest.TapDetectionSettings())
        if changeSettingsRequest.AutoBoneSettings() is not None:
            self.autoBoneSettings = AutoBoneSettingsT.InitFromObj(changeSettingsRequest.AutoBoneSettings())
        if changeSettingsRequest.ResetsSettings() is not None:
            self.resetsSettings = ResetsSettingsT.InitFromObj(changeSettingsRequest.ResetsSettings())
        if changeSettingsRequest.StayAligned() is not None:
            self.stayAligned = StayAlignedSettingsT.InitFromObj(changeSettingsRequest.StayAligned())
        if changeSettingsRequest.HidSettings() is not None:
            self.hidSettings = HIDSettingsT.InitFromObj(changeSettingsRequest.HidSettings())
        if changeSettingsRequest.Timeout() is not None:
            self.timeout = TimeoutSettingsT.InitFromObj(changeSettingsRequest.Timeout())
        if changeSettingsRequest.VelocitySettings() is not None:
            self.velocitySettings = VelocitySettingsT.InitFromObj(changeSettingsRequest.VelocitySettings())
        if changeSettingsRequest.Vrm() is not None:
            self.vrm = VRMSettingsT.InitFromObj(changeSettingsRequest.Vrm())

    # ChangeSettingsRequestT
    def Pack(self, builder):
        if self.steamVrTrackers is not None:
            steamVrTrackers = self.steamVrTrackers.Pack(builder)
        if self.filtering is not None:
            filtering = self.filtering.Pack(builder)
        if self.driftCompensation is not None:
            driftCompensation = self.driftCompensation.Pack(builder)
        if self.oscRouter is not None:
            oscRouter = self.oscRouter.Pack(builder)
        if self.vrcOsc is not None:
            vrcOsc = self.vrcOsc.Pack(builder)
        if self.vmcOsc is not None:
            vmcOsc = self.vmcOsc.Pack(builder)
        if self.modelSettings is not None:
            modelSettings = self.modelSettings.Pack(builder)
        if self.tapDetectionSettings is not None:
            tapDetectionSettings = self.tapDetectionSettings.Pack(builder)
        if self.autoBoneSettings is not None:
            autoBoneSettings = self.autoBoneSettings.Pack(builder)
        if self.resetsSettings is not None:
            resetsSettings = self.resetsSettings.Pack(builder)
        if self.stayAligned is not None:
            stayAligned = self.stayAligned.Pack(builder)
        if self.hidSettings is not None:
            hidSettings = self.hidSettings.Pack(builder)
        if self.timeout is not None:
            timeout = self.timeout.Pack(builder)
        if self.velocitySettings is not None:
            velocitySettings = self.velocitySettings.Pack(builder)
        if self.vrm is not None:
            vrm = self.vrm.Pack(builder)
        ChangeSettingsRequestStart(builder)
        if self.steamVrTrackers is not None:
            ChangeSettingsRequestAddSteamVrTrackers(builder, steamVrTrackers)
        if self.filtering is not None:
            ChangeSettingsRequestAddFiltering(builder, filtering)
        if self.driftCompensation is not None:
            ChangeSettingsRequestAddDriftCompensation(builder, driftCompensation)
        if self.oscRouter is not None:
            ChangeSettingsRequestAddOscRouter(builder, oscRouter)
        if self.vrcOsc is not None:
            ChangeSettingsRequestAddVrcOsc(builder, vrcOsc)
        if self.vmcOsc is not None:
            ChangeSettingsRequestAddVmcOsc(builder, vmcOsc)
        if self.modelSettings is not None:
            ChangeSettingsRequestAddModelSettings(builder, modelSettings)
        if self.tapDetectionSettings is not None:
            ChangeSettingsRequestAddTapDetectionSettings(builder, tapDetectionSettings)
        if self.autoBoneSettings is not None:
            ChangeSettingsRequestAddAutoBoneSettings(builder, autoBoneSettings)
        if self.resetsSettings is not None:
            ChangeSettingsRequestAddResetsSettings(builder, resetsSettings)
        if self.stayAligned is not None:
            ChangeSettingsRequestAddStayAligned(builder, stayAligned)
        if self.hidSettings is not None:
            ChangeSettingsRequestAddHidSettings(builder, hidSettings)
        if self.timeout is not None:
            ChangeSettingsRequestAddTimeout(builder, timeout)
        if self.velocitySettings is not None:
            ChangeSettingsRequestAddVelocitySettings(builder, velocitySettings)
        if self.vrm is not None:
            ChangeSettingsRequestAddVrm(builder, vrm)
        changeSettingsRequest = ChangeSettingsRequestEnd(builder)
        return changeSettingsRequest
