# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ClearDriftCompensationRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ClearDriftCompensationRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsClearDriftCompensationRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ClearDriftCompensationRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def ClearDriftCompensationRequestStart(builder):
    builder.StartObject(0)

def Start(builder):
    ClearDriftCompensationRequestStart(builder)

def ClearDriftCompensationRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return ClearDriftCompensationRequestEnd(builder)


class ClearDriftCompensationRequestT(object):

    # ClearDriftCompensationRequestT
    def __init__(
        self,
    ):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        clearDriftCompensationRequest = ClearDriftCompensationRequest()
        clearDriftCompensationRequest.Init(buf, pos)
        return cls.InitFromObj(clearDriftCompensationRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, clearDriftCompensationRequest):
        x = ClearDriftCompensationRequestT()
        x._UnPack(clearDriftCompensationRequest)
        return x

    # ClearDriftCompensationRequestT
    def _UnPack(self, clearDriftCompensationRequest):
        if clearDriftCompensationRequest is None:
            return

    # ClearDriftCompensationRequestT
    def Pack(self, builder):
        ClearDriftCompensationRequestStart(builder)
        clearDriftCompensationRequest = ClearDriftCompensationRequestEnd(builder)
        return clearDriftCompensationRequest
