# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Clears mounting reset data, defaulting to the manually set mounting orientations
class ClearMountingResetRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ClearMountingResetRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsClearMountingResetRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ClearMountingResetRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def ClearMountingResetRequestStart(builder):
    builder.StartObject(0)

def Start(builder):
    ClearMountingResetRequestStart(builder)

def ClearMountingResetRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return ClearMountingResetRequestEnd(builder)


class ClearMountingResetRequestT(object):

    # ClearMountingResetRequestT
    def __init__(
        self,
    ):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        clearMountingResetRequest = ClearMountingResetRequest()
        clearMountingResetRequest.Init(buf, pos)
        return cls.InitFromObj(clearMountingResetRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, clearMountingResetRequest):
        x = ClearMountingResetRequestT()
        x._UnPack(clearMountingResetRequest)
        return x

    # ClearMountingResetRequestT
    def _UnPack(self, clearMountingResetRequest):
        if clearMountingResetRequest is None:
            return

    # ClearMountingResetRequestT
    def Pack(self, builder):
        ClearMountingResetRequestStart(builder)
        clearMountingResetRequest = ClearMountingResetRequestEnd(builder)
        return clearMountingResetRequest
