# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CloseSerialRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CloseSerialRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCloseSerialRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CloseSerialRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def CloseSerialRequestStart(builder):
    builder.StartObject(0)

def Start(builder):
    CloseSerialRequestStart(builder)

def CloseSerialRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return CloseSerialRequestEnd(builder)


class CloseSerialRequestT(object):

    # CloseSerialRequestT
    def __init__(
        self,
    ):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        closeSerialRequest = CloseSerialRequest()
        closeSerialRequest.Init(buf, pos)
        return cls.InitFromObj(closeSerialRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, closeSerialRequest):
        x = CloseSerialRequestT()
        x._UnPack(closeSerialRequest)
        return x

    # CloseSerialRequestT
    def _UnPack(self, closeSerialRequest):
        if closeSerialRequest is None:
            return

    # CloseSerialRequestT
    def Pack(self, builder):
        CloseSerialRequestStart(builder)
        closeSerialRequest = CloseSerialRequestEnd(builder)
        return closeSerialRequest
