# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DetectStayAlignedRelaxedPoseRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DetectStayAlignedRelaxedPoseRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDetectStayAlignedRelaxedPoseRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DetectStayAlignedRelaxedPoseRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DetectStayAlignedRelaxedPoseRequest
    def Pose(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def DetectStayAlignedRelaxedPoseRequestStart(builder):
    builder.StartObject(1)

def Start(builder):
    DetectStayAlignedRelaxedPoseRequestStart(builder)

def DetectStayAlignedRelaxedPoseRequestAddPose(builder, pose):
    builder.PrependUint8Slot(0, pose, 0)

def AddPose(builder, pose):
    DetectStayAlignedRelaxedPoseRequestAddPose(builder, pose)

def DetectStayAlignedRelaxedPoseRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return DetectStayAlignedRelaxedPoseRequestEnd(builder)


class DetectStayAlignedRelaxedPoseRequestT(object):

    # DetectStayAlignedRelaxedPoseRequestT
    def __init__(
        self,
        pose = 0,
    ):
        self.pose = pose  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        detectStayAlignedRelaxedPoseRequest = DetectStayAlignedRelaxedPoseRequest()
        detectStayAlignedRelaxedPoseRequest.Init(buf, pos)
        return cls.InitFromObj(detectStayAlignedRelaxedPoseRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, detectStayAlignedRelaxedPoseRequest):
        x = DetectStayAlignedRelaxedPoseRequestT()
        x._UnPack(detectStayAlignedRelaxedPoseRequest)
        return x

    # DetectStayAlignedRelaxedPoseRequestT
    def _UnPack(self, detectStayAlignedRelaxedPoseRequest):
        if detectStayAlignedRelaxedPoseRequest is None:
            return
        self.pose = detectStayAlignedRelaxedPoseRequest.Pose()

    # DetectStayAlignedRelaxedPoseRequestT
    def Pack(self, builder):
        DetectStayAlignedRelaxedPoseRequestStart(builder)
        DetectStayAlignedRelaxedPoseRequestAddPose(builder, self.pose)
        detectStayAlignedRelaxedPoseRequest = DetectStayAlignedRelaxedPoseRequestEnd(builder)
        return detectStayAlignedRelaxedPoseRequest
