# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Settings related to IMU yaw drift compensation
class DriftCompensationSettings(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DriftCompensationSettings()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDriftCompensationSettings(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DriftCompensationSettings
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DriftCompensationSettings
    def Enabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # DriftCompensationSettings
    def Prediction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # 0 to 1. A higher value results in more yaw drift compensation
    # DriftCompensationSettings
    def Amount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Number of previous resets to take into account when calculating yaw drift
    # DriftCompensationSettings
    def MaxResets(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def DriftCompensationSettingsStart(builder):
    builder.StartObject(4)

def Start(builder):
    DriftCompensationSettingsStart(builder)

def DriftCompensationSettingsAddEnabled(builder, enabled):
    builder.PrependBoolSlot(0, enabled, 0)

def AddEnabled(builder, enabled):
    DriftCompensationSettingsAddEnabled(builder, enabled)

def DriftCompensationSettingsAddPrediction(builder, prediction):
    builder.PrependBoolSlot(1, prediction, 0)

def AddPrediction(builder, prediction):
    DriftCompensationSettingsAddPrediction(builder, prediction)

def DriftCompensationSettingsAddAmount(builder, amount):
    builder.PrependFloat32Slot(2, amount, 0.0)

def AddAmount(builder, amount):
    DriftCompensationSettingsAddAmount(builder, amount)

def DriftCompensationSettingsAddMaxResets(builder, maxResets):
    builder.PrependUint16Slot(3, maxResets, 0)

def AddMaxResets(builder, maxResets):
    DriftCompensationSettingsAddMaxResets(builder, maxResets)

def DriftCompensationSettingsEnd(builder):
    return builder.EndObject()

def End(builder):
    return DriftCompensationSettingsEnd(builder)


class DriftCompensationSettingsT(object):

    # DriftCompensationSettingsT
    def __init__(
        self,
        enabled = False,
        prediction = False,
        amount = 0.0,
        maxResets = 0,
    ):
        self.enabled = enabled  # type: bool
        self.prediction = prediction  # type: bool
        self.amount = amount  # type: float
        self.maxResets = maxResets  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        driftCompensationSettings = DriftCompensationSettings()
        driftCompensationSettings.Init(buf, pos)
        return cls.InitFromObj(driftCompensationSettings)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, driftCompensationSettings):
        x = DriftCompensationSettingsT()
        x._UnPack(driftCompensationSettings)
        return x

    # DriftCompensationSettingsT
    def _UnPack(self, driftCompensationSettings):
        if driftCompensationSettings is None:
            return
        self.enabled = driftCompensationSettings.Enabled()
        self.prediction = driftCompensationSettings.Prediction()
        self.amount = driftCompensationSettings.Amount()
        self.maxResets = driftCompensationSettings.MaxResets()

    # DriftCompensationSettingsT
    def Pack(self, builder):
        DriftCompensationSettingsStart(builder)
        DriftCompensationSettingsAddEnabled(builder, self.enabled)
        DriftCompensationSettingsAddPrediction(builder, self.prediction)
        DriftCompensationSettingsAddAmount(builder, self.amount)
        DriftCompensationSettingsAddMaxResets(builder, self.maxResets)
        driftCompensationSettings = DriftCompensationSettingsEnd(builder)
        return driftCompensationSettings
