# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EnableStayAlignedRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EnableStayAlignedRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEnableStayAlignedRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EnableStayAlignedRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EnableStayAlignedRequest
    def Enable(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def EnableStayAlignedRequestStart(builder):
    builder.StartObject(1)

def Start(builder):
    EnableStayAlignedRequestStart(builder)

def EnableStayAlignedRequestAddEnable(builder, enable):
    builder.PrependBoolSlot(0, enable, 0)

def AddEnable(builder, enable):
    EnableStayAlignedRequestAddEnable(builder, enable)

def EnableStayAlignedRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return EnableStayAlignedRequestEnd(builder)


class EnableStayAlignedRequestT(object):

    # EnableStayAlignedRequestT
    def __init__(
        self,
        enable = False,
    ):
        self.enable = enable  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        enableStayAlignedRequest = EnableStayAlignedRequest()
        enableStayAlignedRequest.Init(buf, pos)
        return cls.InitFromObj(enableStayAlignedRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, enableStayAlignedRequest):
        x = EnableStayAlignedRequestT()
        x._UnPack(enableStayAlignedRequest)
        return x

    # EnableStayAlignedRequestT
    def _UnPack(self, enableStayAlignedRequest):
        if enableStayAlignedRequest is None:
            return
        self.enable = enableStayAlignedRequest.Enable()

    # EnableStayAlignedRequestT
    def Pack(self, builder):
        EnableStayAlignedRequestStart(builder)
        EnableStayAlignedRequestAddEnable(builder, self.enable)
        enableStayAlignedRequest = EnableStayAlignedRequestEnd(builder)
        return enableStayAlignedRequest
