# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EnableSteamVRDriverRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EnableSteamVRDriverRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEnableSteamVRDriverRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EnableSteamVRDriverRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def EnableSteamVRDriverRequestStart(builder):
    builder.StartObject(0)

def Start(builder):
    EnableSteamVRDriverRequestStart(builder)

def EnableSteamVRDriverRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return EnableSteamVRDriverRequestEnd(builder)


class EnableSteamVRDriverRequestT(object):

    # EnableSteamVRDriverRequestT
    def __init__(
        self,
    ):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        enableSteamVrdriverRequest = EnableSteamVRDriverRequest()
        enableSteamVrdriverRequest.Init(buf, pos)
        return cls.InitFromObj(enableSteamVrdriverRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, enableSteamVrdriverRequest):
        x = EnableSteamVRDriverRequestT()
        x._UnPack(enableSteamVrdriverRequest)
        return x

    # EnableSteamVRDriverRequestT
    def _UnPack(self, enableSteamVrdriverRequest):
        if enableSteamVrdriverRequest is None:
            return

    # EnableSteamVRDriverRequestT
    def Pack(self, builder):
        EnableSteamVRDriverRequestStart(builder)
        enableSteamVrdriverRequest = EnableSteamVRDriverRequestEnd(builder)
        return enableSteamVrdriverRequest
