# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FilteringSettings(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FilteringSettings()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFilteringSettings(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FilteringSettings
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FilteringSettings
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # 0 to 1. A higher value results in more smoothing or prediction
    # FilteringSettings
    def Amount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def FilteringSettingsStart(builder):
    builder.StartObject(2)

def Start(builder):
    FilteringSettingsStart(builder)

def FilteringSettingsAddType(builder, type):
    builder.PrependUint8Slot(0, type, 0)

def AddType(builder, type):
    FilteringSettingsAddType(builder, type)

def FilteringSettingsAddAmount(builder, amount):
    builder.PrependFloat32Slot(1, amount, 0.0)

def AddAmount(builder, amount):
    FilteringSettingsAddAmount(builder, amount)

def FilteringSettingsEnd(builder):
    return builder.EndObject()

def End(builder):
    return FilteringSettingsEnd(builder)


class FilteringSettingsT(object):

    # FilteringSettingsT
    def __init__(
        self,
        type = 0,
        amount = 0.0,
    ):
        self.type = type  # type: int
        self.amount = amount  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        filteringSettings = FilteringSettings()
        filteringSettings.Init(buf, pos)
        return cls.InitFromObj(filteringSettings)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, filteringSettings):
        x = FilteringSettingsT()
        x._UnPack(filteringSettings)
        return x

    # FilteringSettingsT
    def _UnPack(self, filteringSettings):
        if filteringSettings is None:
            return
        self.type = filteringSettings.Type()
        self.amount = filteringSettings.Amount()

    # FilteringSettingsT
    def Pack(self, builder):
        FilteringSettingsStart(builder)
        FilteringSettingsAddType(builder, self.type)
        FilteringSettingsAddAmount(builder, self.amount)
        filteringSettings = FilteringSettingsEnd(builder)
        return filteringSettings
