# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FirmwarePart(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FirmwarePart()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFirmwarePart(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FirmwarePart
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Url of the firmware bin to download
    # FirmwarePart
    def Url(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Offset of the firmware, used when flashing to the mcu, it indicates where to write this file in memory
    # Will be ignored in the case of OTA flashing
    # FirmwarePart
    def Offset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Checksum of the file
    # FirmwarePart
    def Digest(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def FirmwarePartStart(builder):
    builder.StartObject(3)

def Start(builder):
    FirmwarePartStart(builder)

def FirmwarePartAddUrl(builder, url):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(url), 0)

def AddUrl(builder, url):
    FirmwarePartAddUrl(builder, url)

def FirmwarePartAddOffset(builder, offset):
    builder.PrependUint32Slot(1, offset, 0)

def AddOffset(builder, offset):
    FirmwarePartAddOffset(builder, offset)

def FirmwarePartAddDigest(builder, digest):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(digest), 0)

def AddDigest(builder, digest):
    FirmwarePartAddDigest(builder, digest)

def FirmwarePartEnd(builder):
    return builder.EndObject()

def End(builder):
    return FirmwarePartEnd(builder)


class FirmwarePartT(object):

    # FirmwarePartT
    def __init__(
        self,
        url = None,
        offset = 0,
        digest = None,
    ):
        self.url = url  # type: Optional[str]
        self.offset = offset  # type: int
        self.digest = digest  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        firmwarePart = FirmwarePart()
        firmwarePart.Init(buf, pos)
        return cls.InitFromObj(firmwarePart)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, firmwarePart):
        x = FirmwarePartT()
        x._UnPack(firmwarePart)
        return x

    # FirmwarePartT
    def _UnPack(self, firmwarePart):
        if firmwarePart is None:
            return
        self.url = firmwarePart.Url()
        self.offset = firmwarePart.Offset()
        self.digest = firmwarePart.Digest()

    # FirmwarePartT
    def Pack(self, builder):
        if self.url is not None:
            url = builder.CreateString(self.url)
        if self.digest is not None:
            digest = builder.CreateString(self.digest)
        FirmwarePartStart(builder)
        if self.url is not None:
            FirmwarePartAddUrl(builder, url)
        FirmwarePartAddOffset(builder, self.offset)
        if self.digest is not None:
            FirmwarePartAddDigest(builder, digest)
        firmwarePart = FirmwarePartEnd(builder)
        return firmwarePart
