# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.rpc.FirmwareUpdateDeviceId import FirmwareUpdateDeviceIdCreator

class FirmwareUpdateStatusResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FirmwareUpdateStatusResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFirmwareUpdateStatusResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FirmwareUpdateStatusResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FirmwareUpdateStatusResponse
    def DeviceIdType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FirmwareUpdateStatusResponse
    def DeviceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

    # FirmwareUpdateStatusResponse
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # from 0 to 100
    # FirmwareUpdateStatusResponse
    def Progress(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def FirmwareUpdateStatusResponseStart(builder):
    builder.StartObject(4)

def Start(builder):
    FirmwareUpdateStatusResponseStart(builder)

def FirmwareUpdateStatusResponseAddDeviceIdType(builder, deviceIdType):
    builder.PrependUint8Slot(0, deviceIdType, 0)

def AddDeviceIdType(builder, deviceIdType):
    FirmwareUpdateStatusResponseAddDeviceIdType(builder, deviceIdType)

def FirmwareUpdateStatusResponseAddDeviceId(builder, deviceId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(deviceId), 0)

def AddDeviceId(builder, deviceId):
    FirmwareUpdateStatusResponseAddDeviceId(builder, deviceId)

def FirmwareUpdateStatusResponseAddStatus(builder, status):
    builder.PrependUint8Slot(2, status, 0)

def AddStatus(builder, status):
    FirmwareUpdateStatusResponseAddStatus(builder, status)

def FirmwareUpdateStatusResponseAddProgress(builder, progress):
    builder.PrependInt8Slot(3, progress, 0)

def AddProgress(builder, progress):
    FirmwareUpdateStatusResponseAddProgress(builder, progress)

def FirmwareUpdateStatusResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return FirmwareUpdateStatusResponseEnd(builder)

try:
    from typing import Union
except:
    pass

class FirmwareUpdateStatusResponseT(object):

    # FirmwareUpdateStatusResponseT
    def __init__(
        self,
        deviceIdType = 0,
        deviceId = None,
        status = 0,
        progress = 0,
    ):
        self.deviceIdType = deviceIdType  # type: int
        self.deviceId = deviceId  # type: Union[None, 'DeviceIdTableT', 'SerialDevicePortT']
        self.status = status  # type: int
        self.progress = progress  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        firmwareUpdateStatusResponse = FirmwareUpdateStatusResponse()
        firmwareUpdateStatusResponse.Init(buf, pos)
        return cls.InitFromObj(firmwareUpdateStatusResponse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, firmwareUpdateStatusResponse):
        x = FirmwareUpdateStatusResponseT()
        x._UnPack(firmwareUpdateStatusResponse)
        return x

    # FirmwareUpdateStatusResponseT
    def _UnPack(self, firmwareUpdateStatusResponse):
        if firmwareUpdateStatusResponse is None:
            return
        self.deviceIdType = firmwareUpdateStatusResponse.DeviceIdType()
        self.deviceId = FirmwareUpdateDeviceIdCreator(self.deviceIdType, firmwareUpdateStatusResponse.DeviceId())
        self.status = firmwareUpdateStatusResponse.Status()
        self.progress = firmwareUpdateStatusResponse.Progress()

    # FirmwareUpdateStatusResponseT
    def Pack(self, builder):
        if self.deviceId is not None:
            deviceId = self.deviceId.Pack(builder)
        FirmwareUpdateStatusResponseStart(builder)
        FirmwareUpdateStatusResponseAddDeviceIdType(builder, self.deviceIdType)
        if self.deviceId is not None:
            FirmwareUpdateStatusResponseAddDeviceId(builder, deviceId)
        FirmwareUpdateStatusResponseAddStatus(builder, self.status)
        FirmwareUpdateStatusResponseAddProgress(builder, self.progress)
        firmwareUpdateStatusResponse = FirmwareUpdateStatusResponseEnd(builder)
        return firmwareUpdateStatusResponse
