from solarxr_protocol.datatypes.DeviceIdTable import DeviceIdTableT
from solarxr_protocol.rpc.SerialDevicePort import SerialDevicePortT
# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

class FirmwareUpdateDeviceId(object):
    NONE = 0
    solarxr_protocol_datatypes_DeviceIdTable = 1
    SerialDevicePort = 2

def FirmwareUpdateDeviceIdCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == FirmwareUpdateDeviceId.solarxr_protocol_datatypes_DeviceIdTable:
        return DeviceIdTableT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == FirmwareUpdateDeviceId.SerialDevicePort:
        return SerialDevicePortT.InitFromBuf(table.Bytes, table.Pos)
    return None
