# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HeartbeatRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HeartbeatRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHeartbeatRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HeartbeatRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def HeartbeatRequestStart(builder):
    builder.StartObject(0)

def Start(builder):
    HeartbeatRequestStart(builder)

def HeartbeatRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return HeartbeatRequestEnd(builder)


class HeartbeatRequestT(object):

    # HeartbeatRequestT
    def __init__(
        self,
    ):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        heartbeatRequest = HeartbeatRequest()
        heartbeatRequest.Init(buf, pos)
        return cls.InitFromObj(heartbeatRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, heartbeatRequest):
        x = HeartbeatRequestT()
        x._UnPack(heartbeatRequest)
        return x

    # HeartbeatRequestT
    def _UnPack(self, heartbeatRequest):
        if heartbeatRequest is None:
            return

    # HeartbeatRequestT
    def Pack(self, builder):
        HeartbeatRequestStart(builder)
        heartbeatRequest = HeartbeatRequestEnd(builder)
        return heartbeatRequest
