# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Returns the current min and max positional tracker heights
class HeightResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HeightResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHeightResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HeightResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HeightResponse
    def MinHeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # HeightResponse
    def MaxHeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def HeightResponseStart(builder):
    builder.StartObject(2)

def Start(builder):
    HeightResponseStart(builder)

def HeightResponseAddMinHeight(builder, minHeight):
    builder.PrependFloat32Slot(0, minHeight, 0.0)

def AddMinHeight(builder, minHeight):
    HeightResponseAddMinHeight(builder, minHeight)

def HeightResponseAddMaxHeight(builder, maxHeight):
    builder.PrependFloat32Slot(1, maxHeight, 0.0)

def AddMaxHeight(builder, maxHeight):
    HeightResponseAddMaxHeight(builder, maxHeight)

def HeightResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return HeightResponseEnd(builder)


class HeightResponseT(object):

    # HeightResponseT
    def __init__(
        self,
        minHeight = 0.0,
        maxHeight = 0.0,
    ):
        self.minHeight = minHeight  # type: float
        self.maxHeight = maxHeight  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        heightResponse = HeightResponse()
        heightResponse.Init(buf, pos)
        return cls.InitFromObj(heightResponse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, heightResponse):
        x = HeightResponseT()
        x._UnPack(heightResponse)
        return x

    # HeightResponseT
    def _UnPack(self, heightResponse):
        if heightResponse is None:
            return
        self.minHeight = heightResponse.MinHeight()
        self.maxHeight = heightResponse.MaxHeight()

    # HeightResponseT
    def Pack(self, builder):
        HeightResponseStart(builder)
        HeightResponseAddMinHeight(builder, self.minHeight)
        HeightResponseAddMaxHeight(builder, self.maxHeight)
        heightResponse = HeightResponseEnd(builder)
        return heightResponse
