# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HIDSettings(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HIDSettings()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHIDSettings(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HIDSettings
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HIDSettings
    def TrackersOverHid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def HIDSettingsStart(builder):
    builder.StartObject(1)

def Start(builder):
    HIDSettingsStart(builder)

def HIDSettingsAddTrackersOverHid(builder, trackersOverHid):
    builder.PrependBoolSlot(0, trackersOverHid, 0)

def AddTrackersOverHid(builder, trackersOverHid):
    HIDSettingsAddTrackersOverHid(builder, trackersOverHid)

def HIDSettingsEnd(builder):
    return builder.EndObject()

def End(builder):
    return HIDSettingsEnd(builder)


class HIDSettingsT(object):

    # HIDSettingsT
    def __init__(
        self,
        trackersOverHid = False,
    ):
        self.trackersOverHid = trackersOverHid  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        hidsettings = HIDSettings()
        hidsettings.Init(buf, pos)
        return cls.InitFromObj(hidsettings)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, hidsettings):
        x = HIDSettingsT()
        x._UnPack(hidsettings)
        return x

    # HIDSettingsT
    def _UnPack(self, hidsettings):
        if hidsettings is None:
            return
        self.trackersOverHid = hidsettings.TrackersOverHid()

    # HIDSettingsT
    def Pack(self, builder):
        HIDSettingsStart(builder)
        HIDSettingsAddTrackersOverHid(builder, self.trackersOverHid)
        hidsettings = HIDSettingsEnd(builder)
        return hidsettings
