# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InstalledInfoResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InstalledInfoResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInstalledInfoResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InstalledInfoResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InstalledInfoResponse
    def IsUdevInstalled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # InstalledInfoResponse
    def IsWayland(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def InstalledInfoResponseStart(builder):
    builder.StartObject(2)

def Start(builder):
    InstalledInfoResponseStart(builder)

def InstalledInfoResponseAddIsUdevInstalled(builder, isUdevInstalled):
    builder.PrependBoolSlot(0, isUdevInstalled, 0)

def AddIsUdevInstalled(builder, isUdevInstalled):
    InstalledInfoResponseAddIsUdevInstalled(builder, isUdevInstalled)

def InstalledInfoResponseAddIsWayland(builder, isWayland):
    builder.PrependBoolSlot(1, isWayland, 0)

def AddIsWayland(builder, isWayland):
    InstalledInfoResponseAddIsWayland(builder, isWayland)

def InstalledInfoResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return InstalledInfoResponseEnd(builder)


class InstalledInfoResponseT(object):

    # InstalledInfoResponseT
    def __init__(
        self,
        isUdevInstalled = False,
        isWayland = False,
    ):
        self.isUdevInstalled = isUdevInstalled  # type: bool
        self.isWayland = isWayland  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        installedInfoResponse = InstalledInfoResponse()
        installedInfoResponse.Init(buf, pos)
        return cls.InitFromObj(installedInfoResponse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, installedInfoResponse):
        x = InstalledInfoResponseT()
        x._UnPack(installedInfoResponse)
        return x

    # InstalledInfoResponseT
    def _UnPack(self, installedInfoResponse):
        if installedInfoResponse is None:
            return
        self.isUdevInstalled = installedInfoResponse.IsUdevInstalled()
        self.isWayland = installedInfoResponse.IsWayland()

    # InstalledInfoResponseT
    def Pack(self, builder):
        InstalledInfoResponseStart(builder)
        InstalledInfoResponseAddIsUdevInstalled(builder, self.isUdevInstalled)
        InstalledInfoResponseAddIsWayland(builder, self.isWayland)
        installedInfoResponse = InstalledInfoResponseEnd(builder)
        return installedInfoResponse
