# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.rpc.Keybind import KeybindT
from solarxr_protocol.rpc.Keybind import Keybind

class KeybindResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KeybindResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsKeybindResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # KeybindResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # KeybindResponse
    def Keybind(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Keybind()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KeybindResponse
    def KeybindLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # KeybindResponse
    def KeybindIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # KeybindResponse
    def DefaultKeybinds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Keybind()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KeybindResponse
    def DefaultKeybindsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # KeybindResponse
    def DefaultKeybindsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def KeybindResponseStart(builder):
    builder.StartObject(2)

def Start(builder):
    KeybindResponseStart(builder)

def KeybindResponseAddKeybind(builder, keybind):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(keybind), 0)

def AddKeybind(builder, keybind):
    KeybindResponseAddKeybind(builder, keybind)

def KeybindResponseStartKeybindVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartKeybindVector(builder, numElems):
    return KeybindResponseStartKeybindVector(builder, numElems)

def KeybindResponseAddDefaultKeybinds(builder, defaultKeybinds):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(defaultKeybinds), 0)

def AddDefaultKeybinds(builder, defaultKeybinds):
    KeybindResponseAddDefaultKeybinds(builder, defaultKeybinds)

def KeybindResponseStartDefaultKeybindsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDefaultKeybindsVector(builder, numElems):
    return KeybindResponseStartDefaultKeybindsVector(builder, numElems)

def KeybindResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return KeybindResponseEnd(builder)

try:
    from typing import List
except:
    pass

class KeybindResponseT(object):

    # KeybindResponseT
    def __init__(
        self,
        keybind = None,
        defaultKeybinds = None,
    ):
        self.keybind = keybind  # type: Optional[List[KeybindT]]
        self.defaultKeybinds = defaultKeybinds  # type: Optional[List[KeybindT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        keybindResponse = KeybindResponse()
        keybindResponse.Init(buf, pos)
        return cls.InitFromObj(keybindResponse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, keybindResponse):
        x = KeybindResponseT()
        x._UnPack(keybindResponse)
        return x

    # KeybindResponseT
    def _UnPack(self, keybindResponse):
        if keybindResponse is None:
            return
        if not keybindResponse.KeybindIsNone():
            self.keybind = []
            for i in range(keybindResponse.KeybindLength()):
                if keybindResponse.Keybind(i) is None:
                    self.keybind.append(None)
                else:
                    keybind_ = KeybindT.InitFromObj(keybindResponse.Keybind(i))
                    self.keybind.append(keybind_)
        if not keybindResponse.DefaultKeybindsIsNone():
            self.defaultKeybinds = []
            for i in range(keybindResponse.DefaultKeybindsLength()):
                if keybindResponse.DefaultKeybinds(i) is None:
                    self.defaultKeybinds.append(None)
                else:
                    keybind_ = KeybindT.InitFromObj(keybindResponse.DefaultKeybinds(i))
                    self.defaultKeybinds.append(keybind_)

    # KeybindResponseT
    def Pack(self, builder):
        if self.keybind is not None:
            keybindlist = []
            for i in range(len(self.keybind)):
                keybindlist.append(self.keybind[i].Pack(builder))
            KeybindResponseStartKeybindVector(builder, len(self.keybind))
            for i in reversed(range(len(self.keybind))):
                builder.PrependUOffsetTRelative(keybindlist[i])
            keybind = builder.EndVector()
        if self.defaultKeybinds is not None:
            defaultKeybindslist = []
            for i in range(len(self.defaultKeybinds)):
                defaultKeybindslist.append(self.defaultKeybinds[i].Pack(builder))
            KeybindResponseStartDefaultKeybindsVector(builder, len(self.defaultKeybinds))
            for i in reversed(range(len(self.defaultKeybinds))):
                builder.PrependUOffsetTRelative(defaultKeybindslist[i])
            defaultKeybinds = builder.EndVector()
        KeybindResponseStart(builder)
        if self.keybind is not None:
            KeybindResponseAddKeybind(builder, keybind)
        if self.defaultKeybinds is not None:
            KeybindResponseAddDefaultKeybinds(builder, defaultKeybinds)
        keybindResponse = KeybindResponseEnd(builder)
        return keybindResponse
