# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.datatypes.TrackerId import TrackerIdT
from solarxr_protocol.datatypes.TrackerId import TrackerId

# If no tracker ID is given, it's the setting for every tracker/device
class MagToggleResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MagToggleResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMagToggleResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MagToggleResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MagToggleResponse
    def TrackerId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = TrackerId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MagToggleResponse
    def Enable(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def MagToggleResponseStart(builder):
    builder.StartObject(2)

def Start(builder):
    MagToggleResponseStart(builder)

def MagToggleResponseAddTrackerId(builder, trackerId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(trackerId), 0)

def AddTrackerId(builder, trackerId):
    MagToggleResponseAddTrackerId(builder, trackerId)

def MagToggleResponseAddEnable(builder, enable):
    builder.PrependBoolSlot(1, enable, 0)

def AddEnable(builder, enable):
    MagToggleResponseAddEnable(builder, enable)

def MagToggleResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return MagToggleResponseEnd(builder)

try:
    from typing import Optional
except:
    pass

class MagToggleResponseT(object):

    # MagToggleResponseT
    def __init__(
        self,
        trackerId = None,
        enable = False,
    ):
        self.trackerId = trackerId  # type: Optional[TrackerIdT]
        self.enable = enable  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        magToggleResponse = MagToggleResponse()
        magToggleResponse.Init(buf, pos)
        return cls.InitFromObj(magToggleResponse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, magToggleResponse):
        x = MagToggleResponseT()
        x._UnPack(magToggleResponse)
        return x

    # MagToggleResponseT
    def _UnPack(self, magToggleResponse):
        if magToggleResponse is None:
            return
        if magToggleResponse.TrackerId() is not None:
            self.trackerId = TrackerIdT.InitFromObj(magToggleResponse.TrackerId())
        self.enable = magToggleResponse.Enable()

    # MagToggleResponseT
    def Pack(self, builder):
        if self.trackerId is not None:
            trackerId = self.trackerId.Pack(builder)
        MagToggleResponseStart(builder)
        if self.trackerId is not None:
            MagToggleResponseAddTrackerId(builder, trackerId)
        MagToggleResponseAddEnable(builder, self.enable)
        magToggleResponse = MagToggleResponseEnd(builder)
        return magToggleResponse
