# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OpenUriRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OpenUriRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOpenUriRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OpenUriRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def OpenUriRequestStart(builder):
    builder.StartObject(0)

def Start(builder):
    OpenUriRequestStart(builder)

def OpenUriRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return OpenUriRequestEnd(builder)


class OpenUriRequestT(object):

    # OpenUriRequestT
    def __init__(
        self,
    ):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        openUriRequest = OpenUriRequest()
        openUriRequest.Init(buf, pos)
        return cls.InitFromObj(openUriRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, openUriRequest):
        x = OpenUriRequestT()
        x._UnPack(openUriRequest)
        return x

    # OpenUriRequestT
    def _UnPack(self, openUriRequest):
        if openUriRequest is None:
            return

    # OpenUriRequestT
    def Pack(self, builder):
        OpenUriRequestStart(builder)
        openUriRequest = OpenUriRequestEnd(builder)
        return openUriRequest
