# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# OSC Settings that are used in *any* osc application.
class OSCSettings(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OSCSettings()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOSCSettings(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OSCSettings
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OSCSettings
    def Enabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # OSCSettings
    def PortIn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # OSCSettings
    def PortOut(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # OSCSettings
    def Address(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def OSCSettingsStart(builder):
    builder.StartObject(4)

def Start(builder):
    OSCSettingsStart(builder)

def OSCSettingsAddEnabled(builder, enabled):
    builder.PrependBoolSlot(0, enabled, 0)

def AddEnabled(builder, enabled):
    OSCSettingsAddEnabled(builder, enabled)

def OSCSettingsAddPortIn(builder, portIn):
    builder.PrependUint16Slot(1, portIn, 0)

def AddPortIn(builder, portIn):
    OSCSettingsAddPortIn(builder, portIn)

def OSCSettingsAddPortOut(builder, portOut):
    builder.PrependUint16Slot(2, portOut, 0)

def AddPortOut(builder, portOut):
    OSCSettingsAddPortOut(builder, portOut)

def OSCSettingsAddAddress(builder, address):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(address), 0)

def AddAddress(builder, address):
    OSCSettingsAddAddress(builder, address)

def OSCSettingsEnd(builder):
    return builder.EndObject()

def End(builder):
    return OSCSettingsEnd(builder)


class OSCSettingsT(object):

    # OSCSettingsT
    def __init__(
        self,
        enabled = False,
        portIn = 0,
        portOut = 0,
        address = None,
    ):
        self.enabled = enabled  # type: bool
        self.portIn = portIn  # type: int
        self.portOut = portOut  # type: int
        self.address = address  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        oscsettings = OSCSettings()
        oscsettings.Init(buf, pos)
        return cls.InitFromObj(oscsettings)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, oscsettings):
        x = OSCSettingsT()
        x._UnPack(oscsettings)
        return x

    # OSCSettingsT
    def _UnPack(self, oscsettings):
        if oscsettings is None:
            return
        self.enabled = oscsettings.Enabled()
        self.portIn = oscsettings.PortIn()
        self.portOut = oscsettings.PortOut()
        self.address = oscsettings.Address()

    # OSCSettingsT
    def Pack(self, builder):
        if self.address is not None:
            address = builder.CreateString(self.address)
        OSCSettingsStart(builder)
        OSCSettingsAddEnabled(builder, self.enabled)
        OSCSettingsAddPortIn(builder, self.portIn)
        OSCSettingsAddPortOut(builder, self.portOut)
        if self.address is not None:
            OSCSettingsAddAddress(builder, address)
        oscsettings = OSCSettingsEnd(builder)
        return oscsettings
