# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OSCTrackersSetting(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OSCTrackersSetting()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOSCTrackersSetting(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OSCTrackersSetting
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OSCTrackersSetting
    def Head(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # OSCTrackersSetting
    def Chest(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # OSCTrackersSetting
    def Waist(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # OSCTrackersSetting
    def Knees(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # OSCTrackersSetting
    def Feet(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # OSCTrackersSetting
    def Elbows(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # OSCTrackersSetting
    def Hands(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def OSCTrackersSettingStart(builder):
    builder.StartObject(7)

def Start(builder):
    OSCTrackersSettingStart(builder)

def OSCTrackersSettingAddHead(builder, head):
    builder.PrependBoolSlot(0, head, 0)

def AddHead(builder, head):
    OSCTrackersSettingAddHead(builder, head)

def OSCTrackersSettingAddChest(builder, chest):
    builder.PrependBoolSlot(1, chest, 0)

def AddChest(builder, chest):
    OSCTrackersSettingAddChest(builder, chest)

def OSCTrackersSettingAddWaist(builder, waist):
    builder.PrependBoolSlot(2, waist, 0)

def AddWaist(builder, waist):
    OSCTrackersSettingAddWaist(builder, waist)

def OSCTrackersSettingAddKnees(builder, knees):
    builder.PrependBoolSlot(3, knees, 0)

def AddKnees(builder, knees):
    OSCTrackersSettingAddKnees(builder, knees)

def OSCTrackersSettingAddFeet(builder, feet):
    builder.PrependBoolSlot(4, feet, 0)

def AddFeet(builder, feet):
    OSCTrackersSettingAddFeet(builder, feet)

def OSCTrackersSettingAddElbows(builder, elbows):
    builder.PrependBoolSlot(5, elbows, 0)

def AddElbows(builder, elbows):
    OSCTrackersSettingAddElbows(builder, elbows)

def OSCTrackersSettingAddHands(builder, hands):
    builder.PrependBoolSlot(6, hands, 0)

def AddHands(builder, hands):
    OSCTrackersSettingAddHands(builder, hands)

def OSCTrackersSettingEnd(builder):
    return builder.EndObject()

def End(builder):
    return OSCTrackersSettingEnd(builder)


class OSCTrackersSettingT(object):

    # OSCTrackersSettingT
    def __init__(
        self,
        head = False,
        chest = False,
        waist = False,
        knees = False,
        feet = False,
        elbows = False,
        hands = False,
    ):
        self.head = head  # type: bool
        self.chest = chest  # type: bool
        self.waist = waist  # type: bool
        self.knees = knees  # type: bool
        self.feet = feet  # type: bool
        self.elbows = elbows  # type: bool
        self.hands = hands  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        osctrackersSetting = OSCTrackersSetting()
        osctrackersSetting.Init(buf, pos)
        return cls.InitFromObj(osctrackersSetting)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, osctrackersSetting):
        x = OSCTrackersSettingT()
        x._UnPack(osctrackersSetting)
        return x

    # OSCTrackersSettingT
    def _UnPack(self, osctrackersSetting):
        if osctrackersSetting is None:
            return
        self.head = osctrackersSetting.Head()
        self.chest = osctrackersSetting.Chest()
        self.waist = osctrackersSetting.Waist()
        self.knees = osctrackersSetting.Knees()
        self.feet = osctrackersSetting.Feet()
        self.elbows = osctrackersSetting.Elbows()
        self.hands = osctrackersSetting.Hands()

    # OSCTrackersSettingT
    def Pack(self, builder):
        OSCTrackersSettingStart(builder)
        OSCTrackersSettingAddHead(builder, self.head)
        OSCTrackersSettingAddChest(builder, self.chest)
        OSCTrackersSettingAddWaist(builder, self.waist)
        OSCTrackersSettingAddKnees(builder, self.knees)
        OSCTrackersSettingAddFeet(builder, self.feet)
        OSCTrackersSettingAddElbows(builder, self.elbows)
        OSCTrackersSettingAddHands(builder, self.hands)
        osctrackersSetting = OSCTrackersSettingEnd(builder)
        return osctrackersSetting
