# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Requests the current state of `OverlayDisplayModeResponse`.
class OverlayDisplayModeRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OverlayDisplayModeRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOverlayDisplayModeRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OverlayDisplayModeRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def OverlayDisplayModeRequestStart(builder):
    builder.StartObject(0)

def Start(builder):
    OverlayDisplayModeRequestStart(builder)

def OverlayDisplayModeRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return OverlayDisplayModeRequestEnd(builder)


class OverlayDisplayModeRequestT(object):

    # OverlayDisplayModeRequestT
    def __init__(
        self,
    ):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        overlayDisplayModeRequest = OverlayDisplayModeRequest()
        overlayDisplayModeRequest.Init(buf, pos)
        return cls.InitFromObj(overlayDisplayModeRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, overlayDisplayModeRequest):
        x = OverlayDisplayModeRequestT()
        x._UnPack(overlayDisplayModeRequest)
        return x

    # OverlayDisplayModeRequestT
    def _UnPack(self, overlayDisplayModeRequest):
        if overlayDisplayModeRequest is None:
            return

    # OverlayDisplayModeRequestT
    def Pack(self, builder):
        OverlayDisplayModeRequestStart(builder)
        overlayDisplayModeRequest = OverlayDisplayModeRequestEnd(builder)
        return overlayDisplayModeRequest
