# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Changes the state of the overlay's display mode.
class OverlayDisplayModeChangeRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OverlayDisplayModeChangeRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOverlayDisplayModeChangeRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OverlayDisplayModeChangeRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OverlayDisplayModeChangeRequest
    def IsVisible(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return None

    # OverlayDisplayModeChangeRequest
    def IsMirrored(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return None

def OverlayDisplayModeChangeRequestStart(builder):
    builder.StartObject(2)

def Start(builder):
    OverlayDisplayModeChangeRequestStart(builder)

def OverlayDisplayModeChangeRequestAddIsVisible(builder, isVisible):
    builder.PrependBoolSlot(0, isVisible, None)

def AddIsVisible(builder, isVisible):
    OverlayDisplayModeChangeRequestAddIsVisible(builder, isVisible)

def OverlayDisplayModeChangeRequestAddIsMirrored(builder, isMirrored):
    builder.PrependBoolSlot(1, isMirrored, None)

def AddIsMirrored(builder, isMirrored):
    OverlayDisplayModeChangeRequestAddIsMirrored(builder, isMirrored)

def OverlayDisplayModeChangeRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return OverlayDisplayModeChangeRequestEnd(builder)

try:
    from typing import Optional
except:
    pass

class OverlayDisplayModeChangeRequestT(object):

    # OverlayDisplayModeChangeRequestT
    def __init__(
        self,
        isVisible = None,
        isMirrored = None,
    ):
        self.isVisible = isVisible  # type: Optional[bool]
        self.isMirrored = isMirrored  # type: Optional[bool]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        overlayDisplayModeChangeRequest = OverlayDisplayModeChangeRequest()
        overlayDisplayModeChangeRequest.Init(buf, pos)
        return cls.InitFromObj(overlayDisplayModeChangeRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, overlayDisplayModeChangeRequest):
        x = OverlayDisplayModeChangeRequestT()
        x._UnPack(overlayDisplayModeChangeRequest)
        return x

    # OverlayDisplayModeChangeRequestT
    def _UnPack(self, overlayDisplayModeChangeRequest):
        if overlayDisplayModeChangeRequest is None:
            return
        self.isVisible = overlayDisplayModeChangeRequest.IsVisible()
        self.isMirrored = overlayDisplayModeChangeRequest.IsMirrored()

    # OverlayDisplayModeChangeRequestT
    def Pack(self, builder):
        OverlayDisplayModeChangeRequestStart(builder)
        OverlayDisplayModeChangeRequestAddIsVisible(builder, self.isVisible)
        OverlayDisplayModeChangeRequestAddIsMirrored(builder, self.isMirrored)
        overlayDisplayModeChangeRequest = OverlayDisplayModeChangeRequestEnd(builder)
        return overlayDisplayModeChangeRequest
