# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RecordBVHRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RecordBVHRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRecordBVHRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RecordBVHRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RecordBVHRequest
    def Stop(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Path sent when starting the recording, if null the recording won't happen.
    # Has different behavior depending if its a file path or a directory path.
    # RecordBVHRequest
    def Path(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def RecordBVHRequestStart(builder):
    builder.StartObject(2)

def Start(builder):
    RecordBVHRequestStart(builder)

def RecordBVHRequestAddStop(builder, stop):
    builder.PrependBoolSlot(0, stop, 0)

def AddStop(builder, stop):
    RecordBVHRequestAddStop(builder, stop)

def RecordBVHRequestAddPath(builder, path):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(path), 0)

def AddPath(builder, path):
    RecordBVHRequestAddPath(builder, path)

def RecordBVHRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return RecordBVHRequestEnd(builder)


class RecordBVHRequestT(object):

    # RecordBVHRequestT
    def __init__(
        self,
        stop = False,
        path = None,
    ):
        self.stop = stop  # type: bool
        self.path = path  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        recordBvhrequest = RecordBVHRequest()
        recordBvhrequest.Init(buf, pos)
        return cls.InitFromObj(recordBvhrequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, recordBvhrequest):
        x = RecordBVHRequestT()
        x._UnPack(recordBvhrequest)
        return x

    # RecordBVHRequestT
    def _UnPack(self, recordBvhrequest):
        if recordBvhrequest is None:
            return
        self.stop = recordBvhrequest.Stop()
        self.path = recordBvhrequest.Path()

    # RecordBVHRequestT
    def Pack(self, builder):
        if self.path is not None:
            path = builder.CreateString(self.path)
        RecordBVHRequestStart(builder)
        RecordBVHRequestAddStop(builder, self.stop)
        if self.path is not None:
            RecordBVHRequestAddPath(builder, path)
        recordBvhrequest = RecordBVHRequestEnd(builder)
        return recordBvhrequest
