# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RecordBVHStatus(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RecordBVHStatus()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRecordBVHStatus(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RecordBVHStatus
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RecordBVHStatus
    def Recording(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def RecordBVHStatusStart(builder):
    builder.StartObject(1)

def Start(builder):
    RecordBVHStatusStart(builder)

def RecordBVHStatusAddRecording(builder, recording):
    builder.PrependBoolSlot(0, recording, 0)

def AddRecording(builder, recording):
    RecordBVHStatusAddRecording(builder, recording)

def RecordBVHStatusEnd(builder):
    return builder.EndObject()

def End(builder):
    return RecordBVHStatusEnd(builder)


class RecordBVHStatusT(object):

    # RecordBVHStatusT
    def __init__(
        self,
        recording = False,
    ):
        self.recording = recording  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        recordBvhstatus = RecordBVHStatus()
        recordBvhstatus.Init(buf, pos)
        return cls.InitFromObj(recordBvhstatus)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, recordBvhstatus):
        x = RecordBVHStatusT()
        x._UnPack(recordBvhstatus)
        return x

    # RecordBVHStatusT
    def _UnPack(self, recordBvhstatus):
        if recordBvhstatus is None:
            return
        self.recording = recordBvhstatus.Recording()

    # RecordBVHStatusT
    def Pack(self, builder):
        RecordBVHStatusStart(builder)
        RecordBVHStatusAddRecording(builder, self.recording)
        recordBvhstatus = RecordBVHStatusEnd(builder)
        return recordBvhstatus
