# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ResetResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ResetResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResetResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ResetResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ResetResponse
    def ResetType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ResetResponse
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Should return the body parts reseted / being reset
    # ResetResponse
    def BodyParts(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ResetResponse
    def BodyPartsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # ResetResponse
    def BodyPartsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ResetResponse
    def BodyPartsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # gives the time in seconds passed since the start of the reset
    # is 0 when status == FINISHED
    # starts at 0
    # ResetResponse
    def Progress(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ResetResponse
    def Duration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ResetResponseStart(builder):
    builder.StartObject(5)

def Start(builder):
    ResetResponseStart(builder)

def ResetResponseAddResetType(builder, resetType):
    builder.PrependUint8Slot(0, resetType, 0)

def AddResetType(builder, resetType):
    ResetResponseAddResetType(builder, resetType)

def ResetResponseAddStatus(builder, status):
    builder.PrependUint8Slot(1, status, 0)

def AddStatus(builder, status):
    ResetResponseAddStatus(builder, status)

def ResetResponseAddBodyParts(builder, bodyParts):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(bodyParts), 0)

def AddBodyParts(builder, bodyParts):
    ResetResponseAddBodyParts(builder, bodyParts)

def ResetResponseStartBodyPartsVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartBodyPartsVector(builder, numElems):
    return ResetResponseStartBodyPartsVector(builder, numElems)

def ResetResponseAddProgress(builder, progress):
    builder.PrependInt32Slot(3, progress, 0)

def AddProgress(builder, progress):
    ResetResponseAddProgress(builder, progress)

def ResetResponseAddDuration(builder, duration):
    builder.PrependInt32Slot(4, duration, 0)

def AddDuration(builder, duration):
    ResetResponseAddDuration(builder, duration)

def ResetResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return ResetResponseEnd(builder)

try:
    from typing import List
except:
    pass

class ResetResponseT(object):

    # ResetResponseT
    def __init__(
        self,
        resetType = 0,
        status = 0,
        bodyParts = None,
        progress = 0,
        duration = 0,
    ):
        self.resetType = resetType  # type: int
        self.status = status  # type: int
        self.bodyParts = bodyParts  # type: Optional[List[int]]
        self.progress = progress  # type: int
        self.duration = duration  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        resetResponse = ResetResponse()
        resetResponse.Init(buf, pos)
        return cls.InitFromObj(resetResponse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, resetResponse):
        x = ResetResponseT()
        x._UnPack(resetResponse)
        return x

    # ResetResponseT
    def _UnPack(self, resetResponse):
        if resetResponse is None:
            return
        self.resetType = resetResponse.ResetType()
        self.status = resetResponse.Status()
        if not resetResponse.BodyPartsIsNone():
            if np is None:
                self.bodyParts = []
                for i in range(resetResponse.BodyPartsLength()):
                    self.bodyParts.append(resetResponse.BodyParts(i))
            else:
                self.bodyParts = resetResponse.BodyPartsAsNumpy()
        self.progress = resetResponse.Progress()
        self.duration = resetResponse.Duration()

    # ResetResponseT
    def Pack(self, builder):
        if self.bodyParts is not None:
            if np is not None and type(self.bodyParts) is np.ndarray:
                bodyParts = builder.CreateNumpyVector(self.bodyParts)
            else:
                ResetResponseStartBodyPartsVector(builder, len(self.bodyParts))
                for i in reversed(range(len(self.bodyParts))):
                    builder.PrependUint8(self.bodyParts[i])
                bodyParts = builder.EndVector()
        ResetResponseStart(builder)
        ResetResponseAddResetType(builder, self.resetType)
        ResetResponseAddStatus(builder, self.status)
        if self.bodyParts is not None:
            ResetResponseAddBodyParts(builder, bodyParts)
        ResetResponseAddProgress(builder, self.progress)
        ResetResponseAddDuration(builder, self.duration)
        resetResponse = ResetResponseEnd(builder)
        return resetResponse
