# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ResetsSettings(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ResetsSettings()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResetsSettings(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ResetsSettings
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ResetsSettings
    def ResetMountingFeet(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ResetsSettings
    def ArmsMountingResetMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ResetsSettings
    def YawResetSmoothTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ResetsSettings
    def SaveMountingReset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ResetsSettings
    def ResetHmdPitch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def ResetsSettingsStart(builder):
    builder.StartObject(5)

def Start(builder):
    ResetsSettingsStart(builder)

def ResetsSettingsAddResetMountingFeet(builder, resetMountingFeet):
    builder.PrependBoolSlot(0, resetMountingFeet, 0)

def AddResetMountingFeet(builder, resetMountingFeet):
    ResetsSettingsAddResetMountingFeet(builder, resetMountingFeet)

def ResetsSettingsAddArmsMountingResetMode(builder, armsMountingResetMode):
    builder.PrependUint8Slot(1, armsMountingResetMode, 0)

def AddArmsMountingResetMode(builder, armsMountingResetMode):
    ResetsSettingsAddArmsMountingResetMode(builder, armsMountingResetMode)

def ResetsSettingsAddYawResetSmoothTime(builder, yawResetSmoothTime):
    builder.PrependFloat32Slot(2, yawResetSmoothTime, 0.0)

def AddYawResetSmoothTime(builder, yawResetSmoothTime):
    ResetsSettingsAddYawResetSmoothTime(builder, yawResetSmoothTime)

def ResetsSettingsAddSaveMountingReset(builder, saveMountingReset):
    builder.PrependBoolSlot(3, saveMountingReset, 0)

def AddSaveMountingReset(builder, saveMountingReset):
    ResetsSettingsAddSaveMountingReset(builder, saveMountingReset)

def ResetsSettingsAddResetHmdPitch(builder, resetHmdPitch):
    builder.PrependBoolSlot(4, resetHmdPitch, 0)

def AddResetHmdPitch(builder, resetHmdPitch):
    ResetsSettingsAddResetHmdPitch(builder, resetHmdPitch)

def ResetsSettingsEnd(builder):
    return builder.EndObject()

def End(builder):
    return ResetsSettingsEnd(builder)


class ResetsSettingsT(object):

    # ResetsSettingsT
    def __init__(
        self,
        resetMountingFeet = False,
        armsMountingResetMode = 0,
        yawResetSmoothTime = 0.0,
        saveMountingReset = False,
        resetHmdPitch = False,
    ):
        self.resetMountingFeet = resetMountingFeet  # type: bool
        self.armsMountingResetMode = armsMountingResetMode  # type: int
        self.yawResetSmoothTime = yawResetSmoothTime  # type: float
        self.saveMountingReset = saveMountingReset  # type: bool
        self.resetHmdPitch = resetHmdPitch  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        resetsSettings = ResetsSettings()
        resetsSettings.Init(buf, pos)
        return cls.InitFromObj(resetsSettings)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, resetsSettings):
        x = ResetsSettingsT()
        x._UnPack(resetsSettings)
        return x

    # ResetsSettingsT
    def _UnPack(self, resetsSettings):
        if resetsSettings is None:
            return
        self.resetMountingFeet = resetsSettings.ResetMountingFeet()
        self.armsMountingResetMode = resetsSettings.ArmsMountingResetMode()
        self.yawResetSmoothTime = resetsSettings.YawResetSmoothTime()
        self.saveMountingReset = resetsSettings.SaveMountingReset()
        self.resetHmdPitch = resetsSettings.ResetHmdPitch()

    # ResetsSettingsT
    def Pack(self, builder):
        ResetsSettingsStart(builder)
        ResetsSettingsAddResetMountingFeet(builder, self.resetMountingFeet)
        ResetsSettingsAddArmsMountingResetMode(builder, self.armsMountingResetMode)
        ResetsSettingsAddYawResetSmoothTime(builder, self.yawResetSmoothTime)
        ResetsSettingsAddSaveMountingReset(builder, self.saveMountingReset)
        ResetsSettingsAddResetHmdPitch(builder, self.resetHmdPitch)
        resetsSettings = ResetsSettingsEnd(builder)
        return resetsSettings
