# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

class ResetType(object):
    Yaw = 0
    Full = 1
    # Second pose for calibrating mounting rotation
    Mounting = 2
