# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.rpc.SerialDevice import SerialDeviceT
from solarxr_protocol.rpc.SerialDevice import SerialDevice

class SerialUpdateResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SerialUpdateResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSerialUpdateResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SerialUpdateResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SerialUpdateResponse
    def Log(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SerialUpdateResponse
    def Closed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # SerialUpdateResponse
    def Device(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = SerialDevice()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def SerialUpdateResponseStart(builder):
    builder.StartObject(3)

def Start(builder):
    SerialUpdateResponseStart(builder)

def SerialUpdateResponseAddLog(builder, log):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(log), 0)

def AddLog(builder, log):
    SerialUpdateResponseAddLog(builder, log)

def SerialUpdateResponseAddClosed(builder, closed):
    builder.PrependBoolSlot(1, closed, 0)

def AddClosed(builder, closed):
    SerialUpdateResponseAddClosed(builder, closed)

def SerialUpdateResponseAddDevice(builder, device):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(device), 0)

def AddDevice(builder, device):
    SerialUpdateResponseAddDevice(builder, device)

def SerialUpdateResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return SerialUpdateResponseEnd(builder)

try:
    from typing import Optional
except:
    pass

class SerialUpdateResponseT(object):

    # SerialUpdateResponseT
    def __init__(
        self,
        log = None,
        closed = False,
        device = None,
    ):
        self.log = log  # type: Optional[str]
        self.closed = closed  # type: bool
        self.device = device  # type: Optional[SerialDeviceT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        serialUpdateResponse = SerialUpdateResponse()
        serialUpdateResponse.Init(buf, pos)
        return cls.InitFromObj(serialUpdateResponse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, serialUpdateResponse):
        x = SerialUpdateResponseT()
        x._UnPack(serialUpdateResponse)
        return x

    # SerialUpdateResponseT
    def _UnPack(self, serialUpdateResponse):
        if serialUpdateResponse is None:
            return
        self.log = serialUpdateResponse.Log()
        self.closed = serialUpdateResponse.Closed()
        if serialUpdateResponse.Device() is not None:
            self.device = SerialDeviceT.InitFromObj(serialUpdateResponse.Device())

    # SerialUpdateResponseT
    def Pack(self, builder):
        if self.log is not None:
            log = builder.CreateString(self.log)
        if self.device is not None:
            device = self.device.Pack(builder)
        SerialUpdateResponseStart(builder)
        if self.log is not None:
            SerialUpdateResponseAddLog(builder, log)
        SerialUpdateResponseAddClosed(builder, self.closed)
        if self.device is not None:
            SerialUpdateResponseAddDevice(builder, device)
        serialUpdateResponse = SerialUpdateResponseEnd(builder)
        return serialUpdateResponse
