# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SerialDevicePort(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SerialDevicePort()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSerialDevicePort(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SerialDevicePort
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SerialDevicePort
    def Port(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SerialDevicePortStart(builder):
    builder.StartObject(1)

def Start(builder):
    SerialDevicePortStart(builder)

def SerialDevicePortAddPort(builder, port):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(port), 0)

def AddPort(builder, port):
    SerialDevicePortAddPort(builder, port)

def SerialDevicePortEnd(builder):
    return builder.EndObject()

def End(builder):
    return SerialDevicePortEnd(builder)


class SerialDevicePortT(object):

    # SerialDevicePortT
    def __init__(
        self,
        port = None,
    ):
        self.port = port  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        serialDevicePort = SerialDevicePort()
        serialDevicePort.Init(buf, pos)
        return cls.InitFromObj(serialDevicePort)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, serialDevicePort):
        x = SerialDevicePortT()
        x._UnPack(serialDevicePort)
        return x

    # SerialDevicePortT
    def _UnPack(self, serialDevicePort):
        if serialDevicePort is None:
            return
        self.port = serialDevicePort.Port()

    # SerialDevicePortT
    def Pack(self, builder):
        if self.port is not None:
            port = builder.CreateString(self.port)
        SerialDevicePortStart(builder)
        if self.port is not None:
            SerialDevicePortAddPort(builder, port)
        serialDevicePort = SerialDevicePortEnd(builder)
        return serialDevicePort
