# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SerialDevicesRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SerialDevicesRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSerialDevicesRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SerialDevicesRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def SerialDevicesRequestStart(builder):
    builder.StartObject(0)

def Start(builder):
    SerialDevicesRequestStart(builder)

def SerialDevicesRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return SerialDevicesRequestEnd(builder)


class SerialDevicesRequestT(object):

    # SerialDevicesRequestT
    def __init__(
        self,
    ):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        serialDevicesRequest = SerialDevicesRequest()
        serialDevicesRequest.Init(buf, pos)
        return cls.InitFromObj(serialDevicesRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, serialDevicesRequest):
        x = SerialDevicesRequestT()
        x._UnPack(serialDevicesRequest)
        return x

    # SerialDevicesRequestT
    def _UnPack(self, serialDevicesRequest):
        if serialDevicesRequest is None:
            return

    # SerialDevicesRequestT
    def Pack(self, builder):
        SerialDevicesRequestStart(builder)
        serialDevicesRequest = SerialDevicesRequestEnd(builder)
        return serialDevicesRequest
