# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Reboots the tracker connected to the serial monitor
class SerialTrackerRebootRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SerialTrackerRebootRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSerialTrackerRebootRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SerialTrackerRebootRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def SerialTrackerRebootRequestStart(builder):
    builder.StartObject(0)

def Start(builder):
    SerialTrackerRebootRequestStart(builder)

def SerialTrackerRebootRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return SerialTrackerRebootRequestEnd(builder)


class SerialTrackerRebootRequestT(object):

    # SerialTrackerRebootRequestT
    def __init__(
        self,
    ):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        serialTrackerRebootRequest = SerialTrackerRebootRequest()
        serialTrackerRebootRequest.Init(buf, pos)
        return cls.InitFromObj(serialTrackerRebootRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, serialTrackerRebootRequest):
        x = SerialTrackerRebootRequestT()
        x._UnPack(serialTrackerRebootRequest)
        return x

    # SerialTrackerRebootRequestT
    def _UnPack(self, serialTrackerRebootRequest):
        if serialTrackerRebootRequest is None:
            return

    # SerialTrackerRebootRequestT
    def Pack(self, builder):
        SerialTrackerRebootRequestStart(builder)
        serialTrackerRebootRequest = SerialTrackerRebootRequestEnd(builder)
        return serialTrackerRebootRequest
