# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Sends a custom cmd to the currently connected Tracker over the Serial Monitor
class SerialTrackerCustomCommandRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SerialTrackerCustomCommandRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSerialTrackerCustomCommandRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SerialTrackerCustomCommandRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SerialTrackerCustomCommandRequest
    def Command(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SerialTrackerCustomCommandRequestStart(builder):
    builder.StartObject(1)

def Start(builder):
    SerialTrackerCustomCommandRequestStart(builder)

def SerialTrackerCustomCommandRequestAddCommand(builder, command):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(command), 0)

def AddCommand(builder, command):
    SerialTrackerCustomCommandRequestAddCommand(builder, command)

def SerialTrackerCustomCommandRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return SerialTrackerCustomCommandRequestEnd(builder)


class SerialTrackerCustomCommandRequestT(object):

    # SerialTrackerCustomCommandRequestT
    def __init__(
        self,
        command = None,
    ):
        self.command = command  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        serialTrackerCustomCommandRequest = SerialTrackerCustomCommandRequest()
        serialTrackerCustomCommandRequest.Init(buf, pos)
        return cls.InitFromObj(serialTrackerCustomCommandRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, serialTrackerCustomCommandRequest):
        x = SerialTrackerCustomCommandRequestT()
        x._UnPack(serialTrackerCustomCommandRequest)
        return x

    # SerialTrackerCustomCommandRequestT
    def _UnPack(self, serialTrackerCustomCommandRequest):
        if serialTrackerCustomCommandRequest is None:
            return
        self.command = serialTrackerCustomCommandRequest.Command()

    # SerialTrackerCustomCommandRequestT
    def Pack(self, builder):
        if self.command is not None:
            command = builder.CreateString(self.command)
        SerialTrackerCustomCommandRequestStart(builder)
        if self.command is not None:
            SerialTrackerCustomCommandRequestAddCommand(builder, command)
        serialTrackerCustomCommandRequest = SerialTrackerCustomCommandRequestEnd(builder)
        return serialTrackerCustomCommandRequest
