# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Sends the GET INFO cmd to the current tracker on the serial monitor
class SerialTrackerGetInfoRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SerialTrackerGetInfoRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSerialTrackerGetInfoRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SerialTrackerGetInfoRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def SerialTrackerGetInfoRequestStart(builder):
    builder.StartObject(0)

def Start(builder):
    SerialTrackerGetInfoRequestStart(builder)

def SerialTrackerGetInfoRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return SerialTrackerGetInfoRequestEnd(builder)


class SerialTrackerGetInfoRequestT(object):

    # SerialTrackerGetInfoRequestT
    def __init__(
        self,
    ):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        serialTrackerGetInfoRequest = SerialTrackerGetInfoRequest()
        serialTrackerGetInfoRequest.Init(buf, pos)
        return cls.InitFromObj(serialTrackerGetInfoRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, serialTrackerGetInfoRequest):
        x = SerialTrackerGetInfoRequestT()
        x._UnPack(serialTrackerGetInfoRequest)
        return x

    # SerialTrackerGetInfoRequestT
    def _UnPack(self, serialTrackerGetInfoRequest):
        if serialTrackerGetInfoRequest is None:
            return

    # SerialTrackerGetInfoRequestT
    def Pack(self, builder):
        SerialTrackerGetInfoRequestStart(builder)
        serialTrackerGetInfoRequest = SerialTrackerGetInfoRequestEnd(builder)
        return serialTrackerGetInfoRequest
