# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Holds the Server information, this is a basic table holding various information about the currently running server
# like its local ip address (useful for standalone users so they can specify the ip of the server more easily) and any more
# infos we might want to add in the future. (like java version, working dir, server version ....)
# This only holds the local ip for now. But there will be other information added as we chose to display them on the gui for instance
class ServerInfosResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ServerInfosResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsServerInfosResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ServerInfosResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ServerInfosResponse
    def LocalIp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ServerInfosResponseStart(builder):
    builder.StartObject(1)

def Start(builder):
    ServerInfosResponseStart(builder)

def ServerInfosResponseAddLocalIp(builder, localIp):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(localIp), 0)

def AddLocalIp(builder, localIp):
    ServerInfosResponseAddLocalIp(builder, localIp)

def ServerInfosResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return ServerInfosResponseEnd(builder)


class ServerInfosResponseT(object):

    # ServerInfosResponseT
    def __init__(
        self,
        localIp = None,
    ):
        self.localIp = localIp  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        serverInfosResponse = ServerInfosResponse()
        serverInfosResponse.Init(buf, pos)
        return cls.InitFromObj(serverInfosResponse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, serverInfosResponse):
        x = ServerInfosResponseT()
        x._UnPack(serverInfosResponse)
        return x

    # ServerInfosResponseT
    def _UnPack(self, serverInfosResponse):
        if serverInfosResponse is None:
            return
        self.localIp = serverInfosResponse.LocalIp()

    # ServerInfosResponseT
    def Pack(self, builder):
        if self.localIp is not None:
            localIp = builder.CreateString(self.localIp)
        ServerInfosResponseStart(builder)
        if self.localIp is not None:
            ServerInfosResponseAddLocalIp(builder, localIp)
        serverInfosResponse = ServerInfosResponseEnd(builder)
        return serverInfosResponse
