# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetPauseTrackingRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetPauseTrackingRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetPauseTrackingRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetPauseTrackingRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Pauses skeleton tracking if true, resumes skeleton tracking if false.
    # SetPauseTrackingRequest
    def PauseTracking(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def SetPauseTrackingRequestStart(builder):
    builder.StartObject(1)

def Start(builder):
    SetPauseTrackingRequestStart(builder)

def SetPauseTrackingRequestAddPauseTracking(builder, pauseTracking):
    builder.PrependBoolSlot(0, pauseTracking, 0)

def AddPauseTracking(builder, pauseTracking):
    SetPauseTrackingRequestAddPauseTracking(builder, pauseTracking)

def SetPauseTrackingRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return SetPauseTrackingRequestEnd(builder)


class SetPauseTrackingRequestT(object):

    # SetPauseTrackingRequestT
    def __init__(
        self,
        pauseTracking = False,
    ):
        self.pauseTracking = pauseTracking  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        setPauseTrackingRequest = SetPauseTrackingRequest()
        setPauseTrackingRequest.Init(buf, pos)
        return cls.InitFromObj(setPauseTrackingRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, setPauseTrackingRequest):
        x = SetPauseTrackingRequestT()
        x._UnPack(setPauseTrackingRequest)
        return x

    # SetPauseTrackingRequestT
    def _UnPack(self, setPauseTrackingRequest):
        if setPauseTrackingRequest is None:
            return
        self.pauseTracking = setPauseTrackingRequest.PauseTracking()

    # SetPauseTrackingRequestT
    def Pack(self, builder):
        SetPauseTrackingRequestStart(builder)
        SetPauseTrackingRequestAddPauseTracking(builder, self.pauseTracking)
        setPauseTrackingRequest = SetPauseTrackingRequestEnd(builder)
        return setPauseTrackingRequest
