# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SettingsRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SettingsRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSettingsRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SettingsRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def SettingsRequestStart(builder):
    builder.StartObject(0)

def Start(builder):
    SettingsRequestStart(builder)

def SettingsRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return SettingsRequestEnd(builder)


class SettingsRequestT(object):

    # SettingsRequestT
    def __init__(
        self,
    ):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        settingsRequest = SettingsRequest()
        settingsRequest.Init(buf, pos)
        return cls.InitFromObj(settingsRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, settingsRequest):
        x = SettingsRequestT()
        x._UnPack(settingsRequest)
        return x

    # SettingsRequestT
    def _UnPack(self, settingsRequest):
        if settingsRequest is None:
            return

    # SettingsRequestT
    def Pack(self, builder):
        SettingsRequestStart(builder)
        settingsRequest = SettingsRequestEnd(builder)
        return settingsRequest
