# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetWifiRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetWifiRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetWifiRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetWifiRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetWifiRequest
    def Ssid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SetWifiRequest
    def Password(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SetWifiRequestStart(builder):
    builder.StartObject(2)

def Start(builder):
    SetWifiRequestStart(builder)

def SetWifiRequestAddSsid(builder, ssid):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(ssid), 0)

def AddSsid(builder, ssid):
    SetWifiRequestAddSsid(builder, ssid)

def SetWifiRequestAddPassword(builder, password):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(password), 0)

def AddPassword(builder, password):
    SetWifiRequestAddPassword(builder, password)

def SetWifiRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return SetWifiRequestEnd(builder)


class SetWifiRequestT(object):

    # SetWifiRequestT
    def __init__(
        self,
        ssid = None,
        password = None,
    ):
        self.ssid = ssid  # type: Optional[str]
        self.password = password  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        setWifiRequest = SetWifiRequest()
        setWifiRequest.Init(buf, pos)
        return cls.InitFromObj(setWifiRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, setWifiRequest):
        x = SetWifiRequestT()
        x._UnPack(setWifiRequest)
        return x

    # SetWifiRequestT
    def _UnPack(self, setWifiRequest):
        if setWifiRequest is None:
            return
        self.ssid = setWifiRequest.Ssid()
        self.password = setWifiRequest.Password()

    # SetWifiRequestT
    def Pack(self, builder):
        if self.ssid is not None:
            ssid = builder.CreateString(self.ssid)
        if self.password is not None:
            password = builder.CreateString(self.password)
        SetWifiRequestStart(builder)
        if self.ssid is not None:
            SetWifiRequestAddSsid(builder, ssid)
        if self.password is not None:
            SetWifiRequestAddPassword(builder, password)
        setWifiRequest = SetWifiRequestEnd(builder)
        return setWifiRequest
