# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SkeletonPart(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SkeletonPart()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSkeletonPart(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SkeletonPart
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SkeletonPart
    def Bone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # SkeletonPart
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def SkeletonPartStart(builder):
    builder.StartObject(2)

def Start(builder):
    SkeletonPartStart(builder)

def SkeletonPartAddBone(builder, bone):
    builder.PrependUint8Slot(0, bone, 0)

def AddBone(builder, bone):
    SkeletonPartAddBone(builder, bone)

def SkeletonPartAddValue(builder, value):
    builder.PrependFloat32Slot(1, value, 0.0)

def AddValue(builder, value):
    SkeletonPartAddValue(builder, value)

def SkeletonPartEnd(builder):
    return builder.EndObject()

def End(builder):
    return SkeletonPartEnd(builder)


class SkeletonPartT(object):

    # SkeletonPartT
    def __init__(
        self,
        bone = 0,
        value = 0.0,
    ):
        self.bone = bone  # type: int
        self.value = value  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        skeletonPart = SkeletonPart()
        skeletonPart.Init(buf, pos)
        return cls.InitFromObj(skeletonPart)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, skeletonPart):
        x = SkeletonPartT()
        x._UnPack(skeletonPart)
        return x

    # SkeletonPartT
    def _UnPack(self, skeletonPart):
        if skeletonPart is None:
            return
        self.bone = skeletonPart.Bone()
        self.value = skeletonPart.Value()

    # SkeletonPartT
    def Pack(self, builder):
        SkeletonPartStart(builder)
        SkeletonPartAddBone(builder, self.bone)
        SkeletonPartAddValue(builder, self.value)
        skeletonPart = SkeletonPartEnd(builder)
        return skeletonPart
