# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StartWifiProvisioningRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StartWifiProvisioningRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStartWifiProvisioningRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StartWifiProvisioningRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StartWifiProvisioningRequest
    def Ssid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StartWifiProvisioningRequest
    def Password(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StartWifiProvisioningRequest
    def Port(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def StartWifiProvisioningRequestStart(builder):
    builder.StartObject(3)

def Start(builder):
    StartWifiProvisioningRequestStart(builder)

def StartWifiProvisioningRequestAddSsid(builder, ssid):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(ssid), 0)

def AddSsid(builder, ssid):
    StartWifiProvisioningRequestAddSsid(builder, ssid)

def StartWifiProvisioningRequestAddPassword(builder, password):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(password), 0)

def AddPassword(builder, password):
    StartWifiProvisioningRequestAddPassword(builder, password)

def StartWifiProvisioningRequestAddPort(builder, port):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(port), 0)

def AddPort(builder, port):
    StartWifiProvisioningRequestAddPort(builder, port)

def StartWifiProvisioningRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return StartWifiProvisioningRequestEnd(builder)


class StartWifiProvisioningRequestT(object):

    # StartWifiProvisioningRequestT
    def __init__(
        self,
        ssid = None,
        password = None,
        port = None,
    ):
        self.ssid = ssid  # type: Optional[str]
        self.password = password  # type: Optional[str]
        self.port = port  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        startWifiProvisioningRequest = StartWifiProvisioningRequest()
        startWifiProvisioningRequest.Init(buf, pos)
        return cls.InitFromObj(startWifiProvisioningRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, startWifiProvisioningRequest):
        x = StartWifiProvisioningRequestT()
        x._UnPack(startWifiProvisioningRequest)
        return x

    # StartWifiProvisioningRequestT
    def _UnPack(self, startWifiProvisioningRequest):
        if startWifiProvisioningRequest is None:
            return
        self.ssid = startWifiProvisioningRequest.Ssid()
        self.password = startWifiProvisioningRequest.Password()
        self.port = startWifiProvisioningRequest.Port()

    # StartWifiProvisioningRequestT
    def Pack(self, builder):
        if self.ssid is not None:
            ssid = builder.CreateString(self.ssid)
        if self.password is not None:
            password = builder.CreateString(self.password)
        if self.port is not None:
            port = builder.CreateString(self.port)
        StartWifiProvisioningRequestStart(builder)
        if self.ssid is not None:
            StartWifiProvisioningRequestAddSsid(builder, ssid)
        if self.password is not None:
            StartWifiProvisioningRequestAddPassword(builder, password)
        if self.port is not None:
            StartWifiProvisioningRequestAddPort(builder, port)
        startWifiProvisioningRequest = StartWifiProvisioningRequestEnd(builder)
        return startWifiProvisioningRequest
