# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# When an status is fixed and it's removed, it's ID is sent
class StatusSystemFixed(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StatusSystemFixed()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStatusSystemFixed(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StatusSystemFixed
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StatusSystemFixed
    def FixedStatusId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def StatusSystemFixedStart(builder):
    builder.StartObject(1)

def Start(builder):
    StatusSystemFixedStart(builder)

def StatusSystemFixedAddFixedStatusId(builder, fixedStatusId):
    builder.PrependUint32Slot(0, fixedStatusId, 0)

def AddFixedStatusId(builder, fixedStatusId):
    StatusSystemFixedAddFixedStatusId(builder, fixedStatusId)

def StatusSystemFixedEnd(builder):
    return builder.EndObject()

def End(builder):
    return StatusSystemFixedEnd(builder)


class StatusSystemFixedT(object):

    # StatusSystemFixedT
    def __init__(
        self,
        fixedStatusId = 0,
    ):
        self.fixedStatusId = fixedStatusId  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        statusSystemFixed = StatusSystemFixed()
        statusSystemFixed.Init(buf, pos)
        return cls.InitFromObj(statusSystemFixed)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, statusSystemFixed):
        x = StatusSystemFixedT()
        x._UnPack(statusSystemFixed)
        return x

    # StatusSystemFixedT
    def _UnPack(self, statusSystemFixed):
        if statusSystemFixed is None:
            return
        self.fixedStatusId = statusSystemFixed.FixedStatusId()

    # StatusSystemFixedT
    def Pack(self, builder):
        StatusSystemFixedStart(builder)
        StatusSystemFixedAddFixedStatusId(builder, self.fixedStatusId)
        statusSystemFixed = StatusSystemFixedEnd(builder)
        return statusSystemFixed
