from solarxr_protocol.rpc.StatusPublicNetwork import StatusPublicNetworkT
from solarxr_protocol.rpc.StatusSteamVRDisconnected import StatusSteamVRDisconnectedT
from solarxr_protocol.rpc.StatusTrackerError import StatusTrackerErrorT
from solarxr_protocol.rpc.StatusTrackerReset import StatusTrackerResetT
from solarxr_protocol.rpc.StatusUnassignedHMD import StatusUnassignedHMDT
# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

class StatusData(object):
    NONE = 0
    StatusTrackerReset = 1
    StatusTrackerError = 2
    StatusSteamVRDisconnected = 3
    StatusUnassignedHMD = 4
    StatusPublicNetwork = 5

def StatusDataCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == StatusData.StatusTrackerReset:
        return StatusTrackerResetT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == StatusData.StatusTrackerError:
        return StatusTrackerErrorT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == StatusData.StatusSteamVRDisconnected:
        return StatusSteamVRDisconnectedT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == StatusData.StatusUnassignedHMD:
        return StatusUnassignedHMDT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == StatusData.StatusPublicNetwork:
        return StatusPublicNetworkT.InitFromBuf(table.Bytes, table.Pos)
    return None
