# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.rpc.StatusMessage import StatusMessageT
from solarxr_protocol.rpc.StatusMessage import StatusMessage

# When a new status appears, it's sent alone
class StatusSystemUpdate(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StatusSystemUpdate()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStatusSystemUpdate(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StatusSystemUpdate
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StatusSystemUpdate
    def NewStatus(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = StatusMessage()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def StatusSystemUpdateStart(builder):
    builder.StartObject(1)

def Start(builder):
    StatusSystemUpdateStart(builder)

def StatusSystemUpdateAddNewStatus(builder, newStatus):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(newStatus), 0)

def AddNewStatus(builder, newStatus):
    StatusSystemUpdateAddNewStatus(builder, newStatus)

def StatusSystemUpdateEnd(builder):
    return builder.EndObject()

def End(builder):
    return StatusSystemUpdateEnd(builder)

try:
    from typing import Optional
except:
    pass

class StatusSystemUpdateT(object):

    # StatusSystemUpdateT
    def __init__(
        self,
        newStatus = None,
    ):
        self.newStatus = newStatus  # type: Optional[StatusMessageT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        statusSystemUpdate = StatusSystemUpdate()
        statusSystemUpdate.Init(buf, pos)
        return cls.InitFromObj(statusSystemUpdate)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, statusSystemUpdate):
        x = StatusSystemUpdateT()
        x._UnPack(statusSystemUpdate)
        return x

    # StatusSystemUpdateT
    def _UnPack(self, statusSystemUpdate):
        if statusSystemUpdate is None:
            return
        if statusSystemUpdate.NewStatus() is not None:
            self.newStatus = StatusMessageT.InitFromObj(statusSystemUpdate.NewStatus())

    # StatusSystemUpdateT
    def Pack(self, builder):
        if self.newStatus is not None:
            newStatus = self.newStatus.Pack(builder)
        StatusSystemUpdateStart(builder)
        if self.newStatus is not None:
            StatusSystemUpdateAddNewStatus(builder, newStatus)
        statusSystemUpdate = StatusSystemUpdateEnd(builder)
        return statusSystemUpdate
