# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.datatypes.TrackerId import TrackerIdT
from solarxr_protocol.datatypes.TrackerId import TrackerId

# Tracker requires full reset
class StatusTrackerReset(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StatusTrackerReset()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStatusTrackerReset(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StatusTrackerReset
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StatusTrackerReset
    def TrackerId(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = TrackerId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StatusTrackerReset
    def TrackerIdLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StatusTrackerReset
    def TrackerIdIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def StatusTrackerResetStart(builder):
    builder.StartObject(1)

def Start(builder):
    StatusTrackerResetStart(builder)

def StatusTrackerResetAddTrackerId(builder, trackerId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(trackerId), 0)

def AddTrackerId(builder, trackerId):
    StatusTrackerResetAddTrackerId(builder, trackerId)

def StatusTrackerResetStartTrackerIdVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTrackerIdVector(builder, numElems):
    return StatusTrackerResetStartTrackerIdVector(builder, numElems)

def StatusTrackerResetEnd(builder):
    return builder.EndObject()

def End(builder):
    return StatusTrackerResetEnd(builder)

try:
    from typing import List
except:
    pass

class StatusTrackerResetT(object):

    # StatusTrackerResetT
    def __init__(
        self,
        trackerId = None,
    ):
        self.trackerId = trackerId  # type: Optional[List[TrackerIdT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        statusTrackerReset = StatusTrackerReset()
        statusTrackerReset.Init(buf, pos)
        return cls.InitFromObj(statusTrackerReset)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, statusTrackerReset):
        x = StatusTrackerResetT()
        x._UnPack(statusTrackerReset)
        return x

    # StatusTrackerResetT
    def _UnPack(self, statusTrackerReset):
        if statusTrackerReset is None:
            return
        if not statusTrackerReset.TrackerIdIsNone():
            self.trackerId = []
            for i in range(statusTrackerReset.TrackerIdLength()):
                if statusTrackerReset.TrackerId(i) is None:
                    self.trackerId.append(None)
                else:
                    trackerId_ = TrackerIdT.InitFromObj(statusTrackerReset.TrackerId(i))
                    self.trackerId.append(trackerId_)

    # StatusTrackerResetT
    def Pack(self, builder):
        if self.trackerId is not None:
            trackerIdlist = []
            for i in range(len(self.trackerId)):
                trackerIdlist.append(self.trackerId[i].Pack(builder))
            StatusTrackerResetStartTrackerIdVector(builder, len(self.trackerId))
            for i in reversed(range(len(self.trackerId))):
                builder.PrependUOffsetTRelative(trackerIdlist[i])
            trackerId = builder.EndVector()
        StatusTrackerResetStart(builder)
        if self.trackerId is not None:
            StatusTrackerResetAddTrackerId(builder, trackerId)
        statusTrackerReset = StatusTrackerResetEnd(builder)
        return statusTrackerReset
