# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.datatypes.TrackerId import TrackerIdT
from solarxr_protocol.datatypes.TrackerId import TrackerId

# There is an available HMD tracker and it's not assigned to head
class StatusUnassignedHMD(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StatusUnassignedHMD()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStatusUnassignedHMD(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StatusUnassignedHMD
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StatusUnassignedHMD
    def TrackerId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = TrackerId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def StatusUnassignedHMDStart(builder):
    builder.StartObject(1)

def Start(builder):
    StatusUnassignedHMDStart(builder)

def StatusUnassignedHMDAddTrackerId(builder, trackerId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(trackerId), 0)

def AddTrackerId(builder, trackerId):
    StatusUnassignedHMDAddTrackerId(builder, trackerId)

def StatusUnassignedHMDEnd(builder):
    return builder.EndObject()

def End(builder):
    return StatusUnassignedHMDEnd(builder)

try:
    from typing import Optional
except:
    pass

class StatusUnassignedHMDT(object):

    # StatusUnassignedHMDT
    def __init__(
        self,
        trackerId = None,
    ):
        self.trackerId = trackerId  # type: Optional[TrackerIdT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        statusUnassignedHmd = StatusUnassignedHMD()
        statusUnassignedHmd.Init(buf, pos)
        return cls.InitFromObj(statusUnassignedHmd)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, statusUnassignedHmd):
        x = StatusUnassignedHMDT()
        x._UnPack(statusUnassignedHmd)
        return x

    # StatusUnassignedHMDT
    def _UnPack(self, statusUnassignedHmd):
        if statusUnassignedHmd is None:
            return
        if statusUnassignedHmd.TrackerId() is not None:
            self.trackerId = TrackerIdT.InitFromObj(statusUnassignedHmd.TrackerId())

    # StatusUnassignedHMDT
    def Pack(self, builder):
        if self.trackerId is not None:
            trackerId = self.trackerId.Pack(builder)
        StatusUnassignedHMDStart(builder)
        if self.trackerId is not None:
            StatusUnassignedHMDAddTrackerId(builder, trackerId)
        statusUnassignedHmd = StatusUnassignedHMDEnd(builder)
        return statusUnassignedHmd
