# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StopWifiProvisioningRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StopWifiProvisioningRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStopWifiProvisioningRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StopWifiProvisioningRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def StopWifiProvisioningRequestStart(builder):
    builder.StartObject(0)

def Start(builder):
    StopWifiProvisioningRequestStart(builder)

def StopWifiProvisioningRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return StopWifiProvisioningRequestEnd(builder)


class StopWifiProvisioningRequestT(object):

    # StopWifiProvisioningRequestT
    def __init__(
        self,
    ):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        stopWifiProvisioningRequest = StopWifiProvisioningRequest()
        stopWifiProvisioningRequest.Init(buf, pos)
        return cls.InitFromObj(stopWifiProvisioningRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, stopWifiProvisioningRequest):
        x = StopWifiProvisioningRequestT()
        x._UnPack(stopWifiProvisioningRequest)
        return x

    # StopWifiProvisioningRequestT
    def _UnPack(self, stopWifiProvisioningRequest):
        if stopWifiProvisioningRequest is None:
            return

    # StopWifiProvisioningRequestT
    def Pack(self, builder):
        StopWifiProvisioningRequestStart(builder)
        stopWifiProvisioningRequest = StopWifiProvisioningRequestEnd(builder)
        return stopWifiProvisioningRequest
