# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TapDetectionSettings(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TapDetectionSettings()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTapDetectionSettings(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TapDetectionSettings
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TapDetectionSettings
    def FullResetDelay(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return None

    # TapDetectionSettings
    def FullResetEnabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return None

    # TapDetectionSettings
    def FullResetTaps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return None

    # TapDetectionSettings
    def YawResetDelay(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return None

    # TapDetectionSettings
    def YawResetEnabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return None

    # TapDetectionSettings
    def YawResetTaps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return None

    # TapDetectionSettings
    def MountingResetDelay(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return None

    # TapDetectionSettings
    def MountingResetEnabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return None

    # TapDetectionSettings
    def MountingResetTaps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return None

    # If true, disables reset behavior of tap detection and sends a
    # TapDetectionSetupNotification, each time 2 taps are detected on any tracker
    # TapDetectionSettings
    def SetupMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return None

    # TapDetectionSettings
    def NumberTrackersOverThreshold(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return None

    # TapDetectionSettings
    def YawResetTracker(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return None

    # TapDetectionSettings
    def FullResetTracker(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return None

    # TapDetectionSettings
    def MountingResetTracker(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return None

def TapDetectionSettingsStart(builder):
    builder.StartObject(14)

def Start(builder):
    TapDetectionSettingsStart(builder)

def TapDetectionSettingsAddFullResetDelay(builder, fullResetDelay):
    builder.PrependFloat32Slot(0, fullResetDelay, None)

def AddFullResetDelay(builder, fullResetDelay):
    TapDetectionSettingsAddFullResetDelay(builder, fullResetDelay)

def TapDetectionSettingsAddFullResetEnabled(builder, fullResetEnabled):
    builder.PrependBoolSlot(1, fullResetEnabled, None)

def AddFullResetEnabled(builder, fullResetEnabled):
    TapDetectionSettingsAddFullResetEnabled(builder, fullResetEnabled)

def TapDetectionSettingsAddFullResetTaps(builder, fullResetTaps):
    builder.PrependUint8Slot(2, fullResetTaps, None)

def AddFullResetTaps(builder, fullResetTaps):
    TapDetectionSettingsAddFullResetTaps(builder, fullResetTaps)

def TapDetectionSettingsAddYawResetDelay(builder, yawResetDelay):
    builder.PrependFloat32Slot(3, yawResetDelay, None)

def AddYawResetDelay(builder, yawResetDelay):
    TapDetectionSettingsAddYawResetDelay(builder, yawResetDelay)

def TapDetectionSettingsAddYawResetEnabled(builder, yawResetEnabled):
    builder.PrependBoolSlot(4, yawResetEnabled, None)

def AddYawResetEnabled(builder, yawResetEnabled):
    TapDetectionSettingsAddYawResetEnabled(builder, yawResetEnabled)

def TapDetectionSettingsAddYawResetTaps(builder, yawResetTaps):
    builder.PrependUint8Slot(5, yawResetTaps, None)

def AddYawResetTaps(builder, yawResetTaps):
    TapDetectionSettingsAddYawResetTaps(builder, yawResetTaps)

def TapDetectionSettingsAddMountingResetDelay(builder, mountingResetDelay):
    builder.PrependFloat32Slot(6, mountingResetDelay, None)

def AddMountingResetDelay(builder, mountingResetDelay):
    TapDetectionSettingsAddMountingResetDelay(builder, mountingResetDelay)

def TapDetectionSettingsAddMountingResetEnabled(builder, mountingResetEnabled):
    builder.PrependBoolSlot(7, mountingResetEnabled, None)

def AddMountingResetEnabled(builder, mountingResetEnabled):
    TapDetectionSettingsAddMountingResetEnabled(builder, mountingResetEnabled)

def TapDetectionSettingsAddMountingResetTaps(builder, mountingResetTaps):
    builder.PrependUint8Slot(8, mountingResetTaps, None)

def AddMountingResetTaps(builder, mountingResetTaps):
    TapDetectionSettingsAddMountingResetTaps(builder, mountingResetTaps)

def TapDetectionSettingsAddSetupMode(builder, setupMode):
    builder.PrependBoolSlot(9, setupMode, None)

def AddSetupMode(builder, setupMode):
    TapDetectionSettingsAddSetupMode(builder, setupMode)

def TapDetectionSettingsAddNumberTrackersOverThreshold(builder, numberTrackersOverThreshold):
    builder.PrependUint8Slot(10, numberTrackersOverThreshold, None)

def AddNumberTrackersOverThreshold(builder, numberTrackersOverThreshold):
    TapDetectionSettingsAddNumberTrackersOverThreshold(builder, numberTrackersOverThreshold)

def TapDetectionSettingsAddYawResetTracker(builder, yawResetTracker):
    builder.PrependUint8Slot(11, yawResetTracker, None)

def AddYawResetTracker(builder, yawResetTracker):
    TapDetectionSettingsAddYawResetTracker(builder, yawResetTracker)

def TapDetectionSettingsAddFullResetTracker(builder, fullResetTracker):
    builder.PrependUint8Slot(12, fullResetTracker, None)

def AddFullResetTracker(builder, fullResetTracker):
    TapDetectionSettingsAddFullResetTracker(builder, fullResetTracker)

def TapDetectionSettingsAddMountingResetTracker(builder, mountingResetTracker):
    builder.PrependUint8Slot(13, mountingResetTracker, None)

def AddMountingResetTracker(builder, mountingResetTracker):
    TapDetectionSettingsAddMountingResetTracker(builder, mountingResetTracker)

def TapDetectionSettingsEnd(builder):
    return builder.EndObject()

def End(builder):
    return TapDetectionSettingsEnd(builder)

try:
    from typing import Optional
except:
    pass

class TapDetectionSettingsT(object):

    # TapDetectionSettingsT
    def __init__(
        self,
        fullResetDelay = None,
        fullResetEnabled = None,
        fullResetTaps = None,
        yawResetDelay = None,
        yawResetEnabled = None,
        yawResetTaps = None,
        mountingResetDelay = None,
        mountingResetEnabled = None,
        mountingResetTaps = None,
        setupMode = None,
        numberTrackersOverThreshold = None,
        yawResetTracker = None,
        fullResetTracker = None,
        mountingResetTracker = None,
    ):
        self.fullResetDelay = fullResetDelay  # type: Optional[float]
        self.fullResetEnabled = fullResetEnabled  # type: Optional[bool]
        self.fullResetTaps = fullResetTaps  # type: Optional[int]
        self.yawResetDelay = yawResetDelay  # type: Optional[float]
        self.yawResetEnabled = yawResetEnabled  # type: Optional[bool]
        self.yawResetTaps = yawResetTaps  # type: Optional[int]
        self.mountingResetDelay = mountingResetDelay  # type: Optional[float]
        self.mountingResetEnabled = mountingResetEnabled  # type: Optional[bool]
        self.mountingResetTaps = mountingResetTaps  # type: Optional[int]
        self.setupMode = setupMode  # type: Optional[bool]
        self.numberTrackersOverThreshold = numberTrackersOverThreshold  # type: Optional[int]
        self.yawResetTracker = yawResetTracker  # type: Optional[int]
        self.fullResetTracker = fullResetTracker  # type: Optional[int]
        self.mountingResetTracker = mountingResetTracker  # type: Optional[int]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        tapDetectionSettings = TapDetectionSettings()
        tapDetectionSettings.Init(buf, pos)
        return cls.InitFromObj(tapDetectionSettings)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, tapDetectionSettings):
        x = TapDetectionSettingsT()
        x._UnPack(tapDetectionSettings)
        return x

    # TapDetectionSettingsT
    def _UnPack(self, tapDetectionSettings):
        if tapDetectionSettings is None:
            return
        self.fullResetDelay = tapDetectionSettings.FullResetDelay()
        self.fullResetEnabled = tapDetectionSettings.FullResetEnabled()
        self.fullResetTaps = tapDetectionSettings.FullResetTaps()
        self.yawResetDelay = tapDetectionSettings.YawResetDelay()
        self.yawResetEnabled = tapDetectionSettings.YawResetEnabled()
        self.yawResetTaps = tapDetectionSettings.YawResetTaps()
        self.mountingResetDelay = tapDetectionSettings.MountingResetDelay()
        self.mountingResetEnabled = tapDetectionSettings.MountingResetEnabled()
        self.mountingResetTaps = tapDetectionSettings.MountingResetTaps()
        self.setupMode = tapDetectionSettings.SetupMode()
        self.numberTrackersOverThreshold = tapDetectionSettings.NumberTrackersOverThreshold()
        self.yawResetTracker = tapDetectionSettings.YawResetTracker()
        self.fullResetTracker = tapDetectionSettings.FullResetTracker()
        self.mountingResetTracker = tapDetectionSettings.MountingResetTracker()

    # TapDetectionSettingsT
    def Pack(self, builder):
        TapDetectionSettingsStart(builder)
        TapDetectionSettingsAddFullResetDelay(builder, self.fullResetDelay)
        TapDetectionSettingsAddFullResetEnabled(builder, self.fullResetEnabled)
        TapDetectionSettingsAddFullResetTaps(builder, self.fullResetTaps)
        TapDetectionSettingsAddYawResetDelay(builder, self.yawResetDelay)
        TapDetectionSettingsAddYawResetEnabled(builder, self.yawResetEnabled)
        TapDetectionSettingsAddYawResetTaps(builder, self.yawResetTaps)
        TapDetectionSettingsAddMountingResetDelay(builder, self.mountingResetDelay)
        TapDetectionSettingsAddMountingResetEnabled(builder, self.mountingResetEnabled)
        TapDetectionSettingsAddMountingResetTaps(builder, self.mountingResetTaps)
        TapDetectionSettingsAddSetupMode(builder, self.setupMode)
        TapDetectionSettingsAddNumberTrackersOverThreshold(builder, self.numberTrackersOverThreshold)
        TapDetectionSettingsAddYawResetTracker(builder, self.yawResetTracker)
        TapDetectionSettingsAddFullResetTracker(builder, self.fullResetTracker)
        TapDetectionSettingsAddMountingResetTracker(builder, self.mountingResetTracker)
        tapDetectionSettings = TapDetectionSettingsEnd(builder)
        return tapDetectionSettings
