# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.datatypes.TrackerId import TrackerIdT
from solarxr_protocol.datatypes.TrackerId import TrackerId

# See TapDetectionSettings::setup_mode
class TapDetectionSetupNotification(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TapDetectionSetupNotification()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTapDetectionSetupNotification(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TapDetectionSetupNotification
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TapDetectionSetupNotification
    def TrackerId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = TrackerId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def TapDetectionSetupNotificationStart(builder):
    builder.StartObject(1)

def Start(builder):
    TapDetectionSetupNotificationStart(builder)

def TapDetectionSetupNotificationAddTrackerId(builder, trackerId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(trackerId), 0)

def AddTrackerId(builder, trackerId):
    TapDetectionSetupNotificationAddTrackerId(builder, trackerId)

def TapDetectionSetupNotificationEnd(builder):
    return builder.EndObject()

def End(builder):
    return TapDetectionSetupNotificationEnd(builder)

try:
    from typing import Optional
except:
    pass

class TapDetectionSetupNotificationT(object):

    # TapDetectionSetupNotificationT
    def __init__(
        self,
        trackerId = None,
    ):
        self.trackerId = trackerId  # type: Optional[TrackerIdT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        tapDetectionSetupNotification = TapDetectionSetupNotification()
        tapDetectionSetupNotification.Init(buf, pos)
        return cls.InitFromObj(tapDetectionSetupNotification)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, tapDetectionSetupNotification):
        x = TapDetectionSetupNotificationT()
        x._UnPack(tapDetectionSetupNotification)
        return x

    # TapDetectionSetupNotificationT
    def _UnPack(self, tapDetectionSetupNotification):
        if tapDetectionSetupNotification is None:
            return
        if tapDetectionSetupNotification.TrackerId() is not None:
            self.trackerId = TrackerIdT.InitFromObj(tapDetectionSetupNotification.TrackerId())

    # TapDetectionSetupNotificationT
    def Pack(self, builder):
        if self.trackerId is not None:
            trackerId = self.trackerId.Pack(builder)
        TapDetectionSetupNotificationStart(builder)
        if self.trackerId is not None:
            TapDetectionSetupNotificationAddTrackerId(builder, trackerId)
        tapDetectionSetupNotification = TapDetectionSetupNotificationEnd(builder)
        return tapDetectionSetupNotification
