# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TimeoutSettings(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TimeoutSettings()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTimeoutSettings(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TimeoutSettings
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TimeoutSettings
    def Duration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def TimeoutSettingsStart(builder):
    builder.StartObject(1)

def Start(builder):
    TimeoutSettingsStart(builder)

def TimeoutSettingsAddDuration(builder, duration):
    builder.PrependFloat32Slot(0, duration, 0.0)

def AddDuration(builder, duration):
    TimeoutSettingsAddDuration(builder, duration)

def TimeoutSettingsEnd(builder):
    return builder.EndObject()

def End(builder):
    return TimeoutSettingsEnd(builder)


class TimeoutSettingsT(object):

    # TimeoutSettingsT
    def __init__(
        self,
        duration = 0.0,
    ):
        self.duration = duration  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        timeoutSettings = TimeoutSettings()
        timeoutSettings.Init(buf, pos)
        return cls.InitFromObj(timeoutSettings)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, timeoutSettings):
        x = TimeoutSettingsT()
        x._UnPack(timeoutSettings)
        return x

    # TimeoutSettingsT
    def _UnPack(self, timeoutSettings):
        if timeoutSettings is None:
            return
        self.duration = timeoutSettings.Duration()

    # TimeoutSettingsT
    def Pack(self, builder):
        TimeoutSettingsStart(builder)
        TimeoutSettingsAddDuration(builder, self.duration)
        timeoutSettings = TimeoutSettingsEnd(builder)
        return timeoutSettings
