# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TrackingChecklistPublicNetworks(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrackingChecklistPublicNetworks()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTrackingChecklistPublicNetworks(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TrackingChecklistPublicNetworks
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TrackingChecklistPublicNetworks
    def Adapters(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # TrackingChecklistPublicNetworks
    def AdaptersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TrackingChecklistPublicNetworks
    def AdaptersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def TrackingChecklistPublicNetworksStart(builder):
    builder.StartObject(1)

def Start(builder):
    TrackingChecklistPublicNetworksStart(builder)

def TrackingChecklistPublicNetworksAddAdapters(builder, adapters):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(adapters), 0)

def AddAdapters(builder, adapters):
    TrackingChecklistPublicNetworksAddAdapters(builder, adapters)

def TrackingChecklistPublicNetworksStartAdaptersVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAdaptersVector(builder, numElems):
    return TrackingChecklistPublicNetworksStartAdaptersVector(builder, numElems)

def TrackingChecklistPublicNetworksEnd(builder):
    return builder.EndObject()

def End(builder):
    return TrackingChecklistPublicNetworksEnd(builder)

try:
    from typing import List
except:
    pass

class TrackingChecklistPublicNetworksT(object):

    # TrackingChecklistPublicNetworksT
    def __init__(
        self,
        adapters = None,
    ):
        self.adapters = adapters  # type: Optional[List[Optional[str]]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        trackingChecklistPublicNetworks = TrackingChecklistPublicNetworks()
        trackingChecklistPublicNetworks.Init(buf, pos)
        return cls.InitFromObj(trackingChecklistPublicNetworks)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, trackingChecklistPublicNetworks):
        x = TrackingChecklistPublicNetworksT()
        x._UnPack(trackingChecklistPublicNetworks)
        return x

    # TrackingChecklistPublicNetworksT
    def _UnPack(self, trackingChecklistPublicNetworks):
        if trackingChecklistPublicNetworks is None:
            return
        if not trackingChecklistPublicNetworks.AdaptersIsNone():
            self.adapters = []
            for i in range(trackingChecklistPublicNetworks.AdaptersLength()):
                self.adapters.append(trackingChecklistPublicNetworks.Adapters(i))

    # TrackingChecklistPublicNetworksT
    def Pack(self, builder):
        if self.adapters is not None:
            adapterslist = []
            for i in range(len(self.adapters)):
                adapterslist.append(builder.CreateString(self.adapters[i]))
            TrackingChecklistPublicNetworksStartAdaptersVector(builder, len(self.adapters))
            for i in reversed(range(len(self.adapters))):
                builder.PrependUOffsetTRelative(adapterslist[i])
            adapters = builder.EndVector()
        TrackingChecklistPublicNetworksStart(builder)
        if self.adapters is not None:
            TrackingChecklistPublicNetworksAddAdapters(builder, adapters)
        trackingChecklistPublicNetworks = TrackingChecklistPublicNetworksEnd(builder)
        return trackingChecklistPublicNetworks
