# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Requests the current state of tracking pause
class TrackingPauseStateRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrackingPauseStateRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTrackingPauseStateRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TrackingPauseStateRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def TrackingPauseStateRequestStart(builder):
    builder.StartObject(0)

def Start(builder):
    TrackingPauseStateRequestStart(builder)

def TrackingPauseStateRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return TrackingPauseStateRequestEnd(builder)


class TrackingPauseStateRequestT(object):

    # TrackingPauseStateRequestT
    def __init__(
        self,
    ):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        trackingPauseStateRequest = TrackingPauseStateRequest()
        trackingPauseStateRequest.Init(buf, pos)
        return cls.InitFromObj(trackingPauseStateRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, trackingPauseStateRequest):
        x = TrackingPauseStateRequestT()
        x._UnPack(trackingPauseStateRequest)
        return x

    # TrackingPauseStateRequestT
    def _UnPack(self, trackingPauseStateRequest):
        if trackingPauseStateRequest is None:
            return

    # TrackingPauseStateRequestT
    def Pack(self, builder):
        TrackingPauseStateRequestStart(builder)
        trackingPauseStateRequest = TrackingPauseStateRequestEnd(builder)
        return trackingPauseStateRequest
