# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.datatypes.TrackerId import TrackerIdT
from solarxr_protocol.datatypes.TrackerId import TrackerId

class TrackingChecklistUnassignedHMD(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrackingChecklistUnassignedHMD()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTrackingChecklistUnassignedHMD(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TrackingChecklistUnassignedHMD
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TrackingChecklistUnassignedHMD
    def TrackerId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = TrackerId()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def TrackingChecklistUnassignedHMDStart(builder):
    builder.StartObject(1)

def Start(builder):
    TrackingChecklistUnassignedHMDStart(builder)

def TrackingChecklistUnassignedHMDAddTrackerId(builder, trackerId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(trackerId), 0)

def AddTrackerId(builder, trackerId):
    TrackingChecklistUnassignedHMDAddTrackerId(builder, trackerId)

def TrackingChecklistUnassignedHMDEnd(builder):
    return builder.EndObject()

def End(builder):
    return TrackingChecklistUnassignedHMDEnd(builder)

try:
    from typing import Optional
except:
    pass

class TrackingChecklistUnassignedHMDT(object):

    # TrackingChecklistUnassignedHMDT
    def __init__(
        self,
        trackerId = None,
    ):
        self.trackerId = trackerId  # type: Optional[TrackerIdT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        trackingChecklistUnassignedHmd = TrackingChecklistUnassignedHMD()
        trackingChecklistUnassignedHmd.Init(buf, pos)
        return cls.InitFromObj(trackingChecklistUnassignedHmd)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, trackingChecklistUnassignedHmd):
        x = TrackingChecklistUnassignedHMDT()
        x._UnPack(trackingChecklistUnassignedHmd)
        return x

    # TrackingChecklistUnassignedHMDT
    def _UnPack(self, trackingChecklistUnassignedHmd):
        if trackingChecklistUnassignedHmd is None:
            return
        if trackingChecklistUnassignedHmd.TrackerId() is not None:
            self.trackerId = TrackerIdT.InitFromObj(trackingChecklistUnassignedHmd.TrackerId())

    # TrackingChecklistUnassignedHMDT
    def Pack(self, builder):
        if self.trackerId is not None:
            trackerId = self.trackerId.Pack(builder)
        TrackingChecklistUnassignedHMDStart(builder)
        if self.trackerId is not None:
            TrackingChecklistUnassignedHMDAddTrackerId(builder, trackerId)
        trackingChecklistUnassignedHmd = TrackingChecklistUnassignedHMDEnd(builder)
        return trackingChecklistUnassignedHmd
