# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.rpc.TrackingChecklistStep import TrackingChecklistStepT
from solarxr_protocol.rpc.TrackingChecklistStep import TrackingChecklistStep

class TrackingChecklistResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrackingChecklistResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTrackingChecklistResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TrackingChecklistResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TrackingChecklistResponse
    def Steps(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = TrackingChecklistStep()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrackingChecklistResponse
    def StepsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TrackingChecklistResponse
    def StepsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # TrackingChecklistResponse
    def IgnoredSteps(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # TrackingChecklistResponse
    def IgnoredStepsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # TrackingChecklistResponse
    def IgnoredStepsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TrackingChecklistResponse
    def IgnoredStepsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def TrackingChecklistResponseStart(builder):
    builder.StartObject(2)

def Start(builder):
    TrackingChecklistResponseStart(builder)

def TrackingChecklistResponseAddSteps(builder, steps):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(steps), 0)

def AddSteps(builder, steps):
    TrackingChecklistResponseAddSteps(builder, steps)

def TrackingChecklistResponseStartStepsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartStepsVector(builder, numElems):
    return TrackingChecklistResponseStartStepsVector(builder, numElems)

def TrackingChecklistResponseAddIgnoredSteps(builder, ignoredSteps):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(ignoredSteps), 0)

def AddIgnoredSteps(builder, ignoredSteps):
    TrackingChecklistResponseAddIgnoredSteps(builder, ignoredSteps)

def TrackingChecklistResponseStartIgnoredStepsVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartIgnoredStepsVector(builder, numElems):
    return TrackingChecklistResponseStartIgnoredStepsVector(builder, numElems)

def TrackingChecklistResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return TrackingChecklistResponseEnd(builder)

try:
    from typing import List
except:
    pass

class TrackingChecklistResponseT(object):

    # TrackingChecklistResponseT
    def __init__(
        self,
        steps = None,
        ignoredSteps = None,
    ):
        self.steps = steps  # type: Optional[List[TrackingChecklistStepT]]
        self.ignoredSteps = ignoredSteps  # type: Optional[List[int]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        trackingChecklistResponse = TrackingChecklistResponse()
        trackingChecklistResponse.Init(buf, pos)
        return cls.InitFromObj(trackingChecklistResponse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, trackingChecklistResponse):
        x = TrackingChecklistResponseT()
        x._UnPack(trackingChecklistResponse)
        return x

    # TrackingChecklistResponseT
    def _UnPack(self, trackingChecklistResponse):
        if trackingChecklistResponse is None:
            return
        if not trackingChecklistResponse.StepsIsNone():
            self.steps = []
            for i in range(trackingChecklistResponse.StepsLength()):
                if trackingChecklistResponse.Steps(i) is None:
                    self.steps.append(None)
                else:
                    trackingChecklistStep_ = TrackingChecklistStepT.InitFromObj(trackingChecklistResponse.Steps(i))
                    self.steps.append(trackingChecklistStep_)
        if not trackingChecklistResponse.IgnoredStepsIsNone():
            if np is None:
                self.ignoredSteps = []
                for i in range(trackingChecklistResponse.IgnoredStepsLength()):
                    self.ignoredSteps.append(trackingChecklistResponse.IgnoredSteps(i))
            else:
                self.ignoredSteps = trackingChecklistResponse.IgnoredStepsAsNumpy()

    # TrackingChecklistResponseT
    def Pack(self, builder):
        if self.steps is not None:
            stepslist = []
            for i in range(len(self.steps)):
                stepslist.append(self.steps[i].Pack(builder))
            TrackingChecklistResponseStartStepsVector(builder, len(self.steps))
            for i in reversed(range(len(self.steps))):
                builder.PrependUOffsetTRelative(stepslist[i])
            steps = builder.EndVector()
        if self.ignoredSteps is not None:
            if np is not None and type(self.ignoredSteps) is np.ndarray:
                ignoredSteps = builder.CreateNumpyVector(self.ignoredSteps)
            else:
                TrackingChecklistResponseStartIgnoredStepsVector(builder, len(self.ignoredSteps))
                for i in reversed(range(len(self.ignoredSteps))):
                    builder.PrependUint8(self.ignoredSteps[i])
                ignoredSteps = builder.EndVector()
        TrackingChecklistResponseStart(builder)
        if self.steps is not None:
            TrackingChecklistResponseAddSteps(builder, steps)
        if self.ignoredSteps is not None:
            TrackingChecklistResponseAddIgnoredSteps(builder, ignoredSteps)
        trackingChecklistResponse = TrackingChecklistResponseEnd(builder)
        return trackingChecklistResponse
