# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TrackingChecklistRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrackingChecklistRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTrackingChecklistRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TrackingChecklistRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def TrackingChecklistRequestStart(builder):
    builder.StartObject(0)

def Start(builder):
    TrackingChecklistRequestStart(builder)

def TrackingChecklistRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return TrackingChecklistRequestEnd(builder)


class TrackingChecklistRequestT(object):

    # TrackingChecklistRequestT
    def __init__(
        self,
    ):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        trackingChecklistRequest = TrackingChecklistRequest()
        trackingChecklistRequest.Init(buf, pos)
        return cls.InitFromObj(trackingChecklistRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, trackingChecklistRequest):
        x = TrackingChecklistRequestT()
        x._UnPack(trackingChecklistRequest)
        return x

    # TrackingChecklistRequestT
    def _UnPack(self, trackingChecklistRequest):
        if trackingChecklistRequest is None:
            return

    # TrackingChecklistRequestT
    def Pack(self, builder):
        TrackingChecklistRequestStart(builder)
        trackingChecklistRequest = TrackingChecklistRequestEnd(builder)
        return trackingChecklistRequest
