# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TrackingChecklistSteamVRDisconnected(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrackingChecklistSteamVRDisconnected()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTrackingChecklistSteamVRDisconnected(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TrackingChecklistSteamVRDisconnected
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Name of bridge in the server's config
    # TrackingChecklistSteamVRDisconnected
    def BridgeSettingsName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Is the driver installed?
    # TrackingChecklistSteamVRDisconnected
    def DriverInstalled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Has the driver been blocked due to SteamVR's "safe mode"?
    # TrackingChecklistSteamVRDisconnected
    def DriverBlockedBySafeMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Is the driver enabled in SteamVR settings?
    # TrackingChecklistSteamVRDisconnected
    def DriverEnabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def TrackingChecklistSteamVRDisconnectedStart(builder):
    builder.StartObject(4)

def Start(builder):
    TrackingChecklistSteamVRDisconnectedStart(builder)

def TrackingChecklistSteamVRDisconnectedAddBridgeSettingsName(builder, bridgeSettingsName):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(bridgeSettingsName), 0)

def AddBridgeSettingsName(builder, bridgeSettingsName):
    TrackingChecklistSteamVRDisconnectedAddBridgeSettingsName(builder, bridgeSettingsName)

def TrackingChecklistSteamVRDisconnectedAddDriverInstalled(builder, driverInstalled):
    builder.PrependBoolSlot(1, driverInstalled, 0)

def AddDriverInstalled(builder, driverInstalled):
    TrackingChecklistSteamVRDisconnectedAddDriverInstalled(builder, driverInstalled)

def TrackingChecklistSteamVRDisconnectedAddDriverBlockedBySafeMode(builder, driverBlockedBySafeMode):
    builder.PrependBoolSlot(2, driverBlockedBySafeMode, 0)

def AddDriverBlockedBySafeMode(builder, driverBlockedBySafeMode):
    TrackingChecklistSteamVRDisconnectedAddDriverBlockedBySafeMode(builder, driverBlockedBySafeMode)

def TrackingChecklistSteamVRDisconnectedAddDriverEnabled(builder, driverEnabled):
    builder.PrependBoolSlot(3, driverEnabled, 0)

def AddDriverEnabled(builder, driverEnabled):
    TrackingChecklistSteamVRDisconnectedAddDriverEnabled(builder, driverEnabled)

def TrackingChecklistSteamVRDisconnectedEnd(builder):
    return builder.EndObject()

def End(builder):
    return TrackingChecklistSteamVRDisconnectedEnd(builder)


class TrackingChecklistSteamVRDisconnectedT(object):

    # TrackingChecklistSteamVRDisconnectedT
    def __init__(
        self,
        bridgeSettingsName = None,
        driverInstalled = False,
        driverBlockedBySafeMode = False,
        driverEnabled = False,
    ):
        self.bridgeSettingsName = bridgeSettingsName  # type: Optional[str]
        self.driverInstalled = driverInstalled  # type: bool
        self.driverBlockedBySafeMode = driverBlockedBySafeMode  # type: bool
        self.driverEnabled = driverEnabled  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        trackingChecklistSteamVrdisconnected = TrackingChecklistSteamVRDisconnected()
        trackingChecklistSteamVrdisconnected.Init(buf, pos)
        return cls.InitFromObj(trackingChecklistSteamVrdisconnected)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, trackingChecklistSteamVrdisconnected):
        x = TrackingChecklistSteamVRDisconnectedT()
        x._UnPack(trackingChecklistSteamVrdisconnected)
        return x

    # TrackingChecklistSteamVRDisconnectedT
    def _UnPack(self, trackingChecklistSteamVrdisconnected):
        if trackingChecklistSteamVrdisconnected is None:
            return
        self.bridgeSettingsName = trackingChecklistSteamVrdisconnected.BridgeSettingsName()
        self.driverInstalled = trackingChecklistSteamVrdisconnected.DriverInstalled()
        self.driverBlockedBySafeMode = trackingChecklistSteamVrdisconnected.DriverBlockedBySafeMode()
        self.driverEnabled = trackingChecklistSteamVrdisconnected.DriverEnabled()

    # TrackingChecklistSteamVRDisconnectedT
    def Pack(self, builder):
        if self.bridgeSettingsName is not None:
            bridgeSettingsName = builder.CreateString(self.bridgeSettingsName)
        TrackingChecklistSteamVRDisconnectedStart(builder)
        if self.bridgeSettingsName is not None:
            TrackingChecklistSteamVRDisconnectedAddBridgeSettingsName(builder, bridgeSettingsName)
        TrackingChecklistSteamVRDisconnectedAddDriverInstalled(builder, self.driverInstalled)
        TrackingChecklistSteamVRDisconnectedAddDriverBlockedBySafeMode(builder, self.driverBlockedBySafeMode)
        TrackingChecklistSteamVRDisconnectedAddDriverEnabled(builder, self.driverEnabled)
        trackingChecklistSteamVrdisconnected = TrackingChecklistSteamVRDisconnectedEnd(builder)
        return trackingChecklistSteamVrdisconnected
