from solarxr_protocol.rpc.TrackingChecklistNeedCalibration import TrackingChecklistNeedCalibrationT
from solarxr_protocol.rpc.TrackingChecklistPublicNetworks import TrackingChecklistPublicNetworksT
from solarxr_protocol.rpc.TrackingChecklistSteamVRDisconnected import TrackingChecklistSteamVRDisconnectedT
from solarxr_protocol.rpc.TrackingChecklistTrackerError import TrackingChecklistTrackerErrorT
from solarxr_protocol.rpc.TrackingChecklistTrackerReset import TrackingChecklistTrackerResetT
from solarxr_protocol.rpc.TrackingChecklistUnassignedHMD import TrackingChecklistUnassignedHMDT
# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

class TrackingChecklistExtraData(object):
    NONE = 0
    TrackingChecklistTrackerReset = 1
    TrackingChecklistTrackerError = 2
    TrackingChecklistSteamVRDisconnected = 3
    TrackingChecklistUnassignedHMD = 4
    TrackingChecklistNeedCalibration = 5
    TrackingChecklistPublicNetworks = 6

def TrackingChecklistExtraDataCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == TrackingChecklistExtraData.TrackingChecklistTrackerReset:
        return TrackingChecklistTrackerResetT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == TrackingChecklistExtraData.TrackingChecklistTrackerError:
        return TrackingChecklistTrackerErrorT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == TrackingChecklistExtraData.TrackingChecklistSteamVRDisconnected:
        return TrackingChecklistSteamVRDisconnectedT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == TrackingChecklistExtraData.TrackingChecklistUnassignedHMD:
        return TrackingChecklistUnassignedHMDT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == TrackingChecklistExtraData.TrackingChecklistNeedCalibration:
        return TrackingChecklistNeedCalibrationT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == TrackingChecklistExtraData.TrackingChecklistPublicNetworks:
        return TrackingChecklistPublicNetworksT.InitFromBuf(table.Bytes, table.Pos)
    return None
