# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Server notifies connection of an unknown device.
# If the notification is no longer sent, it means the device connected to another
# server, got connected to this server or it was turned off.
class UnknownDeviceHandshakeNotification(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UnknownDeviceHandshakeNotification()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUnknownDeviceHandshakeNotification(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UnknownDeviceHandshakeNotification
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UnknownDeviceHandshakeNotification
    def MacAddress(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def UnknownDeviceHandshakeNotificationStart(builder):
    builder.StartObject(1)

def Start(builder):
    UnknownDeviceHandshakeNotificationStart(builder)

def UnknownDeviceHandshakeNotificationAddMacAddress(builder, macAddress):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(macAddress), 0)

def AddMacAddress(builder, macAddress):
    UnknownDeviceHandshakeNotificationAddMacAddress(builder, macAddress)

def UnknownDeviceHandshakeNotificationEnd(builder):
    return builder.EndObject()

def End(builder):
    return UnknownDeviceHandshakeNotificationEnd(builder)


class UnknownDeviceHandshakeNotificationT(object):

    # UnknownDeviceHandshakeNotificationT
    def __init__(
        self,
        macAddress = None,
    ):
        self.macAddress = macAddress  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        unknownDeviceHandshakeNotification = UnknownDeviceHandshakeNotification()
        unknownDeviceHandshakeNotification.Init(buf, pos)
        return cls.InitFromObj(unknownDeviceHandshakeNotification)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, unknownDeviceHandshakeNotification):
        x = UnknownDeviceHandshakeNotificationT()
        x._UnPack(unknownDeviceHandshakeNotification)
        return x

    # UnknownDeviceHandshakeNotificationT
    def _UnPack(self, unknownDeviceHandshakeNotification):
        if unknownDeviceHandshakeNotification is None:
            return
        self.macAddress = unknownDeviceHandshakeNotification.MacAddress()

    # UnknownDeviceHandshakeNotificationT
    def Pack(self, builder):
        if self.macAddress is not None:
            macAddress = builder.CreateString(self.macAddress)
        UnknownDeviceHandshakeNotificationStart(builder)
        if self.macAddress is not None:
            UnknownDeviceHandshakeNotificationAddMacAddress(builder, macAddress)
        unknownDeviceHandshakeNotification = UnknownDeviceHandshakeNotificationEnd(builder)
        return unknownDeviceHandshakeNotification
