# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserHeightRecordingStatusResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserHeightRecordingStatusResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserHeightRecordingStatusResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserHeightRecordingStatusResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserHeightRecordingStatusResponse
    def HmdHeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # UserHeightRecordingStatusResponse
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def UserHeightRecordingStatusResponseStart(builder):
    builder.StartObject(2)

def Start(builder):
    UserHeightRecordingStatusResponseStart(builder)

def UserHeightRecordingStatusResponseAddHmdHeight(builder, hmdHeight):
    builder.PrependFloat32Slot(0, hmdHeight, 0.0)

def AddHmdHeight(builder, hmdHeight):
    UserHeightRecordingStatusResponseAddHmdHeight(builder, hmdHeight)

def UserHeightRecordingStatusResponseAddStatus(builder, status):
    builder.PrependUint8Slot(1, status, 0)

def AddStatus(builder, status):
    UserHeightRecordingStatusResponseAddStatus(builder, status)

def UserHeightRecordingStatusResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserHeightRecordingStatusResponseEnd(builder)


class UserHeightRecordingStatusResponseT(object):

    # UserHeightRecordingStatusResponseT
    def __init__(
        self,
        hmdHeight = 0.0,
        status = 0,
    ):
        self.hmdHeight = hmdHeight  # type: float
        self.status = status  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        userHeightRecordingStatusResponse = UserHeightRecordingStatusResponse()
        userHeightRecordingStatusResponse.Init(buf, pos)
        return cls.InitFromObj(userHeightRecordingStatusResponse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, userHeightRecordingStatusResponse):
        x = UserHeightRecordingStatusResponseT()
        x._UnPack(userHeightRecordingStatusResponse)
        return x

    # UserHeightRecordingStatusResponseT
    def _UnPack(self, userHeightRecordingStatusResponse):
        if userHeightRecordingStatusResponse is None:
            return
        self.hmdHeight = userHeightRecordingStatusResponse.HmdHeight()
        self.status = userHeightRecordingStatusResponse.Status()

    # UserHeightRecordingStatusResponseT
    def Pack(self, builder):
        UserHeightRecordingStatusResponseStart(builder)
        UserHeightRecordingStatusResponseAddHmdHeight(builder, self.hmdHeight)
        UserHeightRecordingStatusResponseAddStatus(builder, self.status)
        userHeightRecordingStatusResponse = UserHeightRecordingStatusResponseEnd(builder)
        return userHeightRecordingStatusResponse
