# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VelocitySettings(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VelocitySettings()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVelocitySettings(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VelocitySettings
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VelocitySettings
    def SendDerivedVelocity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def VelocitySettingsStart(builder):
    builder.StartObject(1)

def Start(builder):
    VelocitySettingsStart(builder)

def VelocitySettingsAddSendDerivedVelocity(builder, sendDerivedVelocity):
    builder.PrependBoolSlot(0, sendDerivedVelocity, 0)

def AddSendDerivedVelocity(builder, sendDerivedVelocity):
    VelocitySettingsAddSendDerivedVelocity(builder, sendDerivedVelocity)

def VelocitySettingsEnd(builder):
    return builder.EndObject()

def End(builder):
    return VelocitySettingsEnd(builder)


class VelocitySettingsT(object):

    # VelocitySettingsT
    def __init__(
        self,
        sendDerivedVelocity = False,
    ):
        self.sendDerivedVelocity = sendDerivedVelocity  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        velocitySettings = VelocitySettings()
        velocitySettings.Init(buf, pos)
        return cls.InitFromObj(velocitySettings)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, velocitySettings):
        x = VelocitySettingsT()
        x._UnPack(velocitySettings)
        return x

    # VelocitySettingsT
    def _UnPack(self, velocitySettings):
        if velocitySettings is None:
            return
        self.sendDerivedVelocity = velocitySettings.SendDerivedVelocity()

    # VelocitySettingsT
    def Pack(self, builder):
        VelocitySettingsStart(builder)
        VelocitySettingsAddSendDerivedVelocity(builder, self.sendDerivedVelocity)
        velocitySettings = VelocitySettingsEnd(builder)
        return velocitySettings
