# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()
from solarxr_protocol.rpc.VRCConfigRecommendedValues import VRCConfigRecommendedValuesT
from solarxr_protocol.rpc.VRCConfigValidity import VRCConfigValidityT
from solarxr_protocol.rpc.VRCConfigValues import VRCConfigValuesT
from solarxr_protocol.rpc.VRCConfigRecommendedValues import VRCConfigRecommendedValues
from solarxr_protocol.rpc.VRCConfigValidity import VRCConfigValidity
from solarxr_protocol.rpc.VRCConfigValues import VRCConfigValues

# Sent every time the vrchat config state gets updated
# used to display vrchat missconfig settings to the user
class VRCConfigStateChangeResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VRCConfigStateChangeResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVRCConfigStateChangeResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VRCConfigStateChangeResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VRCConfigStateChangeResponse
    def IsSupported(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # VRCConfigStateChangeResponse
    def Validity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = VRCConfigValidity()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VRCConfigStateChangeResponse
    def State(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = VRCConfigValues()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VRCConfigStateChangeResponse
    def Recommended(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = VRCConfigRecommendedValues()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VRCConfigStateChangeResponse
    def Muted(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # VRCConfigStateChangeResponse
    def MutedLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VRCConfigStateChangeResponse
    def MutedIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def VRCConfigStateChangeResponseStart(builder):
    builder.StartObject(5)

def Start(builder):
    VRCConfigStateChangeResponseStart(builder)

def VRCConfigStateChangeResponseAddIsSupported(builder, isSupported):
    builder.PrependBoolSlot(0, isSupported, 0)

def AddIsSupported(builder, isSupported):
    VRCConfigStateChangeResponseAddIsSupported(builder, isSupported)

def VRCConfigStateChangeResponseAddValidity(builder, validity):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(validity), 0)

def AddValidity(builder, validity):
    VRCConfigStateChangeResponseAddValidity(builder, validity)

def VRCConfigStateChangeResponseAddState(builder, state):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(state), 0)

def AddState(builder, state):
    VRCConfigStateChangeResponseAddState(builder, state)

def VRCConfigStateChangeResponseAddRecommended(builder, recommended):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(recommended), 0)

def AddRecommended(builder, recommended):
    VRCConfigStateChangeResponseAddRecommended(builder, recommended)

def VRCConfigStateChangeResponseAddMuted(builder, muted):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(muted), 0)

def AddMuted(builder, muted):
    VRCConfigStateChangeResponseAddMuted(builder, muted)

def VRCConfigStateChangeResponseStartMutedVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMutedVector(builder, numElems):
    return VRCConfigStateChangeResponseStartMutedVector(builder, numElems)

def VRCConfigStateChangeResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return VRCConfigStateChangeResponseEnd(builder)

try:
    from typing import List, Optional
except:
    pass

class VRCConfigStateChangeResponseT(object):

    # VRCConfigStateChangeResponseT
    def __init__(
        self,
        isSupported = False,
        validity = None,
        state = None,
        recommended = None,
        muted = None,
    ):
        self.isSupported = isSupported  # type: bool
        self.validity = validity  # type: Optional[VRCConfigValidityT]
        self.state = state  # type: Optional[VRCConfigValuesT]
        self.recommended = recommended  # type: Optional[VRCConfigRecommendedValuesT]
        self.muted = muted  # type: Optional[List[Optional[str]]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        vrcconfigStateChangeResponse = VRCConfigStateChangeResponse()
        vrcconfigStateChangeResponse.Init(buf, pos)
        return cls.InitFromObj(vrcconfigStateChangeResponse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, vrcconfigStateChangeResponse):
        x = VRCConfigStateChangeResponseT()
        x._UnPack(vrcconfigStateChangeResponse)
        return x

    # VRCConfigStateChangeResponseT
    def _UnPack(self, vrcconfigStateChangeResponse):
        if vrcconfigStateChangeResponse is None:
            return
        self.isSupported = vrcconfigStateChangeResponse.IsSupported()
        if vrcconfigStateChangeResponse.Validity() is not None:
            self.validity = VRCConfigValidityT.InitFromObj(vrcconfigStateChangeResponse.Validity())
        if vrcconfigStateChangeResponse.State() is not None:
            self.state = VRCConfigValuesT.InitFromObj(vrcconfigStateChangeResponse.State())
        if vrcconfigStateChangeResponse.Recommended() is not None:
            self.recommended = VRCConfigRecommendedValuesT.InitFromObj(vrcconfigStateChangeResponse.Recommended())
        if not vrcconfigStateChangeResponse.MutedIsNone():
            self.muted = []
            for i in range(vrcconfigStateChangeResponse.MutedLength()):
                self.muted.append(vrcconfigStateChangeResponse.Muted(i))

    # VRCConfigStateChangeResponseT
    def Pack(self, builder):
        if self.validity is not None:
            validity = self.validity.Pack(builder)
        if self.state is not None:
            state = self.state.Pack(builder)
        if self.recommended is not None:
            recommended = self.recommended.Pack(builder)
        if self.muted is not None:
            mutedlist = []
            for i in range(len(self.muted)):
                mutedlist.append(builder.CreateString(self.muted[i]))
            VRCConfigStateChangeResponseStartMutedVector(builder, len(self.muted))
            for i in reversed(range(len(self.muted))):
                builder.PrependUOffsetTRelative(mutedlist[i])
            muted = builder.EndVector()
        VRCConfigStateChangeResponseStart(builder)
        VRCConfigStateChangeResponseAddIsSupported(builder, self.isSupported)
        if self.validity is not None:
            VRCConfigStateChangeResponseAddValidity(builder, validity)
        if self.state is not None:
            VRCConfigStateChangeResponseAddState(builder, state)
        if self.recommended is not None:
            VRCConfigStateChangeResponseAddRecommended(builder, recommended)
        if self.muted is not None:
            VRCConfigStateChangeResponseAddMuted(builder, muted)
        vrcconfigStateChangeResponse = VRCConfigStateChangeResponseEnd(builder)
        return vrcconfigStateChangeResponse
