# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VRCConfigRecommendedValues(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VRCConfigRecommendedValues()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVRCConfigRecommendedValues(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VRCConfigRecommendedValues
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VRCConfigRecommendedValues
    def LegacyMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # VRCConfigRecommendedValues
    def ShoulderTrackingDisabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # VRCConfigRecommendedValues
    def UserHeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # VRCConfigRecommendedValues
    def CalibrationRange(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # VRCConfigRecommendedValues
    def CalibrationVisuals(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # VRCConfigRecommendedValues
    def TrackerModel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # VRCConfigRecommendedValues
    def SpineMode(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # VRCConfigRecommendedValues
    def SpineModeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # VRCConfigRecommendedValues
    def SpineModeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VRCConfigRecommendedValues
    def SpineModeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # VRCConfigRecommendedValues
    def AvatarMeasurementType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # VRCConfigRecommendedValues
    def ShoulderWidthCompensation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def VRCConfigRecommendedValuesStart(builder):
    builder.StartObject(9)

def Start(builder):
    VRCConfigRecommendedValuesStart(builder)

def VRCConfigRecommendedValuesAddLegacyMode(builder, legacyMode):
    builder.PrependBoolSlot(0, legacyMode, 0)

def AddLegacyMode(builder, legacyMode):
    VRCConfigRecommendedValuesAddLegacyMode(builder, legacyMode)

def VRCConfigRecommendedValuesAddShoulderTrackingDisabled(builder, shoulderTrackingDisabled):
    builder.PrependBoolSlot(1, shoulderTrackingDisabled, 0)

def AddShoulderTrackingDisabled(builder, shoulderTrackingDisabled):
    VRCConfigRecommendedValuesAddShoulderTrackingDisabled(builder, shoulderTrackingDisabled)

def VRCConfigRecommendedValuesAddUserHeight(builder, userHeight):
    builder.PrependFloat32Slot(2, userHeight, 0.0)

def AddUserHeight(builder, userHeight):
    VRCConfigRecommendedValuesAddUserHeight(builder, userHeight)

def VRCConfigRecommendedValuesAddCalibrationRange(builder, calibrationRange):
    builder.PrependFloat32Slot(3, calibrationRange, 0.0)

def AddCalibrationRange(builder, calibrationRange):
    VRCConfigRecommendedValuesAddCalibrationRange(builder, calibrationRange)

def VRCConfigRecommendedValuesAddCalibrationVisuals(builder, calibrationVisuals):
    builder.PrependBoolSlot(4, calibrationVisuals, 0)

def AddCalibrationVisuals(builder, calibrationVisuals):
    VRCConfigRecommendedValuesAddCalibrationVisuals(builder, calibrationVisuals)

def VRCConfigRecommendedValuesAddTrackerModel(builder, trackerModel):
    builder.PrependUint8Slot(5, trackerModel, 0)

def AddTrackerModel(builder, trackerModel):
    VRCConfigRecommendedValuesAddTrackerModel(builder, trackerModel)

def VRCConfigRecommendedValuesAddSpineMode(builder, spineMode):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(spineMode), 0)

def AddSpineMode(builder, spineMode):
    VRCConfigRecommendedValuesAddSpineMode(builder, spineMode)

def VRCConfigRecommendedValuesStartSpineModeVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartSpineModeVector(builder, numElems):
    return VRCConfigRecommendedValuesStartSpineModeVector(builder, numElems)

def VRCConfigRecommendedValuesAddAvatarMeasurementType(builder, avatarMeasurementType):
    builder.PrependUint8Slot(7, avatarMeasurementType, 0)

def AddAvatarMeasurementType(builder, avatarMeasurementType):
    VRCConfigRecommendedValuesAddAvatarMeasurementType(builder, avatarMeasurementType)

def VRCConfigRecommendedValuesAddShoulderWidthCompensation(builder, shoulderWidthCompensation):
    builder.PrependBoolSlot(8, shoulderWidthCompensation, 0)

def AddShoulderWidthCompensation(builder, shoulderWidthCompensation):
    VRCConfigRecommendedValuesAddShoulderWidthCompensation(builder, shoulderWidthCompensation)

def VRCConfigRecommendedValuesEnd(builder):
    return builder.EndObject()

def End(builder):
    return VRCConfigRecommendedValuesEnd(builder)

try:
    from typing import List
except:
    pass

class VRCConfigRecommendedValuesT(object):

    # VRCConfigRecommendedValuesT
    def __init__(
        self,
        legacyMode = False,
        shoulderTrackingDisabled = False,
        userHeight = 0.0,
        calibrationRange = 0.0,
        calibrationVisuals = False,
        trackerModel = 0,
        spineMode = None,
        avatarMeasurementType = 0,
        shoulderWidthCompensation = False,
    ):
        self.legacyMode = legacyMode  # type: bool
        self.shoulderTrackingDisabled = shoulderTrackingDisabled  # type: bool
        self.userHeight = userHeight  # type: float
        self.calibrationRange = calibrationRange  # type: float
        self.calibrationVisuals = calibrationVisuals  # type: bool
        self.trackerModel = trackerModel  # type: int
        self.spineMode = spineMode  # type: Optional[List[int]]
        self.avatarMeasurementType = avatarMeasurementType  # type: int
        self.shoulderWidthCompensation = shoulderWidthCompensation  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        vrcconfigRecommendedValues = VRCConfigRecommendedValues()
        vrcconfigRecommendedValues.Init(buf, pos)
        return cls.InitFromObj(vrcconfigRecommendedValues)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, vrcconfigRecommendedValues):
        x = VRCConfigRecommendedValuesT()
        x._UnPack(vrcconfigRecommendedValues)
        return x

    # VRCConfigRecommendedValuesT
    def _UnPack(self, vrcconfigRecommendedValues):
        if vrcconfigRecommendedValues is None:
            return
        self.legacyMode = vrcconfigRecommendedValues.LegacyMode()
        self.shoulderTrackingDisabled = vrcconfigRecommendedValues.ShoulderTrackingDisabled()
        self.userHeight = vrcconfigRecommendedValues.UserHeight()
        self.calibrationRange = vrcconfigRecommendedValues.CalibrationRange()
        self.calibrationVisuals = vrcconfigRecommendedValues.CalibrationVisuals()
        self.trackerModel = vrcconfigRecommendedValues.TrackerModel()
        if not vrcconfigRecommendedValues.SpineModeIsNone():
            if np is None:
                self.spineMode = []
                for i in range(vrcconfigRecommendedValues.SpineModeLength()):
                    self.spineMode.append(vrcconfigRecommendedValues.SpineMode(i))
            else:
                self.spineMode = vrcconfigRecommendedValues.SpineModeAsNumpy()
        self.avatarMeasurementType = vrcconfigRecommendedValues.AvatarMeasurementType()
        self.shoulderWidthCompensation = vrcconfigRecommendedValues.ShoulderWidthCompensation()

    # VRCConfigRecommendedValuesT
    def Pack(self, builder):
        if self.spineMode is not None:
            if np is not None and type(self.spineMode) is np.ndarray:
                spineMode = builder.CreateNumpyVector(self.spineMode)
            else:
                VRCConfigRecommendedValuesStartSpineModeVector(builder, len(self.spineMode))
                for i in reversed(range(len(self.spineMode))):
                    builder.PrependUint8(self.spineMode[i])
                spineMode = builder.EndVector()
        VRCConfigRecommendedValuesStart(builder)
        VRCConfigRecommendedValuesAddLegacyMode(builder, self.legacyMode)
        VRCConfigRecommendedValuesAddShoulderTrackingDisabled(builder, self.shoulderTrackingDisabled)
        VRCConfigRecommendedValuesAddUserHeight(builder, self.userHeight)
        VRCConfigRecommendedValuesAddCalibrationRange(builder, self.calibrationRange)
        VRCConfigRecommendedValuesAddCalibrationVisuals(builder, self.calibrationVisuals)
        VRCConfigRecommendedValuesAddTrackerModel(builder, self.trackerModel)
        if self.spineMode is not None:
            VRCConfigRecommendedValuesAddSpineMode(builder, spineMode)
        VRCConfigRecommendedValuesAddAvatarMeasurementType(builder, self.avatarMeasurementType)
        VRCConfigRecommendedValuesAddShoulderWidthCompensation(builder, self.shoulderWidthCompensation)
        vrcconfigRecommendedValues = VRCConfigRecommendedValuesEnd(builder)
        return vrcconfigRecommendedValues
