# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VRCConfigValues(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VRCConfigValues()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVRCConfigValues(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VRCConfigValues
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VRCConfigValues
    def LegacyMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # VRCConfigValues
    def ShoulderTrackingDisabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # VRCConfigValues
    def UserHeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # VRCConfigValues
    def CalibrationRange(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # VRCConfigValues
    def CalibrationVisuals(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # VRCConfigValues
    def TrackerModel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # VRCConfigValues
    def SpineMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # VRCConfigValues
    def AvatarMeasurementType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # VRCConfigValues
    def ShoulderWidthCompensation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def VRCConfigValuesStart(builder):
    builder.StartObject(9)

def Start(builder):
    VRCConfigValuesStart(builder)

def VRCConfigValuesAddLegacyMode(builder, legacyMode):
    builder.PrependBoolSlot(0, legacyMode, 0)

def AddLegacyMode(builder, legacyMode):
    VRCConfigValuesAddLegacyMode(builder, legacyMode)

def VRCConfigValuesAddShoulderTrackingDisabled(builder, shoulderTrackingDisabled):
    builder.PrependBoolSlot(1, shoulderTrackingDisabled, 0)

def AddShoulderTrackingDisabled(builder, shoulderTrackingDisabled):
    VRCConfigValuesAddShoulderTrackingDisabled(builder, shoulderTrackingDisabled)

def VRCConfigValuesAddUserHeight(builder, userHeight):
    builder.PrependFloat32Slot(2, userHeight, 0.0)

def AddUserHeight(builder, userHeight):
    VRCConfigValuesAddUserHeight(builder, userHeight)

def VRCConfigValuesAddCalibrationRange(builder, calibrationRange):
    builder.PrependFloat32Slot(3, calibrationRange, 0.0)

def AddCalibrationRange(builder, calibrationRange):
    VRCConfigValuesAddCalibrationRange(builder, calibrationRange)

def VRCConfigValuesAddCalibrationVisuals(builder, calibrationVisuals):
    builder.PrependBoolSlot(4, calibrationVisuals, 0)

def AddCalibrationVisuals(builder, calibrationVisuals):
    VRCConfigValuesAddCalibrationVisuals(builder, calibrationVisuals)

def VRCConfigValuesAddTrackerModel(builder, trackerModel):
    builder.PrependUint8Slot(5, trackerModel, 0)

def AddTrackerModel(builder, trackerModel):
    VRCConfigValuesAddTrackerModel(builder, trackerModel)

def VRCConfigValuesAddSpineMode(builder, spineMode):
    builder.PrependUint8Slot(6, spineMode, 0)

def AddSpineMode(builder, spineMode):
    VRCConfigValuesAddSpineMode(builder, spineMode)

def VRCConfigValuesAddAvatarMeasurementType(builder, avatarMeasurementType):
    builder.PrependUint8Slot(7, avatarMeasurementType, 0)

def AddAvatarMeasurementType(builder, avatarMeasurementType):
    VRCConfigValuesAddAvatarMeasurementType(builder, avatarMeasurementType)

def VRCConfigValuesAddShoulderWidthCompensation(builder, shoulderWidthCompensation):
    builder.PrependBoolSlot(8, shoulderWidthCompensation, 0)

def AddShoulderWidthCompensation(builder, shoulderWidthCompensation):
    VRCConfigValuesAddShoulderWidthCompensation(builder, shoulderWidthCompensation)

def VRCConfigValuesEnd(builder):
    return builder.EndObject()

def End(builder):
    return VRCConfigValuesEnd(builder)


class VRCConfigValuesT(object):

    # VRCConfigValuesT
    def __init__(
        self,
        legacyMode = False,
        shoulderTrackingDisabled = False,
        userHeight = 0.0,
        calibrationRange = 0.0,
        calibrationVisuals = False,
        trackerModel = 0,
        spineMode = 0,
        avatarMeasurementType = 0,
        shoulderWidthCompensation = False,
    ):
        self.legacyMode = legacyMode  # type: bool
        self.shoulderTrackingDisabled = shoulderTrackingDisabled  # type: bool
        self.userHeight = userHeight  # type: float
        self.calibrationRange = calibrationRange  # type: float
        self.calibrationVisuals = calibrationVisuals  # type: bool
        self.trackerModel = trackerModel  # type: int
        self.spineMode = spineMode  # type: int
        self.avatarMeasurementType = avatarMeasurementType  # type: int
        self.shoulderWidthCompensation = shoulderWidthCompensation  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        vrcconfigValues = VRCConfigValues()
        vrcconfigValues.Init(buf, pos)
        return cls.InitFromObj(vrcconfigValues)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, vrcconfigValues):
        x = VRCConfigValuesT()
        x._UnPack(vrcconfigValues)
        return x

    # VRCConfigValuesT
    def _UnPack(self, vrcconfigValues):
        if vrcconfigValues is None:
            return
        self.legacyMode = vrcconfigValues.LegacyMode()
        self.shoulderTrackingDisabled = vrcconfigValues.ShoulderTrackingDisabled()
        self.userHeight = vrcconfigValues.UserHeight()
        self.calibrationRange = vrcconfigValues.CalibrationRange()
        self.calibrationVisuals = vrcconfigValues.CalibrationVisuals()
        self.trackerModel = vrcconfigValues.TrackerModel()
        self.spineMode = vrcconfigValues.SpineMode()
        self.avatarMeasurementType = vrcconfigValues.AvatarMeasurementType()
        self.shoulderWidthCompensation = vrcconfigValues.ShoulderWidthCompensation()

    # VRCConfigValuesT
    def Pack(self, builder):
        VRCConfigValuesStart(builder)
        VRCConfigValuesAddLegacyMode(builder, self.legacyMode)
        VRCConfigValuesAddShoulderTrackingDisabled(builder, self.shoulderTrackingDisabled)
        VRCConfigValuesAddUserHeight(builder, self.userHeight)
        VRCConfigValuesAddCalibrationRange(builder, self.calibrationRange)
        VRCConfigValuesAddCalibrationVisuals(builder, self.calibrationVisuals)
        VRCConfigValuesAddTrackerModel(builder, self.trackerModel)
        VRCConfigValuesAddSpineMode(builder, self.spineMode)
        VRCConfigValuesAddAvatarMeasurementType(builder, self.avatarMeasurementType)
        VRCConfigValuesAddShoulderWidthCompensation(builder, self.shoulderWidthCompensation)
        vrcconfigValues = VRCConfigValuesEnd(builder)
        return vrcconfigValues
