# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# VRM Settings for rescaling to avatar-scale
class VRMSettings(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VRMSettings()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVRMSettings(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VRMSettings
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VRMSettings
    def VrmJson(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def VRMSettingsStart(builder):
    builder.StartObject(1)

def Start(builder):
    VRMSettingsStart(builder)

def VRMSettingsAddVrmJson(builder, vrmJson):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(vrmJson), 0)

def AddVrmJson(builder, vrmJson):
    VRMSettingsAddVrmJson(builder, vrmJson)

def VRMSettingsEnd(builder):
    return builder.EndObject()

def End(builder):
    return VRMSettingsEnd(builder)


class VRMSettingsT(object):

    # VRMSettingsT
    def __init__(
        self,
        vrmJson = None,
    ):
        self.vrmJson = vrmJson  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        vrmsettings = VRMSettings()
        vrmsettings.Init(buf, pos)
        return cls.InitFromObj(vrmsettings)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, vrmsettings):
        x = VRMSettingsT()
        x._UnPack(vrmsettings)
        return x

    # VRMSettingsT
    def _UnPack(self, vrmsettings):
        if vrmsettings is None:
            return
        self.vrmJson = vrmsettings.VrmJson()

    # VRMSettingsT
    def Pack(self, builder):
        if self.vrmJson is not None:
            vrmJson = builder.CreateString(self.vrmJson)
        VRMSettingsStart(builder)
        if self.vrmJson is not None:
            VRMSettingsAddVrmJson(builder, vrmJson)
        vrmsettings = VRMSettingsEnd(builder)
        return vrmsettings
